// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 7eee6911c525


import { spawn, type ChildProcess } from "node:child_process";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

let prismProcess: ChildProcess;

export async function setup() {
  const specPath = process.env.OPENAPI_SPEC_PATH
    ?? resolve(__dirname, "../../specs/platform-openapi.json");
  const port = process.env.PRISM_PORT ?? "4040";

  prismProcess = spawn("npx", [
    "@stoplight/prism-cli", "mock", specPath,
    "--port", port,
    "--host", "127.0.0.1",
    "--dynamic",
  ], { stdio: "pipe" });

  await waitForPort(parseInt(port), 30_000);
}

export async function teardown() {
  prismProcess?.kill("SIGTERM");
}

async function waitForPort(port: number, timeoutMs: number): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    // Fast-fail if Prism process exited (bad spec path, missing npx, etc.)
    if (prismProcess.exitCode !== null) {
      throw new Error(`Prism exited with code ${prismProcess.exitCode} before becoming ready`);
    }
    try {
      const res = await fetch(`http://127.0.0.1:${port}/`);
      if (res) return;
    } catch {
      // not ready yet
    }
    await new Promise((r) => setTimeout(r, 300));
  }
  throw new Error(`Prism did not start within ${timeoutMs}ms`);
}
