// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: f950c9307168

import { z } from "zod";
import { aclSchema, resolvedToolSchema, workerStatusSchema } from "./common.js";

/** API schema for an agent session. */
export const agentSessionSchema = z.object({
  agent: z.string().optional(), // Owning agent ID (agi_...)
  completed_at: z.string().optional(), // When the session completed
  created_at: z.string().optional(), // Creation timestamp
  error: z.string().optional(), // Error message if failed
  id: z.string(), // Agent session ID (ase_...)
  inbox: z.array(z.unknown()).optional(), // Inbox messages
  instructions: z.string().optional(), // Task description for the session
  is_system_session: z.boolean().optional(), // Whether this is a system-created session
  max_runs_per_turn: z.number().int().optional(), // Max tool runs per turn
  max_tokens: z.number().int().optional(), // Max tokens
  max_turns: z.number().int().optional(), // Max turns
  metadata: z.unknown().optional(), // Arbitrary metadata
  name: z.string().optional(), // Optional display name for the session
  result: z.unknown().optional(), // Session result
  started_at: z.string().optional(), // When the session started running
  status: z.string().optional(), // Session status (pending, running, waiting, completed, failed, cancelled)
  trajectory: z.string().optional(), // Trajectory ID for the durable session transcript
});
export type AgentSession = z.infer<typeof agentSessionSchema>;

/** List response for agent sessions. */
export const agentSessionListResponseSchema = z.object({
  data: z.array(agentSessionSchema), // List of agent sessions
});
export type AgentSessionListResponse = z.infer<typeof agentSessionListResponseSchema>;

/** API schema for the result of running an agent tool via impersonation. */
export const agentImpersonationToolRunResultSchema = z.object({
  duration_ms: z.number().int(), // Execution duration in milliseconds
  result: z.unknown(), // Tool execution result
});
export type AgentImpersonationToolRunResult = z.infer<typeof agentImpersonationToolRunResultSchema>;

/** API schema for an agent tool. */
export const agentToolSchema = z.object({
  agent: z.string().optional(), // Owning agent ID
  app: z.string().optional(), // Application ID
  builtin_tool_config: z.unknown().optional(), // Builtin tool configuration
  builtin_tool_key: z.string().optional(), // Builtin tool key
  config: z.string().optional(), // Config ID
  created_at: z.string().optional(), // Creation timestamp
  description: z.string().optional(), // Tool description
  handler_type: z.string().optional(), // Handler type
  id: z.string(), // Tool ID (atl_...)
  instruction: z.string().optional(), // Tool instruction
  kind: z.string().optional(), // Tool kind
  lookup_key: z.string().optional(), // Unique lookup key
  metadata: z.unknown().optional(), // Arbitrary metadata
  name: z.string().optional(), // Tool name
  parameters: z.unknown().optional(), // Tool parameters
  parameters_config: z.string().optional(), // Parameters config ID
  status: z.string().optional(), // Tool status
  updated_at: z.string().optional(), // Last update timestamp
});
export type AgentTool = z.infer<typeof agentToolSchema>;

/** API schema for an agent skill. */
export const agentSkillSchema = z.object({
  agent: z.string().optional(), // Owning agent ID
  app: z.string().optional(), // Application ID
  config: z.string().optional(), // Skill config ID
  created_at: z.string().optional(), // Creation timestamp
  id: z.string(), // Agent skill ID (ask_...)
  instruction: z.string().optional(), // Instruction override
  metadata: z.unknown().optional(), // Arbitrary metadata
  status: z.string().optional(), // Skill status
  updated_at: z.string().optional(), // Last update timestamp
});
export type AgentSkill = z.infer<typeof agentSkillSchema>;

/** API schema for an agent computer. */
export const agentComputerSchema = z.object({
  agent: z.string().optional(), // Owning agent
  app: z.string().optional(), // Application ID
  config: z.unknown().optional(), // Configuration
  created_at: z.string().optional(), // Creation timestamp
  error_message: z.string().optional(), // Error message
  id: z.string(), // Computer ID (cmp_...)
  last_active_at: z.string().optional(), // Last active timestamp
  lookup_key: z.string().optional(), // Unique lookup key
  metadata: z.unknown().optional(), // Arbitrary metadata
  name: z.string().optional(), // Computer name
  region: z.string().optional(), // Region
  sprite_url: z.string().optional(), // Sprite URL
  status: z.string().optional(), // Computer status
  updated_at: z.string().optional(), // Last update timestamp
});
export type AgentComputer = z.infer<typeof agentComputerSchema>;

/** API schema for an agent conversation history session. */
export const agentConversationHistorySchema = z.object({
  created_at: z.string().optional(), // Creation timestamp
  last_interaction_at: z.string().optional(), // Last interaction timestamp
  name: z.string().optional(), // Session name
  org: z.string().optional(), // Organization
  sandbox: z.string().optional(), // Sandbox
  session: z.string().optional(), // Session ID (ach_...)
});
export type AgentConversationHistory = z.infer<typeof agentConversationHistorySchema>;

/** API schema for an agent. */
export const agentSchema = z.object({
  acl: aclSchema.optional(), // Access control list. Contains grants array with principal_type, principal, and actions. Null when no ACL restrictions are applied.
  app: z.string().optional(), // Application
  created_at: z.string().optional(), // Creation timestamp
  default_model: z.string().optional(), // Default AI model
  email: z.string().optional(), // Agent email
  id: z.string(), // Agent ID (agi_...)
  identity: z.string().optional(), // Identity prompt
  lookup_key: z.string().optional(), // Unique lookup key
  metadata: z.unknown().optional(), // Arbitrary metadata
  name: z.string().optional(), // Agent name
  org: z.string().optional(), // Organization
  phone_number: z.string().optional(), // Agent phone number
  sandbox: z.string().optional(), // Sandbox
  team: z.string().optional(), // Owning team
  updated_at: z.string().optional(), // Last update timestamp
  user: z.string().optional(), // Owning user
});
export type Agent = z.infer<typeof agentSchema>;

/** API schema for an agent impersonation skill file entry. */
export const agentImpersonationSkillFileSchema = z.object({
  content_type: z.string().optional(), // Raw content type for the file
  download_url: z.string(), // URL to fetch raw file contents
  path: z.string(), // Relative path within the skill bundle
});
export type AgentImpersonationSkillFile = z.infer<typeof agentImpersonationSkillFileSchema>;

/** API schema for an agent impersonation skill manifest. */
export const agentImpersonationSkillManifestSchema = z.object({
  description: z.string().optional(), // Skill description
  entrypoint: z.string(), // Primary file path for the skill
  files: z.array(agentImpersonationSkillFileSchema), // Skill files
  id: z.string(), // Skill config ID
  name: z.string(), // Skill display name
  slug: z.string(), // Skill slug
});
export type AgentImpersonationSkillManifest = z.infer<typeof agentImpersonationSkillManifestSchema>;

/** API schema for an agent impersonation skill summary. */
export const agentImpersonationSkillSummarySchema = z.object({
  description: z.string().optional(), // Skill description
  id: z.string(), // Skill config ID
  name: z.string(), // Skill display name
  slug: z.string(), // Skill slug
});
export type AgentImpersonationSkillSummary = z.infer<typeof agentImpersonationSkillSummarySchema>;

/** Paginated list response for agents. */
export const agentListResponseSchema = z.object({
  data: z.array(agentSchema), // List of agents
  has_next: z.boolean().optional(), // Whether a next page exists
  has_prev: z.boolean().optional(), // Whether a previous page exists
  page: z.number().int().optional(), // Current page number
  page_size: z.number().int().optional(), // Results per page
  total_entries: z.number().int().optional(), // Total number of entries
  total_pages: z.number().int().optional(), // Total number of pages
});
export type AgentListResponse = z.infer<typeof agentListResponseSchema>;

/** List response for agent tools. */
export const agentToolListResponseSchema = z.object({
  data: z.array(agentToolSchema), // List of agent tools
});
export type AgentToolListResponse = z.infer<typeof agentToolListResponseSchema>;

/** API schema for an agent schedule. */
export const agentScheduleSchema = z.object({
  agent: z.string().optional(), // Owning agent ID
  app: z.string().optional(), // Application ID
  created_at: z.string().optional(), // Creation timestamp
  cron_expression: z.string().optional(), // Cron expression (recurring only)
  id: z.string(), // Schedule ID (asc_...)
  instructions: z.string().optional(), // Task instructions
  last_run_at: z.string().optional(), // Last execution time
  max_runs: z.number().int().optional(), // Maximum runs (recurring only)
  metadata: z.unknown().optional(), // Arbitrary metadata
  next_run_at: z.string().optional(), // Next scheduled execution
  run_count: z.number().int().optional(), // Number of times executed
  schedule_type: z.string().optional(), // Schedule type (once or recurring)
  scheduled_at: z.string().optional(), // One-time execution time
  status: z.string().optional(), // Schedule status
  thread: z.string().optional(), // Thread ID (if thread-bound)
  timezone: z.string().optional(), // Schedule timezone
  updated_at: z.string().optional(), // Last update timestamp
});
export type AgentSchedule = z.infer<typeof agentScheduleSchema>;

/** API schema for an agent routine run. */
export const agentRoutineRunSchema = z.object({
  acl: aclSchema.optional(), // Access control list. Contains grants array with principal_type, principal, and actions. Null when no ACL restrictions are applied.
  agent: z.string().optional(), // Agent
  app: z.string().optional(), // Application
  created_at: z.string().optional(), // Creation timestamp
  duration_ms: z.number().int().optional(), // Duration in milliseconds
  event_id: z.string().optional(), // Event ID
  id: z.string(), // Run ID (arr_...)
  metadata: z.unknown().optional(), // Run metadata
  payload: z.unknown().optional(), // Event payload
  result: z.unknown().optional(), // Run result
  routine: z.string().optional(), // Routine
  status: z.string().optional(), // Run status
  structured_response: z.unknown().optional(), // Validated structured response when the run uses an AgentMessageSchema
  updated_at: z.string().optional(), // Last update timestamp
  worker: workerStatusSchema.optional(), // Background worker status. Null when no worker job is associated.
});
export type AgentRoutineRun = z.infer<typeof agentRoutineRunSchema>;

/** Cursor-paginated list response for agent routine runs. */
export const agentRoutineRunListResponseSchema = z.object({
  after_cursor: z.string().optional(), // Cursor for fetching items after this point
  before_cursor: z.string().optional(), // Cursor for fetching items before this point
  data: z.array(agentRoutineRunSchema), // List of routine runs
});
export type AgentRoutineRunListResponse = z.infer<typeof agentRoutineRunListResponseSchema>;

/** API schema for a full agent impersonation manifest. */
export const agentImpersonationManifestSchema = z.object({
  agent: agentSchema, // Agent identity and metadata
  skills: z.array(agentImpersonationSkillSummarySchema), // Linked skills
  tools: z.array(agentToolSchema), // Active tools
});
export type AgentImpersonationManifest = z.infer<typeof agentImpersonationManifestSchema>;

/** API schema for an agent routine. */
export const agentRoutineSchema = z.object({
  acl: aclSchema.optional(), // Access control list. Contains grants array with principal_type, principal, and actions. Null when no ACL restrictions are applied.
  agent: z.string().optional(), // Owning agent ID
  app: z.string().optional(), // Application ID
  config: z.string().optional(), // Config ID
  created_at: z.string().optional(), // Creation timestamp
  description: z.string().optional(), // Routine description
  event_config: z.unknown().optional(), // Event configuration
  event_type: z.string().optional(), // Event type
  handler_type: z.string().optional(), // Handler type
  id: z.string(), // Routine ID (arn_...)
  lookup_key: z.string().optional(), // Unique lookup key
  metadata: z.unknown().optional(), // Arbitrary metadata
  name: z.string().optional(), // Routine name
  preset_config: z.unknown().optional(), // Preset configuration
  preset_name: z.string().optional(), // Preset name
  schedule: z.string().optional(), // Schedule expression
  script: z.string().optional(), // Script content
  status: z.string().optional(), // Routine status
  trigger_context: z.string().optional(), // Trigger context
  updated_at: z.string().optional(), // Last update timestamp
});
export type AgentRoutine = z.infer<typeof agentRoutineSchema>;

/** List response for agent routines. */
export const agentRoutineListResponseSchema = z.object({
  data: z.array(agentRoutineSchema), // List of agent routines
});
export type AgentRoutineListResponse = z.infer<typeof agentRoutineListResponseSchema>;

/** API schema for the resolved callable tools list response. */
export const agentImpersonationToolListSchema = z.object({
  data: z.array(resolvedToolSchema), // Resolved callable tools
});
export type AgentImpersonationToolList = z.infer<typeof agentImpersonationToolListSchema>;

/** API schema for an agent impersonation skill list response. */
export const agentImpersonationSkillListSchema = z.object({
  data: z.array(agentImpersonationSkillSummarySchema), // Agent-linked skills
});
export type AgentImpersonationSkillList = z.infer<typeof agentImpersonationSkillListSchema>;

/** API schema for agent skills list response. */
export const agentSkillListSchema = z.object({
  data: z.array(agentSkillSchema), // List of agent skills
});
export type AgentSkillList = z.infer<typeof agentSkillListSchema>;
