// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d7a1ff76ef26

import { z } from "zod";

/** Schema for an API call record.

Maps to serialized API call output from developer portal API.
 */
export const apiCallSchema = z.object({
  api_key_type: z.string().optional(), // API key type (publishable or secret)
  created_at: z.string().optional(), // Created timestamp
  error_message: z.string().optional(), // Error message if request failed
  event_type: z.string().optional(), // Webhook event type (e.g. push, pull_request)
  full_url: z.string(), // Full request URL with query string
  handler_module: z.string().optional(), // ApiDsl action module
  id: z.string(), // Public ID (aac_...)
  ip_address: z.string().optional(), // Client IP address
  latency_ms: z.number().int(), // Latency in milliseconds
  metadata: z.record(z.unknown()).optional(), // Additional metadata (e.g. integration_ids for webhooks)
  method: z.string(), // HTTP method
  org: z.string().optional(), // Org if org-scoped
  path: z.string(), // Sanitized path with param placeholders
  query_string: z.string().optional(), // Query string
  request_body: z.record(z.unknown()).optional(), // Request body payload (webhooks only)
  request_headers: z.record(z.unknown()).optional(), // Request headers (webhooks only)
  request_id: z.string().optional(), // Request ID from Plug.RequestId
  status_code: z.number().int(), // HTTP status code
  team: z.string().optional(), // Team if team-scoped
  thread: z.string().optional(), // Thread if thread-scoped
  user: z.string().optional(), // User if user-scoped
});
export type ApiCall = z.infer<typeof apiCallSchema>;

/** Schema for a documented API endpoint in the developer API explorer. */
export const apiExplorerEndpointSchema = z.object({
  deprecated: z.boolean(), // Whether the route is deprecated
  description: z.string().optional(), // Endpoint description
  errors: z.array(z.record(z.unknown())), // Documented error responses
  method: z.string(), // HTTP method
  params: z.array(z.record(z.unknown())), // Documented params
  path: z.string(), // Route path
  returns: z.record(z.unknown()).optional(), // Return schema description
  scope: z.string(), // Endpoint scope
  tags: z.array(z.string()), // Route tags
});
export type ApiExplorerEndpoint = z.infer<typeof apiExplorerEndpointSchema>;

/** Schema for the API explorer response. */
export const apiExplorerIndexSchema = z.object({
  data: z.array(apiExplorerEndpointSchema), // Documented API endpoints
  schemas: z.record(z.unknown()).optional(), // Collected schema definitions
});
export type ApiExplorerIndex = z.infer<typeof apiExplorerIndexSchema>;
