// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 2473af3dbae5

import { z } from "zod";

/** API schema for an artifact version. */
export const artifactVersionSchema = z.object({
  artifact: z.string().optional(), // Parent artifact
  change_description: z.string().optional(), // Description of changes
  content_type: z.string().optional(), // MIME content type
  created_at: z.string().optional(), // Creation timestamp
  file: z.string().optional(), // Storage file
  file_name: z.string().optional(), // Original filename
  file_url: z.string().optional(), // Signed file URL
  id: z.string(), // Artifact version ID
  image_source: z.unknown().optional(), // Image source metadata
  updated_at: z.string().optional(), // Last update timestamp
  version_number: z.number().int().optional(), // Version number
});
export type ArtifactVersion = z.infer<typeof artifactVersionSchema>;

/** API schema for an artifact. */
export const artifactSchema = z.object({
  agent: z.string().optional(), // Agent
  content_type: z.string().optional(), // MIME content type
  created_at: z.string().optional(), // Creation timestamp
  current_version: z.string().optional(), // Current version ID
  description: z.string().optional(), // Artifact description
  file: z.string().optional(), // Storage file
  file_name: z.string().optional(), // Original filename
  file_url: z.string().optional(), // Signed file URL
  id: z.string(), // Artifact ID
  image_source: z.unknown().optional(), // Image source metadata
  name: z.string().optional(), // Artifact name
  org: z.string().optional(), // Organization
  sandbox: z.string().optional(), // Sandbox identifier
  team: z.string().optional(), // Team
  thread: z.string().optional(), // Thread
  updated_at: z.string().optional(), // Last update timestamp
  user: z.string().optional(), // User
  version: z.number().int().optional(), // Current version number
});
export type Artifact = z.infer<typeof artifactSchema>;
