// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d4ead889ced7

import { z } from "zod";

/** API schema for a chat member (user or agent). */
export const chatMemberSchema = z.object({
  agent: z.unknown().optional(), // Agent object (for agent members)
  membership_type: z.string().optional(), // Membership type
  type: z.string(), // Member type (user or agent)
  user: z.unknown().optional(), // User object (for user members)
});
export type ChatMember = z.infer<typeof chatMemberSchema>;
