// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 01554be999d7

import { z } from "zod";

/** API schema for OAuth device authorization responses. */
export const deviceAuthorizationResponseSchema = z.object({
  device_code: z.string(), // Device verification code
  expires_in: z.number().int(), // TTL in seconds
  interval: z.number().int(), // Polling interval in seconds
  user_code: z.string(), // User-facing verification code
  verification_uri: z.string(), // Base verification URI
  verification_uri_complete: z.string(), // Full verification URI with code
});
export type DeviceAuthorizationResponse = z.infer<typeof deviceAuthorizationResponseSchema>;
