// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: bf4ebc59f1c0

import { z } from "zod";

/** API schema for image source metadata. */
export const imageSourceSchema = z.object({
  file: z.string().optional(), // Storage file
  height: z.number().int().optional(), // Image height in pixels
  media: z.string().optional(), // Media
  mime_type: z.string().optional(), // Image MIME type
  refresh_url: z.string().optional(), // URL to refresh signed URL
  url: z.string().optional(), // Image URL
  width: z.number().int().optional(), // Image width in pixels
});
export type ImageSource = z.infer<typeof imageSourceSchema>;
