// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 4a33bedceb33

import { z } from "zod";

/** Account that sent the invite */
export const inviterSchema = z.object({
  email: z.string(), // Inviter email
  full_name: z.string().optional(), // Inviter full name
  id: z.string(), // Inviter account ID
});
export type Inviter = z.infer<typeof inviterSchema>;
