// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 5027b0bdde55

import { z } from "zod";

/** API schema for a media variant. */
export const mediaVariantSchema = z.object({
  content_type: z.string().optional(), // File content type
  created_at: z.string().optional(), // Creation timestamp
  file: z.string().optional(), // Storage file
  filename: z.string().optional(), // Original filename
  height: z.number().int().optional(), // Height in pixels
  id: z.string(), // Variant ID
  image_source: z.unknown().optional(), // Image source metadata
  updated_at: z.string().optional(), // Last update timestamp
  url: z.string().optional(), // Signed download URL
  variant_key: z.string().optional(), // Variant key (original, thumbnail, etc)
  width: z.number().int().optional(), // Width in pixels
});
export type MediaVariant = z.infer<typeof mediaVariantSchema>;

/** Filter object for matching thread metadata. */
export const metadataFilterSchema = z.object({
  key: z.string(), // Metadata key to match
  type: z.string(), // Filter type (must be "metadata")
  value: z.string(), // Metadata value to match
});
export type MetadataFilter = z.infer<typeof metadataFilterSchema>;

/** API schema for a media item. */
export const mediaSchema = z.object({
  content_type: z.string().optional(), // Original variant content type
  created_at: z.string().optional(), // Creation timestamp
  filename: z.string().optional(), // Original variant filename
  height: z.number().int().optional(), // Original variant height
  id: z.string(), // Media ID
  media_type: z.string().optional(), // Media type
  name: z.string().optional(), // Media name
  org: z.string().optional(), // Organization
  sandbox: z.string().optional(), // Sandbox
  updated_at: z.string().optional(), // Last update timestamp
  url: z.string().optional(), // Original variant URL
  variants: z.array(z.unknown()).optional(), // Media variants
  width: z.number().int().optional(), // Original variant width
});
export type Media = z.infer<typeof mediaSchema>;
