// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 25e20d7f5f3c

import { z } from "zod";
import { userSchema } from "./users.js";

/** API schema for OAuth token endpoint responses. */
export const oAuthTokenResponseSchema = z.object({
  access_token: z.string(), // OAuth access token
  expires_in: z.number().int(), // Token TTL in seconds
  refresh_token: z.string().optional(), // OAuth refresh token
  scope: z.string().optional(), // Granted scopes (space-separated)
  token_type: z.string(), // Token type (Bearer)
  user: userSchema.optional(), // Authenticated user
});
export type OAuthTokenResponse = z.infer<typeof oAuthTokenResponseSchema>;

/** Schema for an OAuth provider configuration.

Maps to serialized OAuth provider output from developer portal API.
 */
export const oAuthProviderSchema = z.object({
  callback_urls: z.array(z.string()).optional(), // Allowed callback URLs
  client_id: z.string(), // OAuth client ID
  created_at: z.string().optional(), // Created timestamp
  display_name: z.string().optional(), // Display name
  enabled: z.boolean().optional(), // Whether provider is enabled
  id: z.string(), // Public ID (dop_...)
  provider: z.string(), // Provider type (github, google)
  scopes: z.array(z.string()).optional(), // OAuth scopes
  updated_at: z.string().optional(), // Updated timestamp
});
export type OAuthProvider = z.infer<typeof oAuthProviderSchema>;

/** OAuth error response per RFC 6749 */
export const oAuthErrorSchema = z.object({
  error: z.string(), // Error code (e.g. slow_down, invalid_grant)
  error_description: z.string().optional(), // Human-readable error description
});
export type OAuthError = z.infer<typeof oAuthErrorSchema>;

/** Schema for an OAuth client registration. */
export const oAuthClientSchema = z.object({
  client_id: z.string(), // Public OAuth client ID
  client_name: z.string(), // Display name for the client
  client_secret: z.string().optional(), // Client secret shown only at creation
  created_at: z.string().optional(), // Created timestamp
  enabled: z.boolean(), // Whether the client is enabled
  id: z.string(), // OAuth client registration ID
  redirect_uris: z.array(z.string()), // Allowed redirect URIs
  scopes: z.array(z.string()), // Allowed OAuth scopes
  updated_at: z.string().optional(), // Updated timestamp
});
export type OAuthClient = z.infer<typeof oAuthClientSchema>;

/** Schema for OAuth client list responses. */
export const oAuthClientListSchema = z.object({
  data: z.array(oAuthClientSchema), // OAuth clients
});
export type OAuthClientList = z.infer<typeof oAuthClientListSchema>;
