// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 29fd7a1aa724

import { z } from "zod";

/** Schema for picture upload parameters.

Used for uploading profile pictures via base64 encoded data.
 */
export const pictureParamsSchema = z.object({
  data: z.string(), // Base64 encoded image data
  filename: z.string(), // Original filename
  mime_type: z.string(), // MIME type of the image
});
export type PictureParams = z.infer<typeof pictureParamsSchema>;
