// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 79d888dbaacf

import { z } from "zod";

/** API schema for a message reaction. */
export const reactionSchema = z.object({
  created_at: z.string().optional(), // Creation timestamp
  feedback_type: z.string().optional(), // Type of feedback (e.g., emoji_reaction)
  id: z.string(), // Reaction ID (umf_...)
  message: z.string().optional(), // Message the reaction is on
  payload: z.unknown().optional(), // Reaction payload (e.g., {emoji: ...})
  updated_at: z.string().optional(), // Last update timestamp
  user: z.string().optional(), // User who added the reaction
});
export type Reaction = z.infer<typeof reactionSchema>;
