// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 4708e086112a

import { z } from "zod";

/** API schema for a system access token. */
export const systemAccessTokenSchema = z.object({
  created_at: z.string().optional(), // Creation timestamp
  id: z.string(), // Token ID (sat_...)
  last_used_at: z.string().optional(), // Last used timestamp
  name: z.string().optional(), // Token name
  revoked_at: z.string().optional(), // Revocation timestamp
});
export type SystemAccessToken = z.infer<typeof systemAccessTokenSchema>;
