// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: f318fc6ca6ac


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: custom_objects", () => {
  describe("custom_objects", () => {
    it("DELETE /api/v1/custom_objects/{object} returns successfully", async () => {
      const result = await client.v1.custom_objects.delete("test-value");
      expect(result).toBeUndefined();
    });

    it("DELETE /api/v1/custom_objects/{object} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.custom_objects.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("DELETE /api/v1/custom_objects/{object} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.custom_objects.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/custom_objects/{object} returns successfully", async () => {
      const result = await client.v1.custom_objects.get("test-value");
      expect(result).toBeDefined();
    });

    it("GET /api/v1/custom_objects/{object} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.custom_objects.get("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/custom_objects/{object} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.custom_objects.get("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("PUT /api/v1/custom_objects/{object} returns successfully", async () => {
      const result = await client.v1.custom_objects.replace("test-value", { fields: {} });
      expect(result).toBeDefined();
    });

    it("PUT /api/v1/custom_objects/{object} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.custom_objects.replace("test-value", { fields: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("PUT /api/v1/custom_objects/{object} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.custom_objects.replace("test-value", { fields: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("PUT /api/v1/custom_objects/{object} returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.custom_objects.replace("test-value", { fields: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

});
