// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d2e0eaf467a1


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: event_subscription_deliveries", () => {
  describe("event_subscription_deliveries", () => {
    it("POST /api/v1/event_subscription_deliveries/{delivery}/acknowledge returns successfully", async () => {
      const result = await client.v1.event_subscription_deliveries.acknowledge("test-value", { receipt_handle: "test-value" });
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/event_subscription_deliveries/{delivery}/acknowledge returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.event_subscription_deliveries.acknowledge("test-value", { receipt_handle: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/event_subscription_deliveries/{delivery}/acknowledge returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.event_subscription_deliveries.acknowledge("test-value", { receipt_handle: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/event_subscription_deliveries/{delivery}/acknowledge returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.event_subscription_deliveries.acknowledge("test-value", { receipt_handle: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

  });

});
