// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e032dab59148


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: invites", () => {
  describe("invites", () => {
    it("POST /api/v1/invites/accept returns successfully", async () => {
      const result = await client.v1.invites.accept({ key: "test-key" });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/invites/accept returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.invites.accept({ key: "test-key" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/invites/accept returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.invites.accept({ key: "test-key" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/invites/accept returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.invites.accept({ key: "test-key" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/invites/accept returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.invites.accept({ key: "test-key" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

    it("POST /api/v1/invites/accept returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.invites.accept({ key: "test-key" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/invites/accept returns 429", async () => {
      const ec = errorClient(429);
      try {
        await ec.v1.invites.accept({ key: "test-key" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(429);
      }
    });

  });

});
