// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 396012872479


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: notifications", () => {
  describe("notifications", () => {
    it("GET /api/v1/notifications returns successfully", async () => {
      const result = await client.v1.notifications.list();
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/notifications returns 400", async () => {
      const ec = errorClient(400);
      try {
        await ec.v1.notifications.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(400);
      }
    });

    it("GET /api/v1/notifications returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notifications.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/notifications returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notifications.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/notifications/read_all returns successfully", async () => {
      const result = await client.v1.notifications.readAll();
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/notifications/read_all returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notifications.readAll();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/notifications/read_all returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notifications.readAll();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/notifications/send returns successfully", async () => {
      const result = await client.v1.notifications.send({ type: "test", user: "test-value" });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/notifications/send returns 400", async () => {
      const ec = errorClient(400);
      try {
        await ec.v1.notifications.send({ type: "test", user: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(400);
      }
    });

    it("POST /api/v1/notifications/send returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notifications.send({ type: "test", user: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/notifications/send returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notifications.send({ type: "test", user: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/notifications/send returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.notifications.send({ type: "test", user: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/notifications/send returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.notifications.send({ type: "test", user: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("GET /api/v1/notifications/unread_count returns successfully", async () => {
      const result = await client.v1.notifications.unreadCount();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/notifications/unread_count returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notifications.unreadCount();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/notifications/unread_count returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notifications.unreadCount();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/notifications/{notification}/archive returns successfully", async () => {
      const result = await client.v1.notifications.archive("test-value");
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/notifications/{notification}/archive returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notifications.archive("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/notifications/{notification}/archive returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notifications.archive("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/notifications/{notification}/archive returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.notifications.archive("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/notifications/{notification}/read returns successfully", async () => {
      const result = await client.v1.notifications.read("test-value");
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/notifications/{notification}/read returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notifications.read("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/notifications/{notification}/read returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notifications.read("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/notifications/{notification}/read returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.notifications.read("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/notifications/{notification}/unarchive returns successfully", async () => {
      const result = await client.v1.notifications.unarchive("test-value");
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/notifications/{notification}/unarchive returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notifications.unarchive("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/notifications/{notification}/unarchive returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notifications.unarchive("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/notifications/{notification}/unarchive returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.notifications.unarchive("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

  });

});
