// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 0be0af69ed44


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: notification_preferences", () => {
  describe("notification_preferences", () => {
    it("DELETE /api/v1/notification_preferences returns successfully", async () => {
      const result = await client.v1.notification_preferences.remove();
      expect(result).toBeUndefined();
    });

    it("DELETE /api/v1/notification_preferences returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notification_preferences.remove();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("DELETE /api/v1/notification_preferences returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notification_preferences.remove();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("DELETE /api/v1/notification_preferences returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.notification_preferences.remove();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/notification_preferences returns successfully", async () => {
      const result = await client.v1.notification_preferences.list();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/notification_preferences returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notification_preferences.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/notification_preferences returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notification_preferences.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("PUT /api/v1/notification_preferences returns successfully", async () => {
      const result = await client.v1.notification_preferences.replace({ channel: "test-value", enabled: true, type: "test" });
      expect(result).toBeDefined();
    });

    it("PUT /api/v1/notification_preferences returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.notification_preferences.replace({ channel: "test-value", enabled: true, type: "test" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("PUT /api/v1/notification_preferences returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.notification_preferences.replace({ channel: "test-value", enabled: true, type: "test" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("PUT /api/v1/notification_preferences returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.notification_preferences.replace({ channel: "test-value", enabled: true, type: "test" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

});
