// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 8f1408e6f82d


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: private_service_enrollments", () => {
  describe("private_service_enrollments", () => {
    it("GET /api/v1/private_service_enrollments returns successfully", async () => {
      const result = await client.v1.private_service_enrollments.list();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/private_service_enrollments returns 400", async () => {
      const ec = errorClient(400);
      try {
        await ec.v1.private_service_enrollments.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(400);
      }
    });

    it("GET /api/v1/private_service_enrollments returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.private_service_enrollments.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("GET /api/v1/private_service_enrollments returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.private_service_enrollments.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/private_service_enrollments returns 503", async () => {
      const ec = errorClient(503);
      try {
        await ec.v1.private_service_enrollments.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(503);
      }
    });

    it("POST /api/v1/private_service_enrollments returns successfully", async () => {
      const result = await client.v1.private_service_enrollments.create({ private_service: "test-value" });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/private_service_enrollments returns 400", async () => {
      const ec = errorClient(400);
      try {
        await ec.v1.private_service_enrollments.create({ private_service: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(400);
      }
    });

    it("POST /api/v1/private_service_enrollments returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.private_service_enrollments.create({ private_service: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/private_service_enrollments returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.private_service_enrollments.create({ private_service: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/private_service_enrollments returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.private_service_enrollments.create({ private_service: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

    it("POST /api/v1/private_service_enrollments returns 503", async () => {
      const ec = errorClient(503);
      try {
        await ec.v1.private_service_enrollments.create({ private_service: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(503);
      }
    });

    it("GET /api/v1/private_service_enrollments/{private_service_enrollment_id} returns successfully", async () => {
      const result = await client.v1.private_service_enrollments.get("test-id");
      expect(result).toBeDefined();
    });

    it("GET /api/v1/private_service_enrollments/{private_service_enrollment_id} returns 400", async () => {
      const ec = errorClient(400);
      try {
        await ec.v1.private_service_enrollments.get("test-id");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(400);
      }
    });

    it("GET /api/v1/private_service_enrollments/{private_service_enrollment_id} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.private_service_enrollments.get("test-id");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("GET /api/v1/private_service_enrollments/{private_service_enrollment_id} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.private_service_enrollments.get("test-id");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/private_service_enrollments/{private_service_enrollment_id} returns 503", async () => {
      const ec = errorClient(503);
      try {
        await ec.v1.private_service_enrollments.get("test-id");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(503);
      }
    });

  });

});
