// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6f073c3e4ed9


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: solution_tags", () => {
  describe("solution_tags", () => {
    it("GET /api/v1/solution_tags returns successfully", async () => {
      const result = await client.v1.solution_tags.list();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/solution_tags returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.solution_tags.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/solution_tags returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.solution_tags.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

  });

});
