// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 835f95efba79


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: thread_messages", () => {
  describe("thread_messages", () => {
    it("DELETE /api/v1/thread_messages/{message} returns successfully", async () => {
      const result = await client.v1.thread_messages.delete("test-value");
      expect(result).toBeUndefined();
    });

    it("DELETE /api/v1/thread_messages/{message} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.thread_messages.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("DELETE /api/v1/thread_messages/{message} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.thread_messages.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("DELETE /api/v1/thread_messages/{message} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.thread_messages.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("DELETE /api/v1/thread_messages/{message} returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.thread_messages.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("PUT /api/v1/thread_messages/{message} returns successfully", async () => {
      const result = await client.v1.thread_messages.replace("test-value", { message: "test-value" });
      expect(result).toBeDefined();
    });

    it("PUT /api/v1/thread_messages/{message} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.thread_messages.replace("test-value", { message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("PUT /api/v1/thread_messages/{message} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.thread_messages.replace("test-value", { message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("PUT /api/v1/thread_messages/{message} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.thread_messages.replace("test-value", { message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("PUT /api/v1/thread_messages/{message} returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.thread_messages.replace("test-value", { message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("GET /api/v1/thread_messages/{message}/replies returns successfully", async () => {
      const result = await client.v1.thread_messages.replies("test-value");
      expect(result).toBeDefined();
    });

    it("GET /api/v1/thread_messages/{message}/replies returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.thread_messages.replies("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/thread_messages/{message}/replies returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.thread_messages.replies("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("GET /api/v1/thread_messages/{message}/replies returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.thread_messages.replies("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/thread_messages/{message}/replies returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.thread_messages.replies("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

  describe("thread_messages > reactions", () => {
    it("DELETE /api/v1/thread_messages/{message}/reactions returns successfully", async () => {
      const result = await client.v1.thread_messages.reactions.remove("test-value");
      expect(result).toBeUndefined();
    });

    it("DELETE /api/v1/thread_messages/{message}/reactions returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.thread_messages.reactions.remove("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("DELETE /api/v1/thread_messages/{message}/reactions returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.thread_messages.reactions.remove("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("DELETE /api/v1/thread_messages/{message}/reactions returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.thread_messages.reactions.remove("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("DELETE /api/v1/thread_messages/{message}/reactions returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.thread_messages.reactions.remove("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/thread_messages/{message}/reactions returns successfully", async () => {
      const result = await client.v1.thread_messages.reactions.create("test-value", { emoji: "test-value", message: "test-value" });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/thread_messages/{message}/reactions returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.thread_messages.reactions.create("test-value", { emoji: "test-value", message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/thread_messages/{message}/reactions returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.thread_messages.reactions.create("test-value", { emoji: "test-value", message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/thread_messages/{message}/reactions returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.thread_messages.reactions.create("test-value", { emoji: "test-value", message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/thread_messages/{message}/reactions returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.thread_messages.reactions.create("test-value", { emoji: "test-value", message: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

});
