// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e45a57176108


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: users", () => {
  describe("users", () => {
    it("GET /api/v1/users/me returns successfully", async () => {
      const result = await client.v1.users.me();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/users/me returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.me();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user} returns successfully", async () => {
      const result = await client.v1.users.get("test-value");
      expect(result).toBeDefined();
    });

    it("GET /api/v1/users/{user} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.get("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.get("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("GET /api/v1/users/{user}/artifacts returns successfully", async () => {
      const result = await client.v1.users.artifacts("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/artifacts returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.artifacts("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user}/artifacts returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.artifacts("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/users/{user}/invites returns successfully", async () => {
      const result = await client.v1.users.invites("test-value", { invite: {} });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/users/{user}/invites returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.invites("test-value", { invite: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/users/{user}/invites returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.invites("test-value", { invite: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/users/{user}/invites returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.users.invites("test-value", { invite: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/users/{user}/invites returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.users.invites("test-value", { invite: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

    it("POST /api/v1/users/{user}/invites returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.invites("test-value", { invite: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("GET /api/v1/users/{user}/orgs returns successfully", async () => {
      const result = await client.v1.users.orgs("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/orgs returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.orgs("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("PUT /api/v1/users/{user}/profile returns successfully", async () => {
      const result = await client.v1.users.profile("test-value", {});
      expect(result).toBeDefined();
    });

    it("PUT /api/v1/users/{user}/profile returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.profile("test-value", {});
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("PUT /api/v1/users/{user}/profile returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.profile("test-value", {});
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

  describe("users > tasks", () => {
    it("GET /api/v1/users/{user}/tasks returns successfully", async () => {
      const result = await client.v1.users.tasks.list("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/tasks returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tasks.list("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user}/tasks returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.users.tasks.list("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/users/{user}/tasks returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.tasks.list("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/users/{user}/tasks returns successfully", async () => {
      const result = await client.v1.users.tasks.create("test-value", { task: { name: "test-name" } });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/users/{user}/tasks returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tasks.create("test-value", { task: { name: "test-name" } });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/users/{user}/tasks returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.users.tasks.create("test-value", { task: { name: "test-name" } });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/users/{user}/tasks returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.tasks.create("test-value", { task: { name: "test-name" } });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("GET /api/v1/users/{user}/tasks/blocker_cycles returns successfully", async () => {
      const result = await client.v1.users.tasks.blockerCycles("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/tasks/blocker_cycles returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tasks.blockerCycles("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user}/tasks/blocker_cycles returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.users.tasks.blockerCycles("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/users/{user}/tasks/blocker_cycles returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.tasks.blockerCycles("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("GET /api/v1/users/{user}/tasks/ready returns successfully", async () => {
      const result = await client.v1.users.tasks.ready("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/tasks/ready returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tasks.ready("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user}/tasks/ready returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.users.tasks.ready("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/users/{user}/tasks/ready returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.tasks.ready("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("GET /api/v1/users/{user}/tasks/search returns successfully", async () => {
      const result = await client.v1.users.tasks.search("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/tasks/search returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tasks.search("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user}/tasks/search returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.users.tasks.search("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/users/{user}/tasks/search returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.tasks.search("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

  describe("users > threads", () => {
    it("GET /api/v1/users/{user}/threads returns successfully", async () => {
      const result = await client.v1.users.threads.list("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/threads returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.threads.list("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user}/threads returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.threads.list("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/users/{user}/threads returns successfully", async () => {
      const result = await client.v1.users.threads.create("test-value", { thread: {} });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/users/{user}/threads returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.threads.create("test-value", { thread: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/users/{user}/threads returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.threads.create("test-value", { thread: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/users/{user}/threads returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.threads.create("test-value", { thread: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

  describe("users > tokens", () => {
    it("GET /api/v1/users/{user}/tokens returns successfully", async () => {
      const result = await client.v1.users.tokens.list("test-value");
      expect(result).toBeDefined();
      expect(result).toHaveProperty("data");
      expect(Array.isArray((result as any).data)).toBe(true);
    });

    it("GET /api/v1/users/{user}/tokens returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tokens.list("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/users/{user}/tokens returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.tokens.list("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/users/{user}/tokens returns successfully", async () => {
      const result = await client.v1.users.tokens.create("test-value", {});
      expect(result).toBeDefined();
    });

    it("POST /api/v1/users/{user}/tokens returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tokens.create("test-value", {});
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/users/{user}/tokens returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.tokens.create("test-value", {});
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/users/{user}/tokens returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.users.tokens.create("test-value", {});
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/users/{user}/tokens returns 429", async () => {
      const ec = errorClient(429);
      try {
        await ec.v1.users.tokens.create("test-value", {});
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(429);
      }
    });

    it("DELETE /api/v1/users/{user}/tokens/{token} returns successfully", async () => {
      const result = await client.v1.users.tokens.delete("test-value", "test-token");
      expect(result).toBeDefined();
    });

    it("DELETE /api/v1/users/{user}/tokens/{token} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.users.tokens.delete("test-value", "test-token");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("DELETE /api/v1/users/{user}/tokens/{token} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.users.tokens.delete("test-value", "test-token");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("DELETE /api/v1/users/{user}/tokens/{token} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.users.tokens.delete("test-value", "test-token");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

  });

});
