// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 65ac7f8838ed


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: work_items", () => {
  describe("work_items", () => {
    it("GET /api/v1/work_items returns successfully", async () => {
      const result = await client.v1.work_items.list();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/work_items returns 400", async () => {
      const ec = errorClient(400);
      try {
        await ec.v1.work_items.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(400);
      }
    });

    it("GET /api/v1/work_items returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.work_items.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/work_items returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.work_items.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("GET /api/v1/work_items returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.work_items.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/work_items returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.work_items.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/work_items/{work_item}/fail returns successfully", async () => {
      const result = await client.v1.work_items.fail("test-value", { error: {}, lease_owner: "test-value" });
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/work_items/{work_item}/fail returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.work_items.fail("test-value", { error: {}, lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/work_items/{work_item}/fail returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.work_items.fail("test-value", { error: {}, lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/work_items/{work_item}/fail returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.work_items.fail("test-value", { error: {}, lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/work_items/{work_item}/fail returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.work_items.fail("test-value", { error: {}, lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

    it("POST /api/v1/work_items/{work_item}/fail returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.work_items.fail("test-value", { error: {}, lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/work_items/{work_item}/heartbeat returns successfully", async () => {
      const result = await client.v1.work_items.heartbeat("test-value", { lease_owner: "test-value" });
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/work_items/{work_item}/heartbeat returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.work_items.heartbeat("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/work_items/{work_item}/heartbeat returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.work_items.heartbeat("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/work_items/{work_item}/heartbeat returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.work_items.heartbeat("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/work_items/{work_item}/heartbeat returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.work_items.heartbeat("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

    it("POST /api/v1/work_items/{work_item}/heartbeat returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.work_items.heartbeat("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/work_items/{work_item}/start returns successfully", async () => {
      const result = await client.v1.work_items.start("test-value", { lease_owner: "test-value" });
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/work_items/{work_item}/start returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.work_items.start("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/work_items/{work_item}/start returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.work_items.start("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/work_items/{work_item}/start returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.work_items.start("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/work_items/{work_item}/start returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.work_items.start("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

    it("POST /api/v1/work_items/{work_item}/start returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.work_items.start("test-value", { lease_owner: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("POST /api/v1/work_items/{work_item}/submit returns successfully", async () => {
      const result = await client.v1.work_items.submit("test-value", { lease_owner: "test-value", result: {} });
      expect(result).toBeUndefined();
    });

    it("POST /api/v1/work_items/{work_item}/submit returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.work_items.submit("test-value", { lease_owner: "test-value", result: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/work_items/{work_item}/submit returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.work_items.submit("test-value", { lease_owner: "test-value", result: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/work_items/{work_item}/submit returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.work_items.submit("test-value", { lease_owner: "test-value", result: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/work_items/{work_item}/submit returns 409", async () => {
      const ec = errorClient(409);
      try {
        await ec.v1.work_items.submit("test-value", { lease_owner: "test-value", result: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(409);
      }
    });

    it("POST /api/v1/work_items/{work_item}/submit returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.work_items.submit("test-value", { lease_owner: "test-value", result: {} });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

});
