// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6c1669773e61

import { HttpClient } from "../../runtime/http-client.js";
import type { AgentRoutine, AgentRoutineListResponse, AgentRoutineRun, AgentRoutineRunListResponse } from "../../types/agents.js";
import type { RoutinePreset } from "../../types/common.js";

export class RunResource {
  constructor(private http: HttpClient) {}

  async list(routine: string, params?: { status?: string; limit?: number; beforeCursor?: string; afterCursor?: string }): Promise<AgentRoutineRunListResponse> {
    return this.http.request(`/api/v1/agent_routines/${routine}/runs`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async get(routine: string, run: string): Promise<AgentRoutineRun> {
    return this.http.request(`/api/v1/agent_routines/runs/${run}`);
  }
}

export class PresetResource {
  constructor(private http: HttpClient) {}

  async list(): Promise<RoutinePreset[]> {
    return this.http.request(`/api/v1/agent_routines/presets`);
  }
}

export class AgentRoutineResource {
  readonly runs: RunResource;
  readonly presets: PresetResource;

  constructor(private http: HttpClient) {
    this.runs = new RunResource(http);
    this.presets = new PresetResource(http);
  }

  async list(params?: { agent?: string; eventType?: string }): Promise<AgentRoutineListResponse> {
    return this.http.request(`/api/v1/agent_routines`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async invoke(routine: string, input: Record<string, unknown>): Promise<AgentRoutineRun> {
    return this.http.request(`/api/v1/agent_routines/${routine}/invoke`, { method: "POST", body: input });
  }

  async activate(routine: string, input: Record<string, unknown>): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}/activate`, { method: "POST", body: input });
  }

  async pause(routine: string, input: Record<string, unknown>): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}/pause`, { method: "POST", body: input });
  }

  async delete(routine: string): Promise<void> {
    await this.http.request(`/api/v1/agent_routines/${routine}`, { method: "DELETE" });
  }

  async get(routine: string): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}`);
  }

  async update(routine: string, input: Record<string, unknown>): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}`, { method: "PATCH", body: input });
  }
}
