// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 4501c84b5f16

import { HttpClient } from "../../runtime/http-client.js";
import type { AICompletionResult, AIImageResult } from "../../types/ai.js";

export class AiChatModelResource {
  constructor(private http: HttpClient) {}

  async list(): Promise<{ data: { id: string }[] }> {
    return this.http.request(`/api/v1/ai/chat/models`);
  }
}

export class ChatResource {
  readonly models: AiChatModelResource;

  constructor(private http: HttpClient) {
    this.models = new AiChatModelResource(http);
  }

  async completions(input: Record<string, unknown>): Promise<AICompletionResult> {
    return this.http.request(`/api/v1/ai/chat/completions`, { method: "POST", body: input });
  }
}

export class ModelResource {
  constructor(private http: HttpClient) {}

  async list(): Promise<{ data: { id: string }[] }> {
    return this.http.request(`/api/v1/ai/image/models`);
  }
}

export class ImageResource {
  readonly models: ModelResource;

  constructor(private http: HttpClient) {
    this.models = new ModelResource(http);
  }

  async edits(input: Record<string, unknown>): Promise<AIImageResult> {
    return this.http.request(`/api/v1/ai/image/edits`, { method: "POST", body: input });
  }

  async generations(input: Record<string, unknown>): Promise<AIImageResult> {
    return this.http.request(`/api/v1/ai/image/generations`, { method: "POST", body: input });
  }
}

export class AiResource {
  readonly chat: ChatResource;
  readonly image: ImageResource;

  constructor(private http: HttpClient) {
    this.chat = new ChatResource(http);
    this.image = new ImageResource(http);
  }
}
