// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 12193494d133

import { HttpClient } from "../../runtime/http-client.js";

export class AiImageEditResource {
  constructor(private http: HttpClient) {}

  /** Edit an image using a text prompt and one or more source images. */
  async create(input: Record<string, unknown>): Promise<{ aspect_ratio?: string | undefined; height?: number | undefined; image_data?: string | undefined; image_size?: string | undefined; image_type?: string | undefined; image_url?: string | undefined; model: string; revised_prompt?: string | undefined; size?: string | undefined; usage?: unknown | undefined; width?: number | undefined }> {
    return this.http.request(`/api/v1/ai/image/edits`, { method: "POST", body: input });
  }
}
