// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 084cdf54e2ad

import { HttpClient } from "../../runtime/http-client.js";
import type { ValidationResult } from "../../types/common.js";
import type { Config, ConfigKindSchema } from "../../types/config.js";

export class SystemResource {
  constructor(private http: HttpClient) {}

  async list(params?: { kind?: string }): Promise<{ data: { created_at?: string | undefined; current_version?: { change_description?: string | undefined; created_at?: string | undefined; data?: Record<string, unknown> | undefined; id: string; org?: string | undefined; sandbox?: string | undefined; version_number: number } | undefined; id: string; is_archived?: boolean | undefined; kind: string; lookup_key?: string | undefined; mime_type?: string | undefined; org?: string | undefined; raw_content?: string | undefined; sandbox?: string | undefined; team?: string | undefined; updated_at?: string | undefined; user?: string | undefined; virtual_path?: string | undefined }[] }> {
    return this.http.request(`/api/v1/config/system`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async clone(system: string, input: Record<string, unknown>): Promise<Config> {
    return this.http.request(`/api/v1/config/system/${system}/clone`, { method: "POST", body: input });
  }

  async get(system: string): Promise<Config> {
    return this.http.request(`/api/v1/config/system/${system}`);
  }
}

export class KindResource {
  constructor(private http: HttpClient) {}

  async list(params?: { kind?: string[] }): Promise<{ data: { classification: string; description?: string | undefined; kind: string; sample_available: boolean; schema_available: boolean }[] }> {
    return this.http.request(`/api/v1/config/kinds`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async schema(kind: string): Promise<ConfigKindSchema> {
    return this.http.request(`/api/v1/config/kinds/${kind}/schema`);
  }
}

export class ConfigResource {
  readonly system: SystemResource;
  readonly kinds: KindResource;

  constructor(private http: HttpClient) {
    this.system = new SystemResource(http);
    this.kinds = new KindResource(http);
  }

  async delete(config: string): Promise<void> {
    await this.http.request(`/api/v1/config/${config}`, { method: "DELETE" });
  }

  async get(config: string, params?: { team?: string; user?: string }): Promise<Config> {
    return this.http.request(`/api/v1/config/${config}`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async replace(config: string, input: Record<string, unknown>): Promise<Config> {
    return this.http.request(`/api/v1/config/${config}`, { method: "PUT", body: input });
  }

  async validate(input: Record<string, unknown>): Promise<ValidationResult> {
    return this.http.request(`/api/v1/config/validate`, { method: "POST", body: input });
  }

  async list(params?: { team?: string; user?: string; kind?: string }): Promise<{ data: { created_at?: string | undefined; current_version?: { change_description?: string | undefined; created_at?: string | undefined; data?: Record<string, unknown> | undefined; id: string; org?: string | undefined; sandbox?: string | undefined; version_number: number } | undefined; id: string; is_archived?: boolean | undefined; kind: string; lookup_key?: string | undefined; mime_type?: string | undefined; org?: string | undefined; raw_content?: string | undefined; sandbox?: string | undefined; team?: string | undefined; updated_at?: string | undefined; user?: string | undefined; virtual_path?: string | undefined }[] }> {
    return this.http.request(`/api/v1/config`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async create(input: Record<string, unknown>): Promise<Config> {
    return this.http.request(`/api/v1/config`, { method: "POST", body: input });
  }

  async unarchive(config: string, input: Record<string, unknown>): Promise<Config> {
    return this.http.request(`/api/v1/config/${config}/unarchive`, { method: "POST", body: input });
  }

  async archive(config: string, input: Record<string, unknown>): Promise<Config> {
    return this.http.request(`/api/v1/config/${config}/archive`, { method: "POST", body: input });
  }

  async versions(config: string, params?: { team?: string; user?: string }): Promise<{ versions: { change_description?: string | undefined; created_at?: string | undefined; data?: Record<string, unknown> | undefined; id: string; org?: string | undefined; sandbox?: string | undefined; version_number: number }[] }> {
    return this.http.request(`/api/v1/config/${config}/versions`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async encryptSecret(input: Record<string, unknown>): Promise<{ encrypted_value: string }> {
    return this.http.request(`/api/v1/config/encrypt_secret`, { method: "POST", body: input });
  }

  async content(config: string, params?: { team?: string; user?: string; format?: string }): Promise<Record<string, unknown>> {
    return this.http.request(`/api/v1/config/${config}/content`, { query: params as Record<string, string | number | boolean | undefined> });
  }
}
