// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e8c381b4b301

import { HttpClient } from "../../runtime/http-client.js";
import type { CustomObject } from "../../types/common.js";

export class CustomObjectResource {
  constructor(private http: HttpClient) {}

  async delete(object: string): Promise<void> {
    await this.http.request(`/api/v1/custom_objects/${object}`, { method: "DELETE" });
  }

  async get(object: string, params?: { type?: string }): Promise<CustomObject> {
    return this.http.request(`/api/v1/custom_objects/${object}`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async replace(object: string, input: Record<string, unknown>): Promise<{ data: { created_at?: string | undefined; fields?: unknown | undefined; id: string; org?: string | undefined; row_key?: string | undefined; sandbox?: string | undefined; schema_type?: string | undefined; team?: string | undefined; updated_at?: string | undefined; user?: string | undefined; version?: number | undefined }; meta?: unknown | undefined }> {
    return this.http.request(`/api/v1/custom_objects/${object}`, { method: "PUT", body: input });
  }
}
