// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 513cb233f959

import { HttpClient } from "../../runtime/http-client.js";

export class AiChatModelResource {
  constructor(private http: HttpClient) {}

  /** List available AI models. */
  async list(): Promise<{ data: { id: string }[] }> {
    return this.http.request(`/api/v1/ai/chat/models`);
  }
}
