// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 4200133bb994

import type { Channel } from "../phx_channel/channel.js";
import type { Socket } from "../phx_channel/socket.js";

/**
 * Phoenix channel for real-time activity feed updates.
 * Clients join a topic scoped to an agent or org and receive
 * `new_entry` events as feed entries are created.
 * ## Topics
 * * `"api:activity_feed:agent:{agent_user_id}"` — entries for a specific agent
 * * `"api:activity_feed:org:{org_id}"` — entries for an entire org/tenant
 */
export class ApiActivityFeedChannel {
  constructor(private channel: Channel, public readonly joinResponse?: unknown) {}

  /** Join an agent-scoped activity feed */
  static topicAgent(agentId: string): string {
    return `api:activity_feed:agent:${agentId}`;
  }

  /** Join an agent-scoped activity feed */
  static async joinAgent(socket: Socket, agentId: string): Promise<ApiActivityFeedChannel> {
    const topic = ApiActivityFeedChannel.topicAgent(agentId);
    const channel = socket.channel(topic);
    const joinResponse = await channel.join();
    return new ApiActivityFeedChannel(channel, joinResponse);
  }

  /** Join an org-scoped activity feed */
  static topicOrg(orgId: string): string {
    return `api:activity_feed:org:${orgId}`;
  }

  /** Join an org-scoped activity feed */
  static async joinOrg(socket: Socket, orgId: string): Promise<ApiActivityFeedChannel> {
    const topic = ApiActivityFeedChannel.topicOrg(orgId);
    const channel = socket.channel(topic);
    const joinResponse = await channel.join();
    return new ApiActivityFeedChannel(channel, joinResponse);
  }

  /** Leave the underlying channel. */
  async leave(): Promise<void> {
    await this.channel.leave();
  }

  /** List activity feed entries with cursor-based pagination */
  async listEntries(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("list_entries", payload);
  }

  onNewEntry(callback: (payload: unknown) => void): () => void {
    return this.channel.on("new_entry", callback);
  }
}
