// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 18db596860cc

import type { Channel } from "../phx_channel/channel.js";
import type { Socket } from "../phx_channel/socket.js";

/**
 * Channel for real-time custom object collaboration.
 * Clients join `api:object:{object_id}` to receive the current object state
 * and subscribe to field-level updates. Mutations are sent as key:value maps.
 */
export class ApiObjectChannel {
  constructor(private channel: Channel, public readonly joinResponse?: unknown) {}

  static topicById(objectId: string): string {
    return `api:object:${objectId}`;
  }

  static async joinById(socket: Socket, objectId: string, payload?: { connection_id?: string; partial_updates?: boolean }): Promise<ApiObjectChannel> {
    const topic = ApiObjectChannel.topicById(objectId);
    const channel = socket.channel(topic);
    const joinResponse = await channel.join(payload);
    return new ApiObjectChannel(channel, joinResponse);
  }

  static topicByRowKey(schemaType: string, rowKey: string): string {
    return `api:object:${schemaType}:${rowKey}`;
  }

  static async joinByRowKey(socket: Socket, schemaType: string, rowKey: string, payload?: { connection_id?: string; partial_updates?: boolean }): Promise<ApiObjectChannel> {
    const topic = ApiObjectChannel.topicByRowKey(schemaType, rowKey);
    const channel = socket.channel(topic);
    const joinResponse = await channel.join(payload);
    return new ApiObjectChannel(channel, joinResponse);
  }

  /** Leave the underlying channel. */
  async leave(): Promise<void> {
    await this.channel.leave();
  }

  async updateFields(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("update_fields", payload);
  }

  async save(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("save", payload);
  }

  async presenceUpdate(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("presence_update", payload);
  }

  onObjectUpdated(callback: (payload: unknown) => void): () => void {
    return this.channel.on("object_updated", callback);
  }

  onObjectCreated(callback: (payload: unknown) => void): () => void {
    return this.channel.on("object_created", callback);
  }

  onObjectDeleted(callback: (payload: unknown) => void): () => void {
    return this.channel.on("object_deleted", callback);
  }

  onPresenceUpdated(callback: (payload: unknown) => void): () => void {
    return this.channel.on("presence_updated", callback);
  }

  onPresenceLeft(callback: (payload: unknown) => void): () => void {
    return this.channel.on("presence_left", callback);
  }

  onAccessRevoked(callback: (payload: unknown) => void): () => void {
    return this.channel.on("access_revoked", callback);
  }
}
