// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 91affd4ed289

import type { Channel } from "../phx_channel/channel.js";

/**
 * Channel for real-time chat messaging.
 * Supports team-scoped and user-scoped threads with keyed, transient, and direct
 * thread access patterns.
 */
export class ApiChatChannel {
  constructor(private channel: Channel) {}

  /** Join a team-scoped thread by ID */
  static topic1(teamId: string, threadId: string): string {
    return `api:chat:team:${teamId}:thread:${threadId}`;
  }

  /** Join or create a team-scoped keyed thread */
  static topic2(teamId: string, key: string): string {
    return `api:chat:team:${teamId}:key:${key}`;
  }

  /** Join a team-scoped transient (ephemeral) thread */
  static topic3(teamId: string, key: string): string {
    return `api:chat:team:${teamId}:transient:${key}`;
  }

  /** Join a user-scoped thread by ID */
  static topic4(threadId: string): string {
    return `api:chat:user:thread:${threadId}`;
  }

  /** Join or create a user-scoped keyed thread */
  static topic5(key: string): string {
    return `api:chat:user:key:${key}`;
  }

  /** Join a user-scoped transient (ephemeral) thread */
  static topic6(key: string): string {
    return `api:chat:user:transient:${key}`;
  }

  /** Fork a sub-thread from an existing message */
  async apiChatForkThread(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:fork_thread", payload);
  }

  /** Mark a thread as read up to a given message */
  async apiChatMarkThreadRead(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:mark_thread_read", payload);
  }

  /** List all messages in the current thread */
  async apiChatListMessages(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:list_messages", payload);
  }

  /** Load additional messages with cursor-based pagination */
  async apiChatLoadMoreMessages(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:load_more_messages", payload);
  }

  /** Post a new message with optional uploads and reply-to */
  async apiChatPostMessage(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:post_message", payload);
  }

  /** Post a simple text message */
  async apiChatPostSimpleMessage(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:post_simple_message", payload);
  }

  /** Edit an existing message's content */
  async apiChatEditMessage(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:edit_message", payload);
  }

  /** Delete a message */
  async apiChatDeleteMessage(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:delete_message", payload);
  }

  /** Add an emoji reaction to a message */
  async apiChatAddReaction(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:add_reaction", payload);
  }

  /** Remove an emoji reaction from a message */
  async apiChatRemoveReaction(payload: Record<string, unknown>): Promise<unknown> {
    return this.channel.push("api:chat:remove_reaction", payload);
  }

  /** Broadcast when a new message is added to a thread */
  onMessageAdded(callback: (payload: unknown) => void): () => void {
    return this.channel.on("message_added", callback);
  }

  /** Broadcast when a message is updated or removed */
  onMessageUpdated(callback: (payload: unknown) => void): () => void {
    return this.channel.on("message_updated", callback);
  }

  /** Broadcast thread-level events (agent updates, read state, unread counts) */
  onThreadEvent(callback: (payload: unknown) => void): () => void {
    return this.channel.on("thread_event", callback);
  }

  /** Broadcast system-wide events */
  onSystemEvent(callback: (payload: unknown) => void): () => void {
    return this.channel.on("system_event", callback);
  }
}
