// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 135cea30c0a0

import { HttpClient } from "../../runtime/http-client.js";
import type { AgentComputer } from "../../types/agents.js";
import type { ComputerExecResult } from "../../types/common.js";

export class AgentComputerResource {
  constructor(private http: HttpClient) {}

  async delete(computer: string): Promise<void> {
    await this.http.request(`/api/v1/agent_computers/${computer}`, { method: "DELETE" });
  }

  async get(computer: string): Promise<AgentComputer> {
    return this.http.request(`/api/v1/agent_computers/${computer}`);
  }

  async exec(computer: string, input: { command: string; dir?: string | undefined }): Promise<ComputerExecResult> {
    return this.http.request(`/api/v1/agent_computers/${computer}/exec`, { method: "POST", body: input });
  }

  async refresh(computer: string): Promise<AgentComputer> {
    return this.http.request(`/api/v1/agent_computers/${computer}/refresh`, { method: "POST" });
  }
}
