// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 773716182e3b

import { HttpClient } from "../../runtime/http-client.js";
import type { AgentSkill, AgentSkillList } from "../../types/agents.js";

export class AgentSkillResource {
  constructor(private http: HttpClient) {}

  async list(params?: { agent?: string[] }): Promise<AgentSkillList> {
    return this.http.request(`/api/v1/agent_skills`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async create(input: Record<string, unknown>): Promise<AgentSkill> {
    return this.http.request(`/api/v1/agent_skills`, { method: "POST", body: input });
  }

  async delete(agentSkill: string): Promise<void> {
    await this.http.request(`/api/v1/agent_skills/${agentSkill}`, { method: "DELETE" });
  }

  async get(agentSkill: string): Promise<AgentSkill> {
    return this.http.request(`/api/v1/agent_skills/${agentSkill}`);
  }

  async update(agentSkill: string, input: Record<string, unknown>): Promise<AgentSkill> {
    return this.http.request(`/api/v1/agent_skills/${agentSkill}`, { method: "PATCH", body: input });
  }

  async activate(agentSkill: string, input: Record<string, unknown>): Promise<AgentSkill> {
    return this.http.request(`/api/v1/agent_skills/${agentSkill}/activate`, { method: "POST", body: input });
  }

  async deactivate(agentSkill: string, input: Record<string, unknown>): Promise<AgentSkill> {
    return this.http.request(`/api/v1/agent_skills/${agentSkill}/deactivate`, { method: "POST", body: input });
  }
}
