// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: bb9b8cbc6865

import { HttpClient } from "../../runtime/http-client.js";
import type { AgentEnvVarMasked } from "../../types/common.js";

export class AgentEnvVarResource {
  constructor(private http: HttpClient) {}

  /**
   * Delete an agent environment variable
   * Permanently deletes the specified environment variable from the agent. This
   * action is irreversible; the stored value is destroyed and cannot be recovered.
   * The authenticated user must have access to the agent's parent app. Pass the
   * app scope via the `app` parameter when calling with an API key that is scoped
   * to a specific app. Returns `204 No Content` on success.
   * @param envVar - Environment variable ID (`anv_...`) of the variable to delete.
   * @returns Empty response. Returns HTTP 204 No Content on successful deletion.
   */
  async delete(envVar: string): Promise<void> {
    await this.http.request(`/api/v1/agent_env_vars/${envVar}`, { method: "DELETE" });
  }

  /**
   * Retrieve an agent environment variable
   * Returns the environment variable identified by `env_var`. The stored value
   * is always masked in the response; only the last four characters are visible.
   * There is no endpoint that returns the plaintext value after creation.
   * The authenticated user must have access to the agent's parent app. Pass the
   * app scope via the `app` parameter when calling with an API key that is scoped
   * to a specific app.
   * @param envVar - Environment variable ID (`anv_...`) to retrieve.
   * @returns The requested environment variable with its value masked.
   */
  async get(envVar: string): Promise<AgentEnvVarMasked> {
    return this.http.request(`/api/v1/agent_env_vars/${envVar}`);
  }

  /**
   * Update an agent environment variable
   * Updates the `value` or `description` of an existing environment variable.
   * Only fields provided in the request are changed; omitted fields retain their
   * current values. The variable `key` cannot be changed after creation.
   * The updated value is stored securely and, like creation, the plaintext is
   * never returned; the response contains the masked representation. The
   * authenticated user must have access to the agent's parent app. Pass the app
   * scope via the `app` parameter when calling with an API key that is scoped to
   * a specific app.
   * @param envVar - Environment variable ID (`anv_...`) to update.
   * @param input - Request body.
   * @param input.description - Updated human-readable note describing what the variable is used for.
   * @param input.value - New plaintext secret value. The value is encrypted at rest and never returned in full.
   * @returns The updated environment variable with its value masked.
   */
  async update(envVar: string, input: { description?: string | undefined; value?: string | undefined }): Promise<AgentEnvVarMasked> {
    return this.http.request(`/api/v1/agent_env_vars/${envVar}`, { method: "PATCH", body: input });
  }
}
