// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 9ed975d5b9d9

import { HttpClient } from "../../runtime/http-client.js";
import type { AgentRoutine, AgentRoutineListResponse, AgentRoutineRun, AgentRoutineRunListResponse, RoutinePreset } from "../../types/common.js";

export class AgentRoutineRunResource {
  constructor(private http: HttpClient) {}

  /**
   * Retrieve a routine run
   * Returns a single routine run by its ID. The run includes status, payload,
   * result, duration, and any structured response produced by the routine's agent.
   * The authenticated principal must have access to the app that owns the run.
   * When your API key is scoped to an app, the run must belong to that app or
   * a 403 is returned.
   * @param run - Routine run ID (`arr_...`) to retrieve.
   * @returns The requested routine run.
   */
  async get(run: string): Promise<AgentRoutineRun> {
    return this.http.request(`/api/v1/agent_routines/runs/${run}`);
  }
}

export class AgentRoutineResource {
  readonly agent_routine_runs: AgentRoutineRunResource;

  constructor(private http: HttpClient) {
    this.agent_routine_runs = new AgentRoutineRunResource(http);
  }

  /**
   * List routines
   * Returns all routines within the authenticated app scope. Optionally filter by
   * agent or event type. When `agent` is omitted, all routines accessible to the
   * caller are returned regardless of which agent they belong to.
   * If `agent` is provided but does not exist or is not accessible, the endpoint
   * returns 404 rather than an empty list. Results are not paginated; all matching
   * routines are returned in a single response. Requires app scope.
   * @param params - Query parameters.
   * @param params.agent - Agent ID (`agt_...`) to filter routines by. Omit to return routines across all agents.
   * @param params.eventType - Event type string to filter by (e.g. `"agentroutine.invoked"`). Omit to return routines for all event types.
   * @returns Object containing a `data` array of matching routines.
   */
  async list(params?: { agent?: string; eventType?: string }): Promise<AgentRoutineListResponse> {
    return this.http.request(`/api/v1/agent_routines`, { query: params as Record<string, string | number | boolean | Array<string | number | boolean> | undefined> });
  }

  /**
   * List routine presets
   * Returns all registered routine presets available to the authenticated app,
   * including each preset's name, display metadata, and accepted configuration
   * schema. Use this endpoint to discover which presets can be referenced when
   * creating or updating a routine with `handler_type: "preset"`.
   * The list reflects presets registered at server start time and does not change
   * at runtime. Requires app scope.
   * @returns Array of available routine preset objects.
   */
  async presets(): Promise<RoutinePreset[]> {
    return this.http.request(`/api/v1/agent_routines/presets`);
  }

  /**
   * Delete a routine
   * Permanently deletes the specified routine. This action is irreversible — the
   * routine and its configuration are removed immediately. Any in-flight event
   * processing initiated by this routine before deletion may still complete.
   * Requires app scope. Returns 204 No Content on success.
   * @param routine - Routine ID (`arn_...`) of the routine to delete.
   * @returns Empty response on successful deletion (HTTP 204 No Content).
   */
  async delete(routine: string): Promise<void> {
    await this.http.request(`/api/v1/agent_routines/${routine}`, { method: "DELETE" });
  }

  /**
   * Retrieve a routine
   * Returns the full routine record for the given routine ID. Use this endpoint to
   * inspect a routine's current configuration, handler type, event config, schedule,
   * and lifecycle status.
   * Requires app scope. Returns 404 if the routine does not exist or is not
   * accessible to the caller.
   * @param routine - Routine ID (`arn_...`) of the routine to retrieve.
   * @returns The requested routine.
   */
  async get(routine: string): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}`);
  }

  /**
   * Update a routine
   * Updates one or more fields of the specified routine. Only the fields you
   * include are changed; omitted fields retain their current values. To change the
   * execution model, supply a new `handler_type` along with its required handler
   * body field (`config`, `script`, or `preset_name`).
   * When `template` is supplied, the routine's configuration is re-resolved from
   * the template before applying any additional field overrides. The routine's
   * `status`, `lookup_key`, and agent attachment are always preserved regardless
   * of template content. Updating `steps` replaces the entire step list — send
   * the full desired list, not a partial diff. Requires app scope.
   * @param routine - Routine ID (`arn_...`) of the routine to update.
   * @param input - Request body.
   * @param input.acl - Updated access control list. Replaces the existing ACL entirely.
   * @param input.config - Workflow config ID (`cfg_...`). Used when `handler_type` is `"workflow_graph"`.
   * @param input.description - New human-readable description of what this routine does.
   * @param input.event_config - Mapping of event types to trigger configuration. Each key is an event type string; each value is an object with a `"filters"` map and an optional `"dedupe_key_path"` (a JSON path used to deduplicate events, e.g. `"$.thread.id"`).
   * @param input.event_type - Event type that triggers this routine. Deprecated — use `event_config` instead.
   * @param input.handler_type - New execution model. One of `"workflow_graph"`, `"script"`, `"preset"`, or `"chain"`.
   * @param input.lookup_key - New stable, unique key for deterministic lookup. Must be unique within the app.
   * @param input.metadata - Updated arbitrary key-value metadata. Replaces the existing metadata entirely.
   * @param input.name - New human-readable display name for the routine.
   * @param input.preset_config - Updated configuration passed to the preset at runtime.
   * @param input.preset_name - Name of the registered preset to use. Used when `handler_type` is `"preset"`.
   * @param input.schedule - New cron expression for time-triggered routines (e.g. `"0 9 * * 1"`). Must not be more frequent than once per hour.
   * @param input.script - New inline script source. Used when `handler_type` is `"script"`.
   * @param input.steps - Updated ordered list of steps for a chain handler. Required when `handler_type` is `"chain"`; must be omitted or empty otherwise. Replaces the entire existing step list — send the full desired list, not a partial diff.
   * @param input.template - AgentRoutineTemplate config ID (`cfg_...`) or lookup key. When provided, the routine's configuration is re-resolved from the template before applying other param overrides. The routine's `status`, `lookup_key`, and agent attachment are always preserved.
   * @param input.trigger_context - Updated trigger context. One of `"chat_session"` or `"event"`.
   * @returns The updated routine.
   */
  async update(routine: string, input: { acl?: { add?: { actions: string[]; principal?: string | undefined; principal_type: string }[] | undefined; grants?: { actions: string[]; principal?: string | undefined; principal_type: string }[] | undefined; remove?: { principal?: string | undefined; principal_type: string }[] | undefined } | undefined; config?: string | undefined; description?: string | undefined; event_config?: Record<string, unknown> | undefined; event_type?: string | undefined; handler_type?: string | undefined; lookup_key?: string | undefined; metadata?: Record<string, unknown> | undefined; name?: string | undefined; preset_config?: { instructions?: string | undefined; llm?: { model?: string | undefined } | undefined; session_mode?: string | undefined; session_scope?: string | undefined; structured_message_template_ids?: string[] | undefined } | undefined; preset_name?: string | undefined; schedule?: string | undefined; script?: string | undefined; steps?: { config?: string | undefined; handler_type: string; inputs?: Record<string, unknown> | undefined; name?: string | undefined; on_error?: string | undefined; output_key?: string | undefined; preset_config?: { instructions?: string | undefined; llm?: { model?: string | undefined } | undefined; session_mode?: string | undefined; session_scope?: string | undefined; structured_message_template_ids?: string[] | undefined } | undefined; preset_name?: string | undefined; script?: string | undefined }[] | undefined; template?: string | undefined; trigger_context?: string | undefined }): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}`, { method: "PATCH", body: input });
  }

  /**
   * Activate a routine
   * Sets the routine's status to `"active"`, enabling it to process events or run
   * on its configured schedule. Only routines that have a workflow config attached
   * can be activated; attempting to activate a routine with no config returns 422.
   * Scheduled routines must be configured to run no more frequently than once per
   * hour. Activation fails with 422 if the cron schedule is more frequent than
   * that limit. Requires app scope.
   * @param routine - Routine ID (`arn_...`) of the routine to activate.
   * @returns The updated routine with `status` set to `"active"`.
   */
  async activate(routine: string): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}/activate`, { method: "POST" });
  }

  /**
   * Invoke a routine
   * Triggers an on-demand invocation of the specified routine, dispatching an
   * asynchronous agent run and returning a run record immediately. The routine must
   * be active and must have `event_type` set to `"agentroutine.invoked"`.
   * The routine's `preset_config.session_mode` determines session behavior: each
   * call may create a new session (`"stateless"`) or reuse an existing one
   * (`"session"`). When `session_scope` is `"per_user"`, the `user` param is
   * required for S2S and developer callers; authenticated client callers always
   * use their own identity. When `session_scope` is `"per_key"`, `session_key`
   * is required.
   * Supply `idempotency_key` to safely retry invocations — if a completed run
   * already exists for that key a 409 Conflict is returned rather than creating
   * a duplicate run. Entitlement for LLM calls is checked at request time;
   * customers on plans that do not include this feature receive 402.
   * @param routine - Routine ID (`arn_...`) or `lookup_key` of the routine to invoke.
   * @param input - Request body.
   * @param input.idempotency_key - Unique key used to deduplicate invocations. Resubmitting the same key returns 409 if a completed run already exists.
   * @param input.message - The user message to send to the agent for this invocation.
   * @param input.metadata - Arbitrary key-value metadata attached to this invocation. Not interpreted by the platform.
   * @param input.session_key - Arbitrary key used to identify and resume a session when `session_scope` is `"per_key"`. Required in that mode.
   * @param input.thread_id - Thread ID (`thr_...`) to post the preset output into. Omit to skip thread posting.
   * @param input.user - User ID to associate with the session. For S2S and developer callers only; authenticated client callers always use their own identity.
   * @returns The agent routine run created by this invocation.
   */
  async invoke(routine: string, input: { idempotency_key?: string | undefined; message: string; metadata?: Record<string, unknown> | undefined; session_key?: string | undefined; thread_id?: string | undefined; user?: string | undefined }): Promise<AgentRoutineRun> {
    return this.http.request(`/api/v1/agent_routines/${routine}/invoke`, { method: "POST", body: input });
  }

  /**
   * Pause a routine
   * Sets the routine's status to `"paused"`, suspending event processing and
   * scheduled execution without deleting the routine or its configuration. A
   * paused routine can be resumed at any time by calling the activate endpoint.
   * Requires app scope.
   * @param routine - Routine ID (`arn_...`) of the routine to pause.
   * @returns The updated routine with `status` set to `"paused"`.
   */
  async pause(routine: string): Promise<AgentRoutine> {
    return this.http.request(`/api/v1/agent_routines/${routine}/pause`, { method: "POST" });
  }

  /**
   * List runs for a routine
   * Returns a cursor-paginated list of runs for the specified routine, ordered
   * from most recent to oldest by default. Use `before_cursor` and `after_cursor`
   * to page through results in either direction.
   * You can filter runs by status to monitor a specific lifecycle phase. The
   * authenticated principal must have access to the routine's parent app. When
   * your API key is scoped to an app, only runs belonging to that app are
   * returned.
   * @param routine - Routine ID (`rtn_...`) whose runs you want to list.
   * @param params - Query parameters.
   * @param params.status - Filter runs by status. One of `"pending"`, `"running"`, `"completed"`, `"failed"`, or `"skipped"`. Omit to return runs in all statuses.
   * @param params.limit - Maximum number of runs to return per page. Defaults to 50; maximum is 100.
   * @param params.beforeCursor - Opaque cursor from a previous response's `before_cursor` field. Returns the page of runs older than this cursor.
   * @param params.afterCursor - Opaque cursor from a previous response's `after_cursor` field. Returns the page of runs newer than this cursor.
   * @returns Paginated list of routine runs.
   */
  async runs(routine: string, params?: { status?: string; limit?: number; beforeCursor?: string; afterCursor?: string }): Promise<AgentRoutineRunListResponse> {
    return this.http.request(`/api/v1/agent_routines/${routine}/runs`, { query: params as Record<string, string | number | boolean | Array<string | number | boolean> | undefined> });
  }
}
