// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: f8c1f1ea281c

import { HttpClient } from "../../runtime/http-client.js";
import type { AgentTool, AgentToolListResponse } from "../../types/agents.js";
import type { BuiltinToolCatalogEntry } from "../../types/common.js";

export class AgentToolResource {
  constructor(private http: HttpClient) {}

  async list(params?: { agent?: string; kind?: string }): Promise<AgentToolListResponse> {
    return this.http.request(`/api/v1/agent_tools`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async catalog(): Promise<BuiltinToolCatalogEntry[]> {
    return this.http.request(`/api/v1/agent_tools/catalog`);
  }

  async delete(tool: string): Promise<void> {
    await this.http.request(`/api/v1/agent_tools/${tool}`, { method: "DELETE" });
  }

  async get(tool: string): Promise<AgentTool> {
    return this.http.request(`/api/v1/agent_tools/${tool}`);
  }

  async update(tool: string, input: Record<string, unknown>): Promise<AgentTool> {
    return this.http.request(`/api/v1/agent_tools/${tool}`, { method: "PATCH", body: input });
  }

  async activate(tool: string, input: Record<string, unknown>): Promise<AgentTool> {
    return this.http.request(`/api/v1/agent_tools/${tool}/activate`, { method: "POST", body: input });
  }

  async deactivate(tool: string, input: Record<string, unknown>): Promise<AgentTool> {
    return this.http.request(`/api/v1/agent_tools/${tool}/deactivate`, { method: "POST", body: input });
  }
}
