// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 7e929808992d

import { HttpClient } from "../../runtime/http-client.js";
import type { AICompletionResult, AIImageResult } from "../../types/ai.js";

export class ChatResource {
  constructor(private http: HttpClient) {}

  /**
   * Create a chat completion
   * Sends a list of messages to the configured AI provider and returns a single
   * completion. Use this endpoint when you want direct, low-level access to the
   * underlying model without any workflow or agent orchestration.
   * The authenticated app must have the `llm_calls` entitlement enabled on its
   * plan. Requests that exceed the plan quota are rejected with `402`. Token
   * usage is recorded against the authenticated app and organization.
   * Supply `tools` and `tool_choice` to enable OpenAI-compatible function
   * calling. Use `server_tools` to activate platform-managed tools such as
   * search that run on the server side before the response is returned.
   * @param input - Request body.
   * @param input.context - Key-value map used to resolve template variables in message content. Omit if messages contain no templates.
   * @param input.messages - Ordered list of conversation messages to send to the model.
   * @param input.opts - Model and sampling configuration for this request.
   * @returns The completed AI response, including the generated message, finish reason, and token usage.
   */
  async completions(input: { context?: Record<string, unknown> | undefined; messages: { content?: string | undefined; content_parts?: Record<string, unknown>[] | undefined; resume_token?: string | undefined; role: string; structured_output?: unknown | undefined; tool_calls?: { arguments: Record<string, unknown>; id: string; name: string; thought_signature?: string | undefined }[] | undefined; tool_results?: { content?: string | undefined; id: string; name: string; resolution?: unknown | undefined }[] | undefined }[]; opts: { max_tokens?: number | undefined; model: string; server_tools?: Record<string, unknown>[] | undefined; temperature?: number | undefined; tool_choice?: string | undefined; tools?: { function: { description?: string | undefined; name: string; parameters: Record<string, unknown> }; type: string }[] | undefined } }): Promise<AICompletionResult> {
    return this.http.request(`/api/v1/ai/chat/completions`, { method: "POST", body: input });
  }

  /**
   * List available AI models
   * Returns the set of AI models that can be used with the chat completion and
   * workflow endpoints. The list reflects models currently enabled for the
   * platform and includes each model's identifier and whether it is the default.
   * Use the `model` field from any entry in `data` as the value for
   * `opts.model` when calling the completions or workflows endpoint.
   * @returns Successful response
   */
  async models(): Promise<{ data: { default: boolean; id: string; name: string }[] }> {
    return this.http.request(`/api/v1/ai/chat/models`);
  }
}

export class ImageResource {
  constructor(private http: HttpClient) {}

  /**
   * Edit an image with a text prompt
   * Applies a text-guided edit to one or more source images and returns the
   * resulting image. Pass the source images as base64-encoded objects in the
   * `images` array alongside a `prompt` describing the desired modification.
   * The underlying provider is selected by the `model` parameter. Omit `model`
   * to use the platform default. Size, quality, style, and format options are
   * forwarded to the provider as-is; unsupported combinations for a given model
   * return a 422 error with the provider's error message.
   * This endpoint requires authentication. The request is billed against the
   * workspace associated with the authenticated user.
   * @param input - Request body.
   * @param input.aspect_ratio - Desired aspect ratio of the output, e.g. `"1:1"` or `"16:9"`. Not supported by all models; omit to use the model's default.
   * @param input.background - Background treatment for the output. Accepted values and behavior are model-dependent.
   * @param input.height - Explicit output height in pixels. Takes precedence over `size` when both are provided. Not supported by all models.
   * @param input.image_size - Output resolution tier for Gemini models, e.g. `"1K"`, `"2K"`, or `"4K"`. Ignored by non-Gemini models.
   * @param input.images - One or more source images to edit. Each image must be supplied as a base64-encoded object.
   * @param input.model - Model identifier to use for editing. Omit to use the platform default image model.
   * @param input.output_format - Desired MIME type or format for the returned image. Common values: `"png"`, `"jpeg"`, `"webp"`. Defaults to the model's native format.
   * @param input.prompt - Natural-language description of the edit to apply to the source image(s).
   * @param input.quality - Quality preset for the output image. Accepted values and behavior are model-dependent.
   * @param input.size - Output dimensions as a WxH string, e.g. `"1024x1024"`. Applies to OpenAI-compatible models. Omit to use the model's default.
   * @param input.style - Style preset applied to the edit. Accepted values and behavior are model-dependent.
   * @param input.width - Explicit output width in pixels. Takes precedence over `size` when both are provided. Not supported by all models.
   * @returns The resulting edited image, including base64 data or a URL depending on the model.
   */
  async edits(input: { aspect_ratio?: string | undefined; background?: string | undefined; height?: number | undefined; image_size?: string | undefined; images: { image_data: string; image_type: string }[]; model?: string | undefined; output_format?: string | undefined; prompt: string; quality?: string | undefined; size?: string | undefined; style?: string | undefined; width?: number | undefined }): Promise<AIImageResult> {
    return this.http.request(`/api/v1/ai/image/edits`, { method: "POST", body: input });
  }

  /**
   * Generate an image from a text prompt
   * Generates one or more images from a natural-language `prompt` using the
   * specified AI image model. The response contains the first generated image;
   * use `n` to request additional images (where supported by the model).
   * The underlying provider is selected by the `model` parameter. Omit `model`
   * to use the platform default. Size, quality, style, and format options are
   * forwarded to the provider as-is; unsupported combinations for a given model
   * return a 422 error with the provider's error message.
   * This endpoint requires authentication. The request is billed against the
   * workspace associated with the authenticated user.
   * @param input - Request body.
   * @param input.aspect_ratio - Desired aspect ratio of the output, e.g. `"1:1"` or `"16:9"`. Not supported by all models; omit to use the model's default.
   * @param input.background - Background treatment for the output. Accepted values and behavior are model-dependent.
   * @param input.height - Explicit output height in pixels. Takes precedence over `size` when both are provided. Not supported by all models.
   * @param input.image_size - Output resolution tier for Gemini models, e.g. `"1K"`, `"2K"`, or `"4K"`. Ignored by non-Gemini models.
   * @param input.model - Model identifier to use for generation. Omit to use the platform default image model.
   * @param input.n - Number of images to generate. Defaults to `1`. Values greater than `1` are only supported by models that allow batch generation.
   * @param input.output_format - Desired MIME type or format for the returned image. Common values: `"png"`, `"jpeg"`, `"webp"`. Defaults to the model's native format.
   * @param input.prompt - Natural-language description of the image to generate.
   * @param input.quality - Quality preset for the output image. Accepted values and behavior are model-dependent.
   * @param input.size - Output dimensions as a WxH string, e.g. `"1024x1024"`. Applies to OpenAI-compatible models. Omit to use the model's default.
   * @param input.style - Style preset applied to the generated image. Accepted values and behavior are model-dependent.
   * @param input.width - Explicit output width in pixels. Takes precedence over `size` when both are provided. Not supported by all models.
   * @returns The generated image, including base64 data or a URL depending on the model.
   */
  async generations(input: { aspect_ratio?: string | undefined; background?: string | undefined; height?: number | undefined; image_size?: string | undefined; model?: string | undefined; n?: number | undefined; output_format?: string | undefined; prompt: string; quality?: string | undefined; size?: string | undefined; style?: string | undefined; width?: number | undefined }): Promise<AIImageResult> {
    return this.http.request(`/api/v1/ai/image/generations`, { method: "POST", body: input });
  }

  /**
   * List available image generation models
   * Returns the list of image generation models available on the platform.
   * Exactly one entry in the list carries `default: true`, indicating the model
   * used when no `model` parameter is supplied to the generation or editing
   * endpoints.
   * This endpoint requires authentication and reflects the models enabled for
   * the authenticated user's workspace.
   * @returns Successful response
   */
  async models(): Promise<{ data: { default: boolean; id: string; name: string }[] }> {
    return this.http.request(`/api/v1/ai/image/models`);
  }
}

export class AiResource {
  readonly chat: ChatResource;
  readonly image: ImageResource;

  constructor(private http: HttpClient) {
    this.chat = new ChatResource(http);
    this.image = new ImageResource(http);
  }
}
