// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 628e7ca6d9b8

import { HttpClient } from "../../runtime/http-client.js";
import type { Artifact } from "../../types/artifacts.js";

export class ArtifactResource {
  constructor(private http: HttpClient) {}

  async delete(artifact: string): Promise<void> {
    await this.http.request(`/api/v1/artifacts/${artifact}`, { method: "DELETE" });
  }

  async get(artifact: string): Promise<Artifact> {
    return this.http.request(`/api/v1/artifacts/${artifact}`);
  }

  async replace(artifact: string, input: Record<string, unknown>): Promise<Artifact> {
    return this.http.request(`/api/v1/artifacts/${artifact}`, { method: "PUT", body: input });
  }

  async archive(artifact: string): Promise<void> {
    await this.http.request(`/api/v1/artifacts/${artifact}/archive`, { method: "POST" });
  }

  async content(artifact: string, params?: { version?: number }): Promise<{ content: ArrayBuffer; mimeType: string }> {
    return this.http.requestRaw(`/api/v1/artifacts/${artifact}/content`, { query: params as Record<string, string | number | boolean | undefined> });
  }
}
