// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 338b48a6c451

import { HttpClient } from "../../runtime/http-client.js";
import type { Artifact } from "../../types/artifacts.js";

export class ArtifactResource {
  constructor(private http: HttpClient) {}

  /**
   * Delete an artifact
   * Permanently deletes the artifact and all associated file versions. This
   * operation is irreversible — deleted artifacts and their file content cannot
   * be recovered.
   * The authenticated user must have write access to the artifact's owning team
   * or organization. Returns 404 if the artifact does not exist or is not
   * accessible to the caller.
   * @param artifact - Artifact ID (`art_...`) of the artifact to delete.
   * @returns Empty body. HTTP 204 indicates the artifact and all associated file versions were permanently deleted.
   */
  async delete(artifact: string): Promise<void> {
    await this.http.request(`/api/v1/artifacts/${artifact}`, { method: "DELETE" });
  }

  /**
   * Retrieve an artifact
   * Returns the artifact identified by `artifact`. The response includes metadata
   * such as name, description, version, and a signed `file_url` for downloading
   * the current file version. Image artifacts also include an `image_source` object
   * with display-ready metadata.
   * The authenticated user must have read access to the artifact's owning team or
   * organization. Returns 404 if the artifact does not exist or is not accessible
   * to the caller.
   * @param artifact - Artifact ID (`art_...`) of the artifact to retrieve.
   * @returns The requested artifact, including its current version's file metadata and signed download URL.
   */
  async get(artifact: string): Promise<Artifact> {
    return this.http.request(`/api/v1/artifacts/${artifact}`);
  }

  /**
   * Update an artifact
   * Updates the metadata and, optionally, the file content of an existing artifact.
   * This endpoint uses optimistic concurrency control: you must supply the artifact's
   * current `version` number as `from_version`. If another update has incremented the
   * version since you last fetched the artifact, the request returns 409.
   * To replace the artifact's file, include a nested `file` object with Base64
   * `data`, `filename`, and `mime_type`. Omitting `file` leaves the existing file
   * unchanged. The authenticated user or developer must have write access to the
   * artifact's owner.
   * @param artifact - Artifact ID (`art_...`) of the artifact to update.
   * @param input - Request body.
   * @param input.description - New description for the artifact. Omit to leave the existing description unchanged.
   * @param input.file - Replacement file payload. Omit to leave the current file unchanged.
   * @param input.file_content - Legacy flat Base64 file content. Prefer `file.data`.
   * @param input.file_content_type - Legacy flat MIME type. Prefer `file.mime_type`.
   * @param input.file_name - Legacy flat filename. Prefer `file.filename`.
   * @param input.from_version - The artifact's current version number, used for optimistic concurrency control. Returns 409 if this value does not match the server's current version.
   * @param input.name - New display name for the artifact. Omit to leave the existing name unchanged.
   * @returns The artifact after applying the update, reflecting the new version number and any changed metadata or file.
   */
  async replace(artifact: string, input: { description?: string | undefined; file?: { data: string; filename?: string | undefined; mime_type?: string | undefined } | undefined; file_content?: string | undefined; file_content_type?: string | undefined; file_name?: string | undefined; from_version: number; name?: string | undefined }): Promise<Artifact> {
    return this.http.request(`/api/v1/artifacts/${artifact}`, { method: "PUT", body: input });
  }

  /**
   * Archive an artifact
   * Soft-deletes the artifact identified by `artifact`. The artifact record is
   * retained in storage but is no longer returned by the list or show endpoints.
   * The authenticated user must have write access to the artifact's owning team or
   * organization. Attempting to archive an artifact you do not own returns 403.
   * Attempting to archive an artifact that does not exist or is already archived
   * returns 404.
   * @param artifact - Artifact ID (`art_...`) of the artifact to archive.
   * @returns Returns 204 No Content on success. The artifact is soft-deleted and no longer accessible through the API.
   */
  async archive(artifact: string): Promise<void> {
    await this.http.request(`/api/v1/artifacts/${artifact}/archive`, { method: "POST" });
  }

  /**
   * Retrieve raw artifact file content
   * Returns the raw binary content of the file stored for the specified artifact.
   * The response `Content-Type` header reflects the artifact file's MIME type, so
   * you can pipe the response body directly to disk or display it in a browser.
   * By default the endpoint serves the artifact's current version. Pass the
   * `version` parameter to retrieve a specific historical version. The authenticated
   * user must have read access to the artifact's owning team or organization.
   * @param artifact - Artifact ID (`art_...`) of the artifact whose content to retrieve.
   * @param params - Query parameters.
   * @param params.version - Version number to retrieve. Omit to return the artifact's current version.
   * @returns Raw binary content of the artifact file. The `Content-Type` header is set to the artifact's stored MIME type.
   */
  async content(artifact: string, params?: { version?: number }): Promise<{ content: ArrayBuffer; mimeType: string }> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.version !== undefined) {
      query["version"] = params?.version;
    }

    return this.http.requestRaw(`/api/v1/artifacts/${artifact}/content`, { query });
  }
}
