// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d494c552974e

import { HttpClient } from "../../runtime/http-client.js";
import type { AutomationRun } from "../../types/automations.js";

export class AutomationResource {
  constructor(private http: HttpClient) {}

  async invoke(automation: string, input: { idempotency_key?: string | undefined; payload?: Record<string, unknown> | undefined }): Promise<AutomationRun> {
    return this.http.request(`/api/v1/automations/${automation}/invoke`, { method: "POST", body: input });
  }
}
