// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 44886323d6d6

import { HttpClient } from "../../runtime/http-client.js";
import type { AutomationRun } from "../../types/automations.js";
import type { RunJournalPage } from "../../types/common.js";

export class AutomationRunResource {
  constructor(private http: HttpClient) {}

  /**
   * Retrieve an automation run
   * Returns a single automation run by ID.
   * Public v1 path: `GET /api/v1/automation_runs/:automation_run`.
   * Developer app-scoped path (legacy shape, same module):
   * `GET /protected/api/v1/developer/apps/:app/automations/runs/:automation_run`.
   * Any automation type is accepted (`trigger`, `scheduled`, or `invoked`).
   * Resolution is viewer-scoped (AppScope + OrgScope): a run the caller cannot
   * see returns 404.
   * @param automationRun - Automation run ID (`arun_...`).
   * @returns The requested automation run.
   */
  async get(automationRun: string): Promise<AutomationRun> {
    return this.http.request(`/api/v1/automation_runs/${automationRun}`);
  }

  /**
   * List an automation run journal
   * Returns durable workflow journal entries for an automation run.
   * Public v1 path: `GET /api/v1/automation_runs/:automation_run/journal`.
   * Developer app-scoped path (legacy shape, same module):
   * `GET /protected/api/v1/developer/apps/:app/automations/runs/:automation_run/journal`.
   * Any automation type is accepted. Resolution is viewer-scoped
   * (AppScope + OrgScope). An authorized run without a journal returns
   * `journal: null` and an empty `data` array with HTTP 200.
   * @param automationRun - Automation run ID (`atr_...`) whose journal to retrieve.
   * @param params - Query parameters.
   * @param params.limit - Maximum number of entries to return. Defaults to 50; maximum is 100.
   * @param params.afterCursor - Opaque cursor from the previous response's `after_cursor` field.
   * @returns Forward-paginated automation run journal entries.
   */
  async journal(automationRun: string, params?: { limit?: number; afterCursor?: string }): Promise<RunJournalPage> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.limit !== undefined) {
      query["limit"] = params?.limit;
    }
    if (params?.afterCursor !== undefined) {
      query["after_cursor"] = params?.afterCursor;
    }

    return this.http.request(`/api/v1/automation_runs/${automationRun}/journal`, { query });
  }

  /**
   * Stream automation run status
   * Opens a Server-Sent Events connection that emits a `run_update` event whenever
   * the invoked automation run's status changes, replaying the current status on
   * connect and closing on a terminal status (`completed`, `failed`, `cancelled`)
   * or after the max stream duration.
   * @param automationRun - ID of the invoked automation run.
   * @returns Server-Sent Events stream
   */
  async *stream(automationRun: string): AsyncIterable<{ event: "run_update"; data: AutomationRun }> {
    yield* this.http.streamSSE(`/api/v1/automation_runs/${automationRun}/stream`) as AsyncIterable<{ event: "run_update"; data: AutomationRun }>;
  }
}
