// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6209439abf7a

import { HttpClient } from "../../runtime/http-client.js";
import type { UserInvite } from "../../types/users.js";

export class InviteResource {
  constructor(private http: HttpClient) {}

  async accept(input: { key: string }): Promise<UserInvite> {
    return this.http.request(`/api/v1/invites/accept`, { method: "POST", body: input });
  }
}
