// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 8cc1bf8e03d4

import { HttpClient } from "../../runtime/http-client.js";
import type { KeyValueStorageEntry, KeyValueStorageEntryPage } from "../../types/common.js";

export class KvResource {
  constructor(private http: HttpClient) {}

  async list(params?: { page?: number; pageSize?: number; user?: string; userSearch?: string; key?: string }): Promise<KeyValueStorageEntryPage> {
    return this.http.request(`/api/v1/kv`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async create(input: Record<string, unknown>): Promise<KeyValueStorageEntry> {
    return this.http.request(`/api/v1/kv`, { method: "POST", body: input });
  }

  async delete(key: string): Promise<void> {
    await this.http.request(`/api/v1/kv/${key}`, { method: "DELETE" });
  }

  async get(key: string, params?: { user?: string }): Promise<KeyValueStorageEntry> {
    return this.http.request(`/api/v1/kv/${key}`, { query: params as Record<string, string | number | boolean | undefined> });
  }

  async upsert(key: string, input: Record<string, unknown>): Promise<KeyValueStorageEntry> {
    return this.http.request(`/api/v1/kv/${key}`, { method: "PUT", body: input });
  }
}
