// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e121fa00429e

import { HttpClient } from "../../runtime/http-client.js";
import type { KeyValueStorageEntry, KeyValueStorageEntryPage } from "../../types/common.js";

export class KvResource {
  constructor(private http: HttpClient) {}

  /**
   * List key-value storage entries
   * Returns key-value storage entries in one of two modes depending on the caller's
   * auth scope.
   * **User-JWT callers** receive a flat list of all their own entries with no
   * pagination fields. The `page`, `page_size`, `user`, `user_search`, and `key`
   * params are ignored.
   * **Developer and server-to-server callers** receive a page-based paginated
   * response across all users within the caller's app. Use `user` to scope results
   * to a single user, `user_search` to do a substring match on email or full name,
   * and `key` to filter entries whose key starts with the given prefix. Results are
   * ordered by creation time descending.
   * @param params - Query parameters.
   * @param params.page - Page number to retrieve. Applies to developer and server-to-server callers only. Defaults to 1.
   * @param params.pageSize - Number of entries per page. Applies to developer and server-to-server callers only. Defaults to 25; maximum is 100.
   * @param params.user - Filter results to entries belonging to this user ID. Applies to developer and server-to-server callers only.
   * @param params.userSearch - Substring match against user email address and full name. Applies to developer and server-to-server callers only.
   * @param params.key - Prefix filter on the storage key. Returns only entries whose key starts with this string. Applies to developer and server-to-server callers only.
   * @returns Key-value storage entries for the current page, with pagination metadata for developer and server-to-server callers.
   */
  async list(params?: { page?: number; pageSize?: number; user?: string; userSearch?: string; key?: string }): Promise<KeyValueStorageEntryPage> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.page !== undefined) {
      query["page"] = params?.page;
    }
    if (params?.pageSize !== undefined) {
      query["page_size"] = params?.pageSize;
    }
    if (params?.user !== undefined) {
      query["user"] = params?.user;
    }
    if (params?.userSearch !== undefined) {
      query["user_search"] = params?.userSearch;
    }
    if (params?.key !== undefined) {
      query["key"] = params?.key;
    }

    return this.http.request(`/api/v1/kv`, { query });
  }

  /**
   * Create a key-value storage entry
   * Creates a new key-value storage entry for the target user under the given key.
   * The key must not already exist for this user; use the upsert endpoint to create
   * or overwrite in a single call.
   * End-user (user-JWT) callers always write to their own storage. Developer and
   * server-to-server callers must supply a `user` param identifying the target user
   * within their app's scope. Attempting to write for a user in a different app
   * returns 404.
   * @param input - Request body.
   * @param input.key - Storage key for the entry. Must be a non-empty string unique to this user.
   * @param input.user - Target user ID. Required when calling as a developer or with a server-to-server key; ignored for end-user callers.
   * @param input.value - Value to store under `key`. Must be a non-empty string.
   * @returns The newly created key-value storage entry.
   */
  async create(input: { key: string; user?: string | undefined; value: string }): Promise<KeyValueStorageEntry> {
    return this.http.request(`/api/v1/kv`, { method: "POST", body: input });
  }

  /**
   * Delete a key-value storage entry
   * Permanently deletes the key-value storage entry identified by `key` for the
   * target user. Returns 204 No Content on success and 404 if the entry does not
   * exist.
   * End-user (user-JWT) callers can only delete entries they own. Developer and
   * server-to-server callers must supply a `user` param identifying the target user
   * within their app's scope.
   * @param key - Storage key of the entry to delete. Must be a non-empty string.
   * @returns Empty response body. HTTP 204 No Content on success.
   */
  async delete(key: string): Promise<void> {
    await this.http.request(`/api/v1/kv/${key}`, { method: "DELETE" });
  }

  /**
   * Retrieve a key-value storage entry
   * Returns the key-value storage entry identified by `key` for the target user.
   * Returns 404 if no entry exists for that key.
   * End-user (user-JWT) callers retrieve entries from their own storage. Developer
   * and server-to-server callers must supply a `user` param identifying the target
   * user within their app's scope.
   * @param key - Storage key of the entry to retrieve. Must be a non-empty string.
   * @param params - Query parameters.
   * @param params.user - Target user ID. Required when calling as a developer or with a server-to-server key; ignored for end-user callers.
   * @returns The key-value storage entry for the given key.
   */
  async get(key: string, params?: { user?: string }): Promise<KeyValueStorageEntry> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.user !== undefined) {
      query["user"] = params?.user;
    }

    return this.http.request(`/api/v1/kv/${key}`, { query });
  }

  /**
   * Create or update a key-value storage entry
   * Creates a new key-value storage entry for the given `key`, or overwrites the
   * value if an entry already exists. This is the idempotent alternative to the
   * create endpoint: safe to call regardless of whether the key already exists.
   * End-user (user-JWT) callers always write to their own storage. Developer and
   * server-to-server callers must supply a `user` param identifying the target user
   * within their app's scope. Attempting to write for a user in a different app
   * returns 404.
   * @param key - Storage key to create or overwrite. Must be a non-empty string.
   * @param input - Request body.
   * @param input.user - Target user ID. Required when calling as a developer or with a server-to-server key; ignored for end-user callers.
   * @param input.value - New value to store under `key`. Must be a non-empty string. Replaces any existing value.
   * @returns The created or updated key-value storage entry.
   */
  async upsert(key: string, input: { user?: string | undefined; value: string }): Promise<KeyValueStorageEntry> {
    return this.http.request(`/api/v1/kv/${key}`, { method: "PUT", body: input });
  }
}
