// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: bf15a607e306

import { HttpClient } from "../../runtime/http-client.js";

export class PrivateServiceDefinitionResource {
  constructor(private http: HttpClient) {}

  /**
   * Download an enrolled private service definition
   * Returns the canonical callable definition authorized by an enrollment token.
   * @returns Raw content
   */
  async get(appId: string, privateServiceId: string): Promise<string> {
    return this.http.request(`/api/v1/private_service_definitions/${appId}/${privateServiceId}`);
  }
}
