// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d0e14fba7255

import { HttpClient } from "../../runtime/http-client.js";
import type { CreatedPrivateServiceEnrollment, PrivateServiceEnrollment, PrivateServiceEnrollmentPage } from "../../types/common.js";

export class PrivateServiceEnrollmentResource {
  constructor(private http: HttpClient) {}

  /**
   * List private service enrollments
   * @param params - Query parameters.
   * @param params.org - Organization ID or slug. Required for developer and server callers.
   * @param params.page - Page number. Defaults to 1.
   * @param params.pageSize - Results per page. Defaults to 25; maximum is 100.
   * @returns Successful response
   */
  async list(params?: { org?: string; page?: number; pageSize?: number }): Promise<PrivateServiceEnrollmentPage> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.org !== undefined) {
      query["org"] = params?.org;
    }
    if (params?.page !== undefined) {
      query["page"] = params?.page;
    }
    if (params?.pageSize !== undefined) {
      query["page_size"] = params?.pageSize;
    }

    return this.http.request(`/api/v1/private_service_enrollments`, { query });
  }

  /**
   * Create a private service enrollment
   * Creates or safely replaces an unreserved one-time connector enrollment token.
   * @param input - Request body.
   * @param input.org - Organization ID or slug. Required for developer and server callers.
   * @param input.private_service - Private service ID (`pvs_...`).
   * @returns Successful response
   */
  async create(input: { org?: string | undefined; private_service: string }): Promise<CreatedPrivateServiceEnrollment> {
    return this.http.request(`/api/v1/private_service_enrollments`, { method: "POST", body: input });
  }

  /**
   * Retrieve a private service enrollment
   * @param privateServiceEnrollmentId - Canonical certificate-bound service identity.
   * @param params - Query parameters.
   * @param params.org - Organization ID or slug. Required for developer and server callers.
   * @returns Successful response
   */
  async get(privateServiceEnrollmentId: string, params?: { org?: string }): Promise<PrivateServiceEnrollment> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.org !== undefined) {
      query["org"] = params?.org;
    }

    return this.http.request(`/api/v1/private_service_enrollments/${privateServiceEnrollmentId}`, { query });
  }
}
