// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: bddc51a65c25

import { HttpClient } from "../../runtime/http-client.js";
import type { SlackChannelBinding, SlackChannelBindingListResponse, SlackDeliveryOutcomeListResponse } from "../../types/common.js";

export class SlackChannelBindingResource {
  constructor(private http: HttpClient) {}

  /**
   * List Slack channel bindings
   * Returns a page of Slack channel bindings visible to the authenticated user.
   * Results can be filtered by integration, team, agent, or organization. Omit all
   * filter params to retrieve every binding the caller can see.
   * Pagination is page-based. Pass `page` and `per_page` to navigate large result
   * sets. `page` must be a positive integer; `per_page` must be between 1 and 100.
   * Invalid values return 400.
   * @param params - Query parameters.
   * @param params.integration - Return only bindings whose Slack integration matches one of these integration IDs. Omit to return bindings across all integrations.
   * @param params.team - Return only bindings bound to one of these team IDs. Omit to return bindings for all teams.
   * @param params.agent - Return only bindings that have at least one of these agent user IDs attached. Omit to return bindings regardless of agent attachment.
   * @param params.org - Return only bindings that belong to one of these organization IDs. Omit to return bindings across all organizations visible to the caller.
   * @param params.page - Page number to retrieve, 1-indexed. Defaults to 1. Must be a positive integer.
   * @param params.perPage - Number of bindings to return per page. Defaults to 25; maximum is 100.
   * @returns Paginated list of Slack channel bindings visible to the caller.
   */
  async list(params?: { integration?: string[]; team?: string[]; agent?: string[]; org?: string[]; page?: number; perPage?: number }): Promise<SlackChannelBindingListResponse> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.integration !== undefined) {
      query["integration"] = params?.integration;
    }
    if (params?.team !== undefined) {
      query["team"] = params?.team;
    }
    if (params?.agent !== undefined) {
      query["agent"] = params?.agent;
    }
    if (params?.org !== undefined) {
      query["org"] = params?.org;
    }
    if (params?.page !== undefined) {
      query["page"] = params?.page;
    }
    if (params?.perPage !== undefined) {
      query["per_page"] = params?.perPage;
    }

    return this.http.request(`/api/v1/slack_channel_bindings`, { query });
  }

  /**
   * Create or update a Slack channel binding
   * Creates a new binding between a Slack channel and a team, or updates the
   * existing binding if one already exists for the given channel. The caller also
   * supplies a list of agents to attach to the binding and enroll as members of the
   * destination team.
   * The caller must have team-manage rights on the destination team (and on the
   * currently bound team if the channel is being re-pointed). Returns 403 if
   * permission is insufficient. All write steps are idempotent, so retrying after
   * a partial failure is safe.
   * On success the REST endpoint returns 201 Created. The script binding
   * (`slack.channel_bindings.upsert`) returns the full binding object including the
   * attached agents.
   * @param input - Request body.
   * @param input.agent_user_ids - List of agent user IDs to attach to the binding and enroll as members of the destination team. Pass an empty array to bind the channel without attaching any agents.
   * @param input.allow_bot_conversations - Opt this channel into sustained bot-to-bot conversation: the reply loop brake is disabled for its mirror thread. Set when the counterparty is a known bot the agent should keep answering. Omitting the parameter leaves the stored value unchanged.
   * @param input.channel_id - Slack channel ID to bind (e.g. `C01234ABCDE`). Acts as the natural key of the binding within the workspace.
   * @param input.customer_label - Human-readable label for the customer associated with this channel. Stored in the binding's config. `null` if omitted.
   * @param input.is_ext_shared_cached - Cached value of Slack's `is_ext_shared` flag for the channel. When provided, this value is persisted on the binding to avoid repeated Slack API lookups. `null` if omitted.
   * @param input.is_private_cached - Cached value of Slack's `is_private` flag for the channel. When provided, this value is persisted on the binding to avoid repeated Slack API lookups. Private channels are member-managed. `null` if omitted.
   * @param input.slack_team_id - Slack workspace team ID that the channel belongs to (e.g. `T01234ABCDE`). Identifies which Slack integration to use.
   * @param input.team_id - ID of the team to bind the Slack channel to. The caller must have team-manage rights on this team.
   * @returns The created or updated Slack channel binding, including the full list of currently attached agents.
   */
  async create(input: { agent_user_ids: string[]; allow_bot_conversations?: boolean | undefined; channel_id: string; customer_label?: string | undefined; is_ext_shared_cached?: boolean | undefined; is_private_cached?: boolean | undefined; slack_team_id: string; team_id: string }): Promise<SlackChannelBinding> {
    return this.http.request(`/api/v1/slack_channel_bindings`, { method: "POST", body: input });
  }

  /**
   * Start adding a customer over Slack Connect
   * Opens a Slack Connect channel with a new customer — creating one and sending
   * the invite, or adopting a shared channel you already have — and records who is
   * adding whom so the addition can finish once the customer accepts.
   * The returned binding is **pending**: nothing mirrors, and no per-customer Team,
   * agent, or solution instance exists yet. Acceptance is asynchronous and may
   * never come. When it does, the addition completes in the background under the
   * identity of the admin who called this endpoint, re-checked live at that moment.
   * A caller who has since lost their admin role does not get a substitute — the
   * addition is refused and a human re-adds the customer.
   * The caller must be an admin of the Slack integration's own organization. This
   * is the same authority the completion demands, checked here so a customer is
   * never invited into a channel whose addition can never finish.
   * Deliberately not exposed as a script binding: this sends mail to a person
   * outside the org, so it stays a vendor-admin HTTP surface.
   * @param input - Request body.
   * @param input.channel_name - Name for a Slack channel to create for this customer. Required unless `existing_channel_id` is given. The channel is created private.
   * @param input.customer_email - Address the Slack Connect invite is sent to. Required when creating a channel; optional when adopting one the customer is already in. Whoever accepts becomes the verified counterparty.
   * @param input.customer_key - The vendor's own primary key for this customer (`customer_id` / `account_id` / `tenant_id`). The per-customer agent's data access is locked to it. Immutable once the customer is added: re-targeting means offboarding and re-provisioning.
   * @param input.customer_label - Human-readable name for the customer (e.g. `Acme, Inc.`). Used for the vendor's own dashboards and as the per-customer Team's name. Not an identity or an access control input.
   * @param input.existing_channel_id - Adopt this already-shared Slack Connect channel (e.g. `C01234ABCDE`) instead of creating one. Mutually exclusive with `channel_name`.
   * @param input.inputs - String-keyed values the per-customer solution instance is stamped with. Defaults to an empty map.
   * @param input.slack_team_id - Slack workspace team ID of the vendor's own Slack installation (e.g. `T01234ABCDE`). The customer's workspace is not known yet — it resolves from whoever accepts.
   * @param input.template_config_id - Config ID (`cfg_…`) of the org-installed Solution the per-customer instance is stamped from. Must be the organization's own installed copy, not the catalog original — instances stamped from a different config do not appear in the vendor's customer fleet.
   * @returns The pending binding for the customer's channel. `disclosure_state` is `pending` until the customer accepts, and `scope_key` is null until the addition finishes.
   */
  async provision(input: { channel_name?: string | undefined; customer_email?: string | undefined; customer_key: string; customer_label: string; existing_channel_id?: string | undefined; inputs?: Record<string, unknown> | undefined; slack_team_id: string; template_config_id: string }): Promise<SlackChannelBinding> {
    return this.http.request(`/api/v1/slack_channel_bindings/provision`, { method: "POST", body: input });
  }

  /**
   * Delete a Slack channel binding
   * Removes the binding between a Slack channel and its associated team. The
   * channel is identified by its Slack channel ID together with the `slack_team_id`
   * that scopes it to a specific Slack workspace. Removing the binding does not
   * delete the bound team or any conversation threads scoped to it; decommission
   * those resources separately if required.
   * The caller must have team-manage rights on the team the channel is currently
   * bound to. Returning 403 indicates insufficient permission; returning 404
   * indicates the binding does not exist or is not visible to the caller.
   * The REST endpoint returns 204 No Content on success. The script binding
   * (`slack.channel_bindings.delete`) returns a confirmation object so script
   * callers can verify success without an additional fetch. Both paths are
   * idempotent — retrying after a partial failure is safe.
   * @param channel - Slack channel ID of the binding to delete (e.g. `C01234ABCDE`).
   * @returns Successful response
   */
  async delete(channel: string): Promise<{ channel: string; deleted: boolean }> {
    return this.http.request(`/api/v1/slack_channel_bindings/${channel}`, { method: "DELETE" });
  }

  /**
   * Retrieve a Slack channel binding
   * Returns the Slack channel binding identified by a Slack channel ID and workspace
   * team ID pair. Use this endpoint to look up the team and agents currently bound
   * to a specific Slack channel.
   * The `channel` path parameter is the Slack channel ID; `slack_team_id` identifies
   * the Slack workspace the channel belongs to, disambiguating channels with the same
   * ID across workspaces. Both parameters are required. Returns 404 if no binding
   * exists for the given pair or the associated Slack integration is not visible to
   * the caller.
   * @param channel - Slack channel ID of the binding to retrieve (e.g. `C01234ABCDE`).
   * @param params - Query parameters.
   * @param params.slackTeamId - Slack workspace team ID that the channel belongs to (e.g. `T01234ABCDE`). Used together with `channel` to uniquely identify the binding.
   * @returns The Slack channel binding for the given channel and workspace.
   */
  async get(channel: string, params?: { slackTeamId?: string }): Promise<SlackChannelBinding> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    query["slack_team_id"] = params?.slackTeamId;

    return this.http.request(`/api/v1/slack_channel_bindings/${channel}`, { query });
  }

  /**
   * List delivery outcomes for a Slack channel
   * Returns what happened to each agent message this platform sent to a Slack
   * channel, newest attempt first.
   * A message that never appears in a Slack channel has several possible causes
   * that look identical from the channel itself: a content guard withheld it, the
   * cross-org judge refused it, Slack rejected the call, or nobody asked anything.
   * This endpoint tells them apart. Use it to confirm a reply was delivered, or to
   * find out why one never arrived, without reading the channel's mirrored
   * conversation.
   * Outcomes cover **outbound agent messages only**. They carry no message
   * content, no author, and nothing about inbound messages. Access follows the
   * channel's binding — the organization and app the channel is bound to — and
   * needs no membership in the mirrored thread.
   * Paginated with opaque cursors, newest first. When `has_more` is true, pass the
   * response's `before_cursor` back as `before_cursor` to continue into older
   * history. `since` and `outcome` narrow the result set; they are filters, not
   * paging controls.
   * @param channel - Slack channel ID to read delivery outcomes for (e.g. `C01234ABCDE`).
   * @param params - Query parameters.
   * @param params.since - Only return attempts at or after this ISO 8601 timestamp (e.g. `2026-08-11T00:00:00Z`). Omit to return the most recent attempts regardless of age.
   * @param params.outcome - Return only attempts with this outcome. Omit to return every outcome. Use `floored` and `judge_refused` to see only what was withheld.
   * @param params.limit - Maximum number of outcomes to return. Defaults to 50; maximum is 200.
   * @param params.beforeCursor - Opaque cursor from a previous response; returns outcomes older than it. Cursors are not parseable and are only valid against this endpoint.
   * @param params.afterCursor - Opaque cursor from a previous response; returns outcomes newer than it. Suited to a UI loading newer entries. To poll for everything recorded since a point in time, prefer `since` with a little overlap and de-duplicate on `id` — `after_cursor` can miss an attempt recorded in the same millisecond as the cursor's own row.
   * @returns Delivery outcomes for the requested channel, newest first.
   */
  async deliveryOutcomes(channel: string, params?: { since?: string; outcome?: "delivered" | "floored" | "judge_refused" | "failed"; limit?: number; beforeCursor?: string; afterCursor?: string }): Promise<SlackDeliveryOutcomeListResponse> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.since !== undefined) {
      query["since"] = params?.since;
    }
    if (params?.outcome !== undefined) {
      query["outcome"] = params?.outcome;
    }
    if (params?.limit !== undefined) {
      query["limit"] = params?.limit;
    }
    if (params?.beforeCursor !== undefined) {
      query["before_cursor"] = params?.beforeCursor;
    }
    if (params?.afterCursor !== undefined) {
      query["after_cursor"] = params?.afterCursor;
    }

    return this.http.request(`/api/v1/slack_channel_bindings/${channel}/delivery_outcomes`, { query });
  }

  /**
   * Point a Slack channel's deposit pipe at a staging thread, or turn it off
   * Sets the binding's deposit target — the internal staging thread the
   * deposit pipe copies this channel's mirror content into. Pass a `null`
   * `thread_id` to turn the pipe off.
   * The target is validated server-side: it must exist, belong to the
   * binding's app and org, and never be a Slack mirror thread. Customer
   * bindings (bound `team_id`) additionally require a team-owned private
   * thread with no participant list, so the staging read ACL stays governed
   * by the channel-membership projection. Re-pointing or clearing an
   * existing target purges the old thread's deposit entries.
   * @param channel - Slack channel ID whose binding is being configured (e.g. `C01234ABCDE`).
   * @param input - Request body.
   * @param input.slack_team_id - Slack workspace team ID that the channel belongs to (e.g. `T01234ABCDE`). Identifies which Slack integration to use.
   * @param input.thread_id - Staging thread ID (primary key, `thr_…`) deposits should flow into. Pass `null` to turn the pipe off.
   * @returns The binding with the updated deposit config.
   */
  async depositThread(channel: string, input: { slack_team_id: string; thread_id?: string | undefined }): Promise<SlackChannelBinding> {
    return this.http.request(`/api/v1/slack_channel_bindings/${channel}/deposit_thread`, { method: "POST", body: input });
  }
}
