// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 58281a94c15d

import { HttpClient } from "../../runtime/http-client.js";

export class SshKeyResource {
  constructor(private http: HttpClient) {}

  /**
   * Revoke an SSH public key
   * Revokes an owned key immediately. The key remains visible as audit metadata.
   * @param sshKey - Registered SSH key ID (`ssk_...`).
   * @returns No content
   */
  async delete(sshKey: string): Promise<void> {
    await this.http.request(`/api/v1/ssh_keys/${sshKey}`, { method: "DELETE" });
  }
}
