// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 8348c9589e7a

import { HttpClient } from "../../runtime/http-client.js";
import type { TeamMembershipListResponse } from "../../types/teams.js";

export class TeamMembershipResource {
  constructor(private http: HttpClient) {}

  async list(params?: { team?: string[]; user?: string[]; agent?: string[]; page?: number; pageSize?: number }): Promise<TeamMembershipListResponse> {
    return this.http.request(`/api/v1/team_memberships`, { query: params as Record<string, string | number | boolean | Array<string | number | boolean> | undefined> });
  }

  async delete(teamMembership: string): Promise<void> {
    await this.http.request(`/api/v1/team_memberships/${teamMembership}`, { method: "DELETE" });
  }
}
