// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 3ddc73bbaf5b

import { HttpClient } from "../../runtime/http-client.js";
import type { TeamMembershipListResponse } from "../../types/teams.js";

export class TeamMembershipResource {
  constructor(private http: HttpClient) {}

  /**
   * List team memberships
   * Returns a paginated list of team memberships across all teams accessible to
   * the authenticated caller. Use the `team`, `user`, and `agent` filters to
   * narrow results to a specific team or principal.
   * This endpoint requires S2S (service-to-service) authentication. Callers
   * authenticated with a user token receive a 401. Each membership includes the
   * resolved `type` (`"user"`, `"agent"`, or `"unknown"`), display name, and
   * profile picture derived from the associated user or agent at request time.
   * Results are returned in offset-based pages. Pass `page` and `page_size` to
   * navigate; the response includes `has_next` and `has_prev` to determine
   * whether adjacent pages exist.
   * @param params - Query parameters.
   * @param params.team - Filter results to memberships belonging to these team IDs (`tm_...`). Multiple values are combined with OR.
   * @param params.user - Filter results to memberships held by these user IDs (`usr_...`). Multiple values are combined with OR.
   * @param params.agent - Filter results to memberships held by these agent IDs (`agt_...`). Multiple values are combined with OR.
   * @param params.page - Page number to retrieve, starting at `1`. Defaults to `1`.
   * @param params.pageSize - Number of memberships to return per page. Defaults to `25`.
   * @returns Paginated list of team memberships matching the applied filters.
   */
  async list(params?: { team?: string[]; user?: string[]; agent?: string[]; page?: number; pageSize?: number }): Promise<TeamMembershipListResponse> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.team !== undefined) {
      query["team"] = params?.team;
    }
    if (params?.user !== undefined) {
      query["user"] = params?.user;
    }
    if (params?.agent !== undefined) {
      query["agent"] = params?.agent;
    }
    if (params?.page !== undefined) {
      query["page"] = params?.page;
    }
    if (params?.pageSize !== undefined) {
      query["page_size"] = params?.pageSize;
    }

    return this.http.request(`/api/v1/team_memberships`, { query });
  }

  /**
   * Remove a team membership by ID
   * Removes a team membership identified directly by its membership ID. On
   * success, returns 204 No Content.
   * This endpoint is intended for server-to-server callers that already hold the
   * membership ID. To remove a member by user or agent ID instead, use the team
   * members delete endpoint. The caller must have permission to manage the team
   * that the membership belongs to.
   * @param teamMembership - Team membership ID (`tmb_...`) to remove. The membership must be within the caller's app scope.
   * @returns Empty response. Returns 204 No Content on success.
   */
  async delete(teamMembership: string): Promise<void> {
    await this.http.request(`/api/v1/team_memberships/${teamMembership}`, { method: "DELETE" });
  }
}
