// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 85449a1601a6

import { HttpClient } from "../../runtime/http-client.js";
import type { Message, PaginatedReplies } from "../../types/common.js";

export class ReactionResource {
  constructor(private http: HttpClient) {}

  /**
   * Remove a reaction from a thread message
   * Removes the authenticated user's emoji reaction from the specified thread
   * message. The reaction is identified by the combination of the message ID and
   * the emoji; only the reaction belonging to the calling user is removed.
   * Returns 204 No Content on success. Returns 404 if no matching reaction
   * exists for the user and emoji on that message, or if the message itself
   * cannot be found. The authenticated user must have read access to the thread
   * containing the message.
   * @param message - Message ID (`msg_...`) of the thread message whose reaction should be removed.
   * @returns Empty response body. HTTP 204 No Content on success.
   */
  async remove(message: string): Promise<void> {
    await this.http.request(`/api/v1/thread_messages/${message}/reactions`, { method: "DELETE" });
  }

  /**
   * Add a reaction to a thread message
   * Adds an emoji reaction to the specified thread message on behalf of the
   * authenticated user. If the user has already reacted to the message with the
   * same emoji, the request returns a 409 Conflict rather than creating a
   * duplicate.
   * The authenticated user must have read access to the thread containing the
   * message. If the thread belongs to a team, the user must be a member of
   * that team.
   * @param message - Message ID (`msg_...`) of the thread message whose reaction should be removed.
   * @param input - Request body.
   * @param input.emoji - Emoji character or shortcode to add as a reaction, e.g. `"👍"` or `":thumbsup:"`.
   * @returns Successful response
   */
  async create(message: string, input: { emoji: string }): Promise<{ data: { created_at?: string | undefined; feedback_type?: string | undefined; id: string; message?: string | undefined; payload?: Record<string, unknown> | undefined; updated_at?: string | undefined; user?: string | undefined } }> {
    return this.http.request(`/api/v1/thread_messages/${message}/reactions`, { method: "POST", body: input });
  }
}

export class ThreadMessageResource {
  readonly reactions: ReactionResource;

  constructor(private http: HttpClient) {
    this.reactions = new ReactionResource(http);
  }

  /**
   * Delete a thread message
   * Permanently removes the specified message from its thread. This action
   * cannot be undone.
   * A regular user may only delete messages they authored. Service-to-service
   * callers with elevated (`all_powerful`) scope may delete any message in a
   * thread they can access. Returns `403 Forbidden` when the caller does not
   * own the message.
   * @param message - ID of the message to delete (`msg_...`).
   * @returns Empty body. The server responds with HTTP 204 No Content on success.
   */
  async delete(message: string): Promise<void> {
    await this.http.request(`/api/v1/thread_messages/${message}`, { method: "DELETE" });
  }

  /**
   * Update a thread message
   * Edits the content of an existing thread message and returns the updated
   * message object.
   * A regular user may only edit messages they authored. Service-to-service
   * callers with elevated (`all_powerful`) scope may edit any accessible message
   * without an ownership check. Returns `403 Forbidden` when the caller does not
   * own the message.
   * @param message - ID of the message to update (`msg_...`).
   * @param input - Request body.
   * @param input.content - Replacement text content for the message. Omit to leave the content unchanged.
   * @returns The updated message object reflecting the new content.
   */
  async replace(message: string, input: { content?: string | undefined }): Promise<Message> {
    return this.http.request(`/api/v1/thread_messages/${message}`, { method: "PUT", body: input });
  }

  /**
   * List replies to a thread message
   * Returns a cursor-paginated list of reply messages for the specified thread
   * message. By default only direct (first-level) replies are returned. Set
   * `tree` to `true` to retrieve the full nested reply tree in a flat list,
   * ordered by creation time ascending.
   * The authenticated user must have access to the thread that contains the
   * message. If the message belongs to a team-scoped thread, the viewer is
   * automatically scoped to that team before the query executes.
   * Use `before_cursor` and `after_cursor` together with `limit` to page
   * through large reply threads. The `has_more` field in the response
   * indicates whether additional pages exist.
   * @param message - ID of the thread message to fetch replies for (`msg_...`).
   * @param params - Query parameters.
   * @param params.beforeCursor - Opaque pagination cursor. Returns replies created before this point. Obtain from `before_cursor` in a previous response.
   * @param params.afterCursor - Opaque pagination cursor. Returns replies created after this point. Obtain from `after_cursor` in a previous response.
   * @param params.limit - Maximum number of replies to return per page. Defaults to 20.
   * @param params.tree - When `true`, returns all replies in the nested reply tree (flattened). When `false` or omitted, returns only direct replies to the message.
   * @returns Cursor-paginated list of reply messages for the requested thread message.
   */
  async replies(message: string, params?: { beforeCursor?: string; afterCursor?: string; limit?: number; tree?: boolean }): Promise<PaginatedReplies> {
    const query: Record<string, string | number | boolean | Array<string | number | boolean> | undefined> = {};
    if (params?.beforeCursor !== undefined) {
      query["before_cursor"] = params?.beforeCursor;
    }
    if (params?.afterCursor !== undefined) {
      query["after_cursor"] = params?.afterCursor;
    }
    if (params?.limit !== undefined) {
      query["limit"] = params?.limit;
    }
    if (params?.tree !== undefined) {
      query["tree"] = params?.tree;
    }

    return this.http.request(`/api/v1/thread_messages/${message}/replies`, { query });
  }
}
