// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 16a635d8391a


import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

let prismProcess: ChildProcessWithoutNullStreams | undefined;
let harnessProcess: ChildProcessWithoutNullStreams | undefined;

// Channel contract tests are opt-in. Set ARCHASTRO_RUN_CHANNEL_CONTRACT_TESTS=1
// to spawn the harness-service subprocess and run them; otherwise the channel
// test files are filtered out by the vitest config and the subprocess is skipped.
function channelTestsEnabled(): boolean {
  const v = process.env.ARCHASTRO_RUN_CHANNEL_CONTRACT_TESTS;
  return v === "1" || v === "true" || v === "yes";
}

export async function setup() {
  const specPath = process.env.OPENAPI_SPEC_PATH
    ?? resolve(__dirname, "../../specs/platform-openapi.json");

  const prismPort = process.env.PRISM_PORT ?? "4040";
  prismProcess = spawn("npx", [
    "@stoplight/prism-cli", "mock", specPath,
    "--port", prismPort,
    "--host", "127.0.0.1",
    "--dynamic",
  ], { stdio: ["pipe", "pipe", "pipe"] });
  await waitForPrism(parseInt(prismPort), 30_000);

  if (!channelTestsEnabled()) return;

  // Spawn the channel-harness service — the same subprocess Python (or any
  // other language) tests spawn. Tests talk to it over HTTP + WebSocket
  // rather than importing ContractServer in-process: no shortcuts.
  const harnessBin = process.env.ARCHASTRO_HARNESS_BIN
    ?? require.resolve("@archastro/channel-harness/bin");
  harnessProcess = spawn("node", [harnessBin, specPath], {
    stdio: ["pipe", "pipe", "pipe"],
  });
  const urls = await readHarnessUrls(harnessProcess, 15_000);
  process.env.ARCHASTRO_HARNESS_WS_URL = urls.wsUrl;
  process.env.ARCHASTRO_HARNESS_CONTROL_URL = urls.controlUrl;
}

export async function teardown() {
  prismProcess?.kill("SIGTERM");
  harnessProcess?.kill("SIGTERM");
}

async function waitForPrism(port: number, timeoutMs: number): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (prismProcess!.exitCode !== null) {
      throw new Error(`Prism exited with code ${prismProcess!.exitCode} before becoming ready`);
    }
    try {
      const res = await fetch(`http://127.0.0.1:${port}/`);
      if (res) return;
    } catch {
      // not ready yet
    }
    await new Promise((r) => setTimeout(r, 300));
  }
  throw new Error(`Prism did not start within ${timeoutMs}ms`);
}

async function readHarnessUrls(
  proc: ChildProcessWithoutNullStreams,
  timeoutMs: number
): Promise<{ wsUrl: string; controlUrl: string }> {
  return new Promise((resolvePromise, reject) => {
    let buf = "";
    const onData = (chunk: Buffer): void => {
      buf += chunk.toString("utf-8");
      const nl = buf.indexOf("\n");
      if (nl === -1) return;
      const line = buf.slice(0, nl);
      proc.stdout.off("data", onData);
      try {
        const parsed = JSON.parse(line) as { wsUrl: string; controlUrl: string };
        if (!parsed.wsUrl || !parsed.controlUrl) {
          throw new Error(
            `harness service did not report URLs: ${JSON.stringify(parsed)}`
          );
        }
        resolvePromise(parsed);
      } catch (err) {
        reject(err);
      }
    };
    const onExit = (code: number | null): void => {
      reject(
        new Error(`harness service exited before reporting URLs (code=${code})`)
      );
    };
    proc.stdout.on("data", onData);
    proc.once("exit", onExit);
    setTimeout(() => {
      proc.stdout.off("data", onData);
      proc.off("exit", onExit);
      reject(new Error(`timed out after ${timeoutMs}ms waiting for harness URLs`));
    }, timeoutMs).unref();
  });
}
