// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: ed71c9ebc721


import { describe, it, expect } from "vitest";
import { PlatformClient } from "../../../src/index.js";
import { ApiError } from "../../../src/runtime/http-client.js";

const PRISM_URL = process.env.PRISM_URL ?? "http://127.0.0.1:4040";

const client = new PlatformClient({
  baseUrl: PRISM_URL,
  defaultHeaders: { "x-archastro-api-key": "pk_test-key" },
  accessToken: "test-token",
});

function errorClient(code: number): PlatformClient {
  return new PlatformClient({
    baseUrl: PRISM_URL,
    defaultHeaders: { "x-archastro-api-key": "pk_test-key", "Prefer": `code=${code}` },
    accessToken: "test-token",
  });
}

describe("contract: agent_tools", () => {
  describe("agent_tools", () => {
    it("DELETE /api/v1/agent_tools/{tool} returns successfully", async () => {
      await client.v1.agent_tools.delete("test-value");
    });

    it("DELETE /api/v1/agent_tools/{tool} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.agent_tools.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("DELETE /api/v1/agent_tools/{tool} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.agent_tools.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("DELETE /api/v1/agent_tools/{tool} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.agent_tools.delete("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("GET /api/v1/agent_tools/{tool} returns successfully", async () => {
      const result = await client.v1.agent_tools.get("test-value");
      expect(result).toBeDefined();
    });

    it("GET /api/v1/agent_tools/{tool} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.agent_tools.get("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/agent_tools/{tool} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.agent_tools.get("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("GET /api/v1/agent_tools/{tool} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.agent_tools.get("test-value");
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("PATCH /api/v1/agent_tools/{tool} returns successfully", async () => {
      const result = await client.v1.agent_tools.update("test-value", { tool: "test-value" });
      expect(result).toBeDefined();
    });

    it("PATCH /api/v1/agent_tools/{tool} returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.agent_tools.update("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("PATCH /api/v1/agent_tools/{tool} returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.agent_tools.update("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("PATCH /api/v1/agent_tools/{tool} returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.agent_tools.update("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("PATCH /api/v1/agent_tools/{tool} returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.agent_tools.update("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

    it("GET /api/v1/agent_tools/catalog returns successfully", async () => {
      const result = await client.v1.agent_tools.catalog();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/agent_tools/catalog returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.agent_tools.catalog();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/agent_tools/catalog returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.agent_tools.catalog();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("GET /api/v1/agent_tools returns successfully", async () => {
      const result = await client.v1.agent_tools.list();
      expect(result).toBeDefined();
    });

    it("GET /api/v1/agent_tools returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.agent_tools.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("GET /api/v1/agent_tools returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.agent_tools.list();
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/agent_tools/{tool}/deactivate returns successfully", async () => {
      const result = await client.v1.agent_tools.deactivate("test-value", { tool: "test-value" });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/agent_tools/{tool}/deactivate returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.agent_tools.deactivate("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/agent_tools/{tool}/deactivate returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.agent_tools.deactivate("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/agent_tools/{tool}/deactivate returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.agent_tools.deactivate("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/agent_tools/{tool}/activate returns successfully", async () => {
      const result = await client.v1.agent_tools.activate("test-value", { tool: "test-value" });
      expect(result).toBeDefined();
    });

    it("POST /api/v1/agent_tools/{tool}/activate returns 401", async () => {
      const ec = errorClient(401);
      try {
        await ec.v1.agent_tools.activate("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(401);
      }
    });

    it("POST /api/v1/agent_tools/{tool}/activate returns 403", async () => {
      const ec = errorClient(403);
      try {
        await ec.v1.agent_tools.activate("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(403);
      }
    });

    it("POST /api/v1/agent_tools/{tool}/activate returns 404", async () => {
      const ec = errorClient(404);
      try {
        await ec.v1.agent_tools.activate("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(404);
      }
    });

    it("POST /api/v1/agent_tools/{tool}/activate returns 422", async () => {
      const ec = errorClient(422);
      try {
        await ec.v1.agent_tools.activate("test-value", { tool: "test-value" });
        expect.fail("Expected ApiError to be thrown");
      } catch (e) {
        expect(e).toBeInstanceOf(ApiError);
        expect((e as ApiError).status).toBe(422);
      }
    });

  });

});
