// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 3cc30d4d2979

import { AuthClient } from "./auth.js";
import { HttpClient } from "./runtime/http-client.js";
import { V1 } from "./v1.js";
import type { HttpClientConfig } from "./runtime/http-client.js";
import type { AgentComputerResource } from "./v1/resources/agent_computers.js";
import type { AgentInstallationResource } from "./v1/resources/agent_installations.js";
import type { AgentRoutineResource } from "./v1/resources/agent_routines.js";
import type { AgentSessionResource } from "./v1/resources/agent_sessions.js";
import type { AgentSkillResource } from "./v1/resources/agent_skills.js";
import type { AgentToolResource } from "./v1/resources/agent_tools.js";
import type { AgentResource } from "./v1/resources/agents.js";
import type { AiResource } from "./v1/resources/ai.js";
import type { ArtifactResource } from "./v1/resources/artifacts.js";
import type { AutomationRunResource } from "./v1/resources/automation_runs.js";
import type { AutomationResource } from "./v1/resources/automations.js";
import type { ConfigResource } from "./v1/resources/config.js";
import type { CustomObjectResource } from "./v1/resources/custom_objects.js";
import type { InstallationSourceResource } from "./v1/resources/installation_sources.js";
import type { OrgResource } from "./v1/resources/orgs.js";
import type { TeamMembershipResource } from "./v1/resources/team_memberships.js";
import type { TeamResource } from "./v1/resources/teams.js";
import type { ThreadMessageResource } from "./v1/resources/thread_messages.js";
import type { ThreadResource } from "./v1/resources/threads.js";
import type { UserResource } from "./v1/resources/users.js";

export interface PlatformClientConfig {
  baseUrl?: string;
  accessToken?: string;
  getAccessToken?: () => string | undefined;
  onRefreshToken?: () => Promise<string>;
  pathPrefix?: string;
  defaultHeaders?: Record<string, string>;
}

export class PlatformClient {
  readonly http: HttpClient;
  readonly auth: AuthClient;
  readonly v1: V1;
  readonly automation_runs: AutomationRunResource;
  readonly config: ConfigResource;
  readonly artifacts: ArtifactResource;
  readonly installation_sources: InstallationSourceResource;
  readonly agent_routines: AgentRoutineResource;
  readonly users: UserResource;
  readonly agent_sessions: AgentSessionResource;
  readonly teams: TeamResource;
  readonly agent_tools: AgentToolResource;
  readonly team_memberships: TeamMembershipResource;
  readonly agent_installations: AgentInstallationResource;
  readonly agents: AgentResource;
  readonly orgs: OrgResource;
  readonly agent_computers: AgentComputerResource;
  readonly agent_skills: AgentSkillResource;
  readonly threads: ThreadResource;
  readonly custom_objects: CustomObjectResource;
  readonly automations: AutomationResource;
  readonly thread_messages: ThreadMessageResource;
  readonly ai: AiResource;

  constructor(config: PlatformClientConfig = {}) {
    const httpConfig: HttpClientConfig = {
      baseUrl: config.baseUrl ?? "https://platform.archastro.ai",
      accessToken: config.accessToken,
      getAccessToken: config.getAccessToken,
      onRefreshToken: config.onRefreshToken,
      pathPrefix: config.pathPrefix,
      defaultHeaders: config.defaultHeaders,
    };

    this.http = new HttpClient(httpConfig);
    this.auth = new AuthClient(this.http);
    this.v1 = new V1(this.http);
    this.automation_runs = this.v1.automation_runs;
    this.config = this.v1.config;
    this.artifacts = this.v1.artifacts;
    this.installation_sources = this.v1.installation_sources;
    this.agent_routines = this.v1.agent_routines;
    this.users = this.v1.users;
    this.agent_sessions = this.v1.agent_sessions;
    this.teams = this.v1.teams;
    this.agent_tools = this.v1.agent_tools;
    this.team_memberships = this.v1.team_memberships;
    this.agent_installations = this.v1.agent_installations;
    this.agents = this.v1.agents;
    this.orgs = this.v1.orgs;
    this.agent_computers = this.v1.agent_computers;
    this.agent_skills = this.v1.agent_skills;
    this.threads = this.v1.threads;
    this.custom_objects = this.v1.custom_objects;
    this.automations = this.v1.automations;
    this.thread_messages = this.v1.thread_messages;
    this.ai = this.v1.ai;
  }


  private _refreshToken?: string;

  get refreshToken(): string | undefined {
    return this._refreshToken;
  }

  setAccessToken(token: string) {
    this.http.setAccessToken(token);
  }

  setRefreshToken(token: string) {
    this._refreshToken = token;
  }

  // ─── Factory constructors (generated from auth schemes) ───

  /** Secret API key — full admin access, no user JWT required */
  static withSecretKey(key: string, baseUrl?: string): PlatformClient {
    return new PlatformClient({
      baseUrl,
      defaultHeaders: { "x-archastro-api-key": key },
    });
  }

  /** Create a client with a publishable key and pre-existing access token. */
  static withToken(apiKey: string, accessToken: string, baseUrl?: string): PlatformClient {
    return new PlatformClient({
      baseUrl,
      accessToken,
      defaultHeaders: { "x-archastro-api-key": apiKey },
    });
  }

  /** Create a client by logging in with email/password */
  static async withCredentials(apiKey: string, email: string, password: string, baseUrl?: string): Promise<PlatformClient> {
    const client = new PlatformClient({
      baseUrl,
      defaultHeaders: { "x-archastro-api-key": apiKey },
    });
    const tokens = await client.auth.login(email, password);
    if (!tokens.accessToken) throw new Error("Login did not return an access token");
    client.setAccessToken(tokens.accessToken);
    if (tokens.refreshToken) client.setRefreshToken(tokens.refreshToken);
    const refreshHttp = new HttpClient({
      baseUrl: baseUrl ?? "https://platform.archastro.ai",
      defaultHeaders: { "x-archastro-api-key": apiKey },
      refreshOnly: true,
    });
    const refreshAuth = new AuthClient(refreshHttp);
    client.http.setRefreshHandler(async () => {
      const rt = client.refreshToken;
      if (!rt) throw new Error("No refresh token available");
      const refreshed = await refreshAuth.refresh(rt);
      if (!refreshed.accessToken) throw new Error("Refresh did not return an access token");
      client.setAccessToken(refreshed.accessToken);
      if (refreshed.refreshToken) client.setRefreshToken(refreshed.refreshToken);
      return refreshed.accessToken;
    });
    return client;
  }
}
