// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 82e692843de1

// Contract tests for the generated channel class. Drives the channel
// through a real WebSocket against the harness-service subprocess —
// the same service Python tests connect to. Scenario closures are
// serialized over an HTTP control API, not passed in-process.

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  ChannelJoinError,
  ChannelReplyError,
  HarnessServiceClient,
  type HarnessSocket,
} from "@archastro/sdk-generator/channel-harness";
import { ApiActivityFeedChannel } from "../../../src/channels/api_activity_feed_channel.js";

interface Rig {
  client: HarnessServiceClient;
  socket: HarnessSocket;
}

// Check the env vars inside bootHarness() rather than at module scope:
// a module-level throw would surface as a vitest collection error for the
// whole file, while a thrown inside bootHarness() becomes a normal test
// failure that doesn't tear down the rest of the suite.
async function bootHarness(): Promise<Rig> {
  const wsUrl = process.env.ARCHASTRO_HARNESS_WS_URL;
  const controlUrl = process.env.ARCHASTRO_HARNESS_CONTROL_URL;
  if (!wsUrl || !controlUrl) {
    throw new Error(
      "Channel contract tests require ARCHASTRO_HARNESS_WS_URL and " +
        "ARCHASTRO_HARNESS_CONTROL_URL — set by global-setup.ts."
    );
  }
  const client = new HarnessServiceClient({ wsUrl, controlUrl });
  await client.reset();
  const socket = await client.openSocket();
  return { client, socket };
}

function nextPush(
  subscribe: (cb: (payload: unknown) => void) => () => void,
  timeoutMs = 500
): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let settled = false;
    let unsubscribe: (() => void) | null = null;
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      unsubscribe?.();
      reject(new Error("push not received in time"));
    }, timeoutMs);
    unsubscribe = subscribe((payload) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      unsubscribe?.();
      resolve(payload);
    });
    if (settled) unsubscribe();
  });
}

describe("ApiActivityFeedChannel.joinAgent (api:activity_feed:agent:{agent_id})", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("joins and receives a contract-valid reply", async () => {
    const channel = await ApiActivityFeedChannel.joinAgent(rig.socket, "test-id");
    expect(channel).toBeInstanceOf(ApiActivityFeedChannel);
    expect(channel.joinResponse).toBeDefined();
  });

  it("surfaces an application-level error reply as ChannelJoinError", async () => {
    await rig.client.registerScenario({
      topic: "api:activity_feed:agent:test-id",
      onJoin: [{ type: "replyError", payload: { reason: "test_error" } }],
    });

    const err = await ApiActivityFeedChannel.joinAgent(rig.socket, "test-id").catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ChannelJoinError);
    expect((err as ChannelJoinError).response).toEqual({ reason: "test_error" });
  });
});

describe("ApiActivityFeedChannel.joinOrg (api:activity_feed:org:{org_id})", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("joins and receives a contract-valid reply", async () => {
    const channel = await ApiActivityFeedChannel.joinOrg(rig.socket, "test-id");
    expect(channel).toBeInstanceOf(ApiActivityFeedChannel);
    expect(channel.joinResponse).toBeDefined();
  });

  it("surfaces an application-level error reply as ChannelJoinError", async () => {
    await rig.client.registerScenario({
      topic: "api:activity_feed:org:test-id",
      onJoin: [{ type: "replyError", payload: { reason: "test_error" } }],
    });

    const err = await ApiActivityFeedChannel.joinOrg(rig.socket, "test-id").catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ChannelJoinError);
    expect((err as ChannelJoinError).response).toEqual({ reason: "test_error" });
  });
});

describe("ApiActivityFeedChannel.listEntries (list_entries)", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("sends a valid push and receives a contract-valid reply", async () => {
    await rig.client.registerScenario({
      topic: "api:activity_feed:agent:test-id",
      onJoin: [{ type: "autoReply" }],
      onMessage: {
        "list_entries": [{ type: "autoReply" }],
      },
    });

    const channel = await ApiActivityFeedChannel.joinAgent(rig.socket, "test-id");
    const reply = await channel.listEntries({ after_cursor: "test-value", before_cursor: "test-value", kind: "test", level: "test-value", limit: 1 });
    expect(reply).toBeDefined();

    const observed = await rig.client.observations("api:activity_feed:agent:test-id", "list_entries");
    expect(observed).toHaveLength(1);
    expect(observed[0]!.params).toBeDefined();
  });
});

describe("ApiActivityFeedChannel.onNewEntry (new_entry)", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("delivers contract-valid payloads to onNewEntry", async () => {
    await rig.client.registerScenario({
      topic: "api:activity_feed:agent:test-id",
      onJoin: [
        { type: "autoReply" },
        { type: "autoPush", event: "new_entry" },
      ],
    });

    const channel = await ApiActivityFeedChannel.joinAgent(rig.socket, "test-id");
    const payload = await nextPush((cb) => channel.onNewEntry(cb));
    expect(payload).toBeDefined();
  });
});

describe("ApiActivityFeedChannel.leave", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("leaves cleanly through the generated leave()", async () => {
    await rig.client.registerScenario({
      topic: "api:activity_feed:agent:test-id",
      onJoin: [{ type: "autoReply" }],
    });
    const channel = await ApiActivityFeedChannel.joinAgent(rig.socket, "test-id");
    await channel.leave();
  });
});

