// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e6d7133e63ff

// Contract tests for the generated channel class. Drives the channel
// through a real WebSocket against the harness-service subprocess —
// the same service Python tests connect to. Scenario closures are
// serialized over an HTTP control API, not passed in-process.

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  ChannelJoinError,
  ChannelReplyError,
  HarnessServiceClient,
  type HarnessSocket,
} from "@archastro/sdk-generator/channel-harness";
import { ApiObjectChannel } from "../../../src/channels/api_object_channel.js";

interface Rig {
  client: HarnessServiceClient;
  socket: HarnessSocket;
}

// Check the env vars inside bootHarness() rather than at module scope:
// a module-level throw would surface as a vitest collection error for the
// whole file, while a thrown inside bootHarness() becomes a normal test
// failure that doesn't tear down the rest of the suite.
async function bootHarness(): Promise<Rig> {
  const wsUrl = process.env.ARCHASTRO_HARNESS_WS_URL;
  const controlUrl = process.env.ARCHASTRO_HARNESS_CONTROL_URL;
  if (!wsUrl || !controlUrl) {
    throw new Error(
      "Channel contract tests require ARCHASTRO_HARNESS_WS_URL and " +
        "ARCHASTRO_HARNESS_CONTROL_URL — set by global-setup.ts."
    );
  }
  const client = new HarnessServiceClient({ wsUrl, controlUrl });
  await client.reset();
  const socket = await client.openSocket();
  return { client, socket };
}

function nextPush(
  subscribe: (cb: (payload: unknown) => void) => () => void,
  timeoutMs = 500
): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let settled = false;
    let unsubscribe: (() => void) | null = null;
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      unsubscribe?.();
      reject(new Error("push not received in time"));
    }, timeoutMs);
    unsubscribe = subscribe((payload) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      unsubscribe?.();
      resolve(payload);
    });
    if (settled) unsubscribe();
  });
}

describe("ApiObjectChannel.joinById (api:object:{object_id})", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("joins and receives a contract-valid reply", async () => {
    const channel = await ApiObjectChannel.joinById(rig.socket, "test-id");
    expect(channel).toBeInstanceOf(ApiObjectChannel);
    expect(channel.joinResponse).toBeDefined();
  });

  it("surfaces an application-level error reply as ChannelJoinError", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-id",
      onJoin: [{ type: "replyError", payload: { reason: "test_error" } }],
    });

    const err = await ApiObjectChannel.joinById(rig.socket, "test-id").catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ChannelJoinError);
    expect((err as ChannelJoinError).response).toEqual({ reason: "test_error" });
  });
});

describe("ApiObjectChannel.joinByRowKey (api:object:{schema_type}:{row_key})", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("joins and receives a contract-valid reply", async () => {
    const channel = await ApiObjectChannel.joinByRowKey(rig.socket, "test-value", "test-key");
    expect(channel).toBeInstanceOf(ApiObjectChannel);
    expect(channel.joinResponse).toBeDefined();
  });

  it("surfaces an application-level error reply as ChannelJoinError", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-value:test-key",
      onJoin: [{ type: "replyError", payload: { reason: "test_error" } }],
    });

    const err = await ApiObjectChannel.joinByRowKey(rig.socket, "test-value", "test-key").catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ChannelJoinError);
    expect((err as ChannelJoinError).response).toEqual({ reason: "test_error" });
  });
});

describe("ApiObjectChannel.updateFields (update_fields)", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("sends a valid push and receives a contract-valid reply", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-id",
      onJoin: [{ type: "autoReply" }],
      onMessage: {
        "update_fields": [{ type: "autoReply" }],
      },
    });

    const channel = await ApiObjectChannel.joinById(rig.socket, "test-id");
    const reply = await channel.updateFields({ fields: {} });
    expect(reply).toBeDefined();

    const observed = await rig.client.observations("api:object:test-id", "update_fields");
    expect(observed).toHaveLength(1);
    expect(observed[0]!.params).toEqual(expect.objectContaining({ fields: {} }));
  });

  it("rejects with ChannelReplyError when required params are missing", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-id",
      onJoin: [{ type: "autoReply" }],
    });
    const channel = await ApiObjectChannel.joinById(rig.socket, "test-id");

    await expect(channel.updateFields({})).rejects.toBeInstanceOf(ChannelReplyError);
  });
});

describe("ApiObjectChannel.save (save)", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("sends a valid push and receives a contract-valid reply", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-id",
      onJoin: [{ type: "autoReply" }],
      onMessage: {
        "save": [{ type: "autoReply" }],
      },
    });

    const channel = await ApiObjectChannel.joinById(rig.socket, "test-id");
    const reply = await channel.save({});
    expect(reply).toBeDefined();

    const observed = await rig.client.observations("api:object:test-id", "save");
    expect(observed).toHaveLength(1);
    expect(observed[0]!.params).toBeDefined();
  });
});

describe("ApiObjectChannel.onObjectUpdated (object_updated)", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("delivers contract-valid payloads to onObjectUpdated", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-id",
      onJoin: [
        { type: "autoReply" },
        { type: "autoPush", event: "object_updated" },
      ],
    });

    const channel = await ApiObjectChannel.joinById(rig.socket, "test-id");
    const payload = await nextPush((cb) => channel.onObjectUpdated(cb));
    expect(payload).toBeDefined();
  });
});

describe("ApiObjectChannel.onObjectCreated (object_created)", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("delivers contract-valid payloads to onObjectCreated", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-id",
      onJoin: [
        { type: "autoReply" },
        { type: "autoPush", event: "object_created" },
      ],
    });

    const channel = await ApiObjectChannel.joinById(rig.socket, "test-id");
    const payload = await nextPush((cb) => channel.onObjectCreated(cb));
    expect(payload).toBeDefined();
  });
});

describe("ApiObjectChannel.leave", () => {
  let rig: Rig;
  beforeEach(async () => {
    rig = await bootHarness();
  });
  afterEach(() => {
    rig.client.closeAllSockets();
  });

  it("leaves cleanly through the generated leave()", async () => {
    await rig.client.registerScenario({
      topic: "api:object:test-id",
      onJoin: [{ type: "autoReply" }],
    });
    const channel = await ApiObjectChannel.joinById(rig.socket, "test-id");
    await channel.leave();
  });
});

