// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: a9120b7e4fcc

import { z } from "zod";

/** Terminal event marking the end of a streaming chat completion (SSE `done` event). */
export interface AIChatStreamDone {
  /** The overall finish reason for the completion. */
  finish_reason?: string | undefined;
  /** Number of model runs executed, including continuations triggered by tool calls. */
  run_count?: number | undefined;
  /** Aggregate token usage across every run in the completion (including tool-call continuations), keyed by model ID. */
  total_usage?: Record<string, unknown> | undefined;
  /** Token usage for the final run, keyed by model ID. */
  usage?: Record<string, unknown> | undefined;
}

/** Runtime validator for {@link AIChatStreamDone}. */
export const aIChatStreamDoneSchema = z.object({
  /** The overall finish reason for the completion. */
  finish_reason: z.string().optional().describe("The overall finish reason for the completion."),
  /** Number of model runs executed, including continuations triggered by tool calls. */
  run_count: z.number().int().optional().describe("Number of model runs executed, including continuations triggered by tool calls."),
  /** Aggregate token usage across every run in the completion (including tool-call continuations), keyed by model ID. */
  total_usage: z.record(z.unknown()).optional().describe("Aggregate token usage across every run in the completion (including tool-call continuations), keyed by model ID."),
  /** Token usage for the final run, keyed by model ID. */
  usage: z.record(z.unknown()).optional().describe("Token usage for the final run, keyed by model ID."),
}).describe("Terminal event marking the end of a streaming chat completion (SSE `done` event).") satisfies z.ZodType<AIChatStreamDone>;

/** Terminal error event for a streaming chat completion (SSE `error` event). */
export interface AIChatStreamError {
  /** Human-readable description of the error that terminated the stream. */
  message: string;
}

/** Runtime validator for {@link AIChatStreamError}. */
export const aIChatStreamErrorSchema = z.object({
  /** Human-readable description of the error that terminated the stream. */
  message: z.string().describe("Human-readable description of the error that terminated the stream."),
}).describe("Terminal error event for a streaming chat completion (SSE `error` event).") satisfies z.ZodType<AIChatStreamError>;

/** A tool (function) call emitted by the assistant within an AI message. Mirrors the OpenAI tool-call object format. */
export interface AIToolCall {
  /** Arguments the model wants to pass to the tool, as a key-value map. Deserialize and validate these against the tool's input schema before executing. */
  arguments: Record<string, unknown>;
  /** Unique identifier for this tool call, assigned by the model. Use this value as `id` when submitting the corresponding tool result. */
  id: string;
  /** Name of the tool or function the model wants to invoke, e.g. `"web_search"` or `"run_code"`. */
  name: string;
  /** Opaque signature representing the model's internal reasoning that led to this tool call. `null` when the provider does not expose chain-of-thought data. */
  thought_signature?: string | undefined;
}

/** Runtime validator for {@link AIToolCall}. */
export const aIToolCallSchema = z.object({
  /** Arguments the model wants to pass to the tool, as a key-value map. Deserialize and validate these against the tool's input schema before executing. */
  arguments: z.record(z.unknown()).describe("Arguments the model wants to pass to the tool, as a key-value map. Deserialize and validate these against the tool's input schema before executing."),
  /** Unique identifier for this tool call, assigned by the model. Use this value as `id` when submitting the corresponding tool result. */
  id: z.string().describe("Unique identifier for this tool call, assigned by the model. Use this value as `id` when submitting the corresponding tool result."),
  /** Name of the tool or function the model wants to invoke, e.g. `"web_search"` or `"run_code"`. */
  name: z.string().describe("Name of the tool or function the model wants to invoke, e.g. `\"web_search\"` or `\"run_code\"`."),
  /** Opaque signature representing the model's internal reasoning that led to this tool call. `null` when the provider does not expose chain-of-thought data. */
  thought_signature: z.string().optional().describe("Opaque signature representing the model's internal reasoning that led to this tool call. `null` when the provider does not expose chain-of-thought data."),
}).describe("A tool (function) call emitted by the assistant within an AI message. Mirrors the OpenAI tool-call object format.") satisfies z.ZodType<AIToolCall>;

/** The result of executing a tool call, submitted back to the model as a tool-role message. Mirrors the OpenAI tool-result object format. */
export interface AIToolResult {
  /** Plain-text output produced by the tool execution. `null` when the result is expressed entirely through `resolution`. */
  content?: string | undefined;
  /** ID of the tool call this result satisfies. Must match the `id` from the corresponding `AIToolCall`. */
  id: string;
  /** Name of the tool or function that was executed, e.g. `"web_search"`. Must match the `name` from the corresponding `AIToolCall`. */
  name: string;
  /** Structured result data from the tool execution. Shape varies by tool. `null` when the result is expressed as plain text in `content`. */
  resolution?: unknown | undefined;
}

/** Runtime validator for {@link AIToolResult}. */
export const aIToolResultSchema = z.object({
  /** Plain-text output produced by the tool execution. `null` when the result is expressed entirely through `resolution`. */
  content: z.string().optional().describe("Plain-text output produced by the tool execution. `null` when the result is expressed entirely through `resolution`."),
  /** ID of the tool call this result satisfies. Must match the `id` from the corresponding `AIToolCall`. */
  id: z.string().describe("ID of the tool call this result satisfies. Must match the `id` from the corresponding `AIToolCall`."),
  /** Name of the tool or function that was executed, e.g. `"web_search"`. Must match the `name` from the corresponding `AIToolCall`. */
  name: z.string().describe("Name of the tool or function that was executed, e.g. `\"web_search\"`. Must match the `name` from the corresponding `AIToolCall`."),
  /** Structured result data from the tool execution. Shape varies by tool. `null` when the result is expressed as plain text in `content`. */
  resolution: z.unknown().optional().describe("Structured result data from the tool execution. Shape varies by tool. `null` when the result is expressed as plain text in `content`."),
}).describe("The result of executing a tool call, submitted back to the model as a tool-role message. Mirrors the OpenAI tool-result object format.") satisfies z.ZodType<AIToolResult>;

/** A single message in an AI conversation, following the OpenAI-compatible chat format. Used in both request inputs and completion responses. */
export interface AIMessage {
  /** Plain-text content of the message. Present for `system`, `user`, and `assistant` messages. `null` when the message body is expressed through `content_parts` or `tool_calls`. */
  content?: string | undefined;
  /** Multimodal content parts for the message, used when the body includes images or mixed media. Each part is a map with a `type` key (`"text"`, `"image_url"`, or `"image_data"`). `null` when `content` is set. */
  content_parts?: Record<string, unknown>[] | undefined;
  /** Opaque token that can be passed on a subsequent request to resume this conversation from the current state. `null` when the provider does not support conversation resumption. */
  resume_token?: string | undefined;
  /** The speaker role for this message. One of `"system"`, `"user"`, `"assistant"`, or `"tool"`. */
  role: string;
  /** Parsed structured data returned by the model when a JSON schema or structured-output mode was requested. Shape varies by the schema supplied at call time. `null` when structured output was not requested. */
  structured_output?: unknown | undefined;
  /** Tool calls requested by the model in an `assistant` message. Present only on assistant messages that invoke one or more tools. `null` on all other message roles. */
  tool_calls?: AIToolCall[] | undefined;
  /** Tool execution results provided in a `tool` message. Each entry corresponds to a prior tool call by its `id`. `null` on all other message roles. */
  tool_results?: AIToolResult[] | undefined;
}

/** Runtime validator for {@link AIMessage}. */
export const aIMessageSchema = z.object({
  /** Plain-text content of the message. Present for `system`, `user`, and `assistant` messages. `null` when the message body is expressed through `content_parts` or `tool_calls`. */
  content: z.string().optional().describe("Plain-text content of the message. Present for `system`, `user`, and `assistant` messages. `null` when the message body is expressed through `content_parts` or `tool_calls`."),
  /** Multimodal content parts for the message, used when the body includes images or mixed media. Each part is a map with a `type` key (`"text"`, `"image_url"`, or `"image_data"`). `null` when `content` is set. */
  content_parts: z.array(z.record(z.unknown())).optional().describe("Multimodal content parts for the message, used when the body includes images or mixed media. Each part is a map with a `type` key (`\"text\"`, `\"image_url\"`, or `\"image_data\"`). `null` when `content` is set."),
  /** Opaque token that can be passed on a subsequent request to resume this conversation from the current state. `null` when the provider does not support conversation resumption. */
  resume_token: z.string().optional().describe("Opaque token that can be passed on a subsequent request to resume this conversation from the current state. `null` when the provider does not support conversation resumption."),
  /** The speaker role for this message. One of `"system"`, `"user"`, `"assistant"`, or `"tool"`. */
  role: z.string().describe("The speaker role for this message. One of `\"system\"`, `\"user\"`, `\"assistant\"`, or `\"tool\"`."),
  /** Parsed structured data returned by the model when a JSON schema or structured-output mode was requested. Shape varies by the schema supplied at call time. `null` when structured output was not requested. */
  structured_output: z.unknown().optional().describe("Parsed structured data returned by the model when a JSON schema or structured-output mode was requested. Shape varies by the schema supplied at call time. `null` when structured output was not requested."),
  /** Tool calls requested by the model in an `assistant` message. Present only on assistant messages that invoke one or more tools. `null` on all other message roles. */
  tool_calls: z.array(aIToolCallSchema).optional().describe("Tool calls requested by the model in an `assistant` message. Present only on assistant messages that invoke one or more tools. `null` on all other message roles."),
  /** Tool execution results provided in a `tool` message. Each entry corresponds to a prior tool call by its `id`. `null` on all other message roles. */
  tool_results: z.array(aIToolResultSchema).optional().describe("Tool execution results provided in a `tool` message. Each entry corresponds to a prior tool call by its `id`. `null` on all other message roles."),
}).describe("A single message in an AI conversation, following the OpenAI-compatible chat format. Used in both request inputs and completion responses.") satisfies z.ZodType<AIMessage>;

/** The fully assembled assistant message for one run of a streaming chat completion (SSE `message_complete` event). */
export interface AIChatStreamMessageComplete {
  /** Why the model stopped generating this message, e.g. `"stop"`, `"length"`, or `"tool_calls"`. */
  finish_reason?: string | undefined;
  /** The complete assistant message for this run, assembled from the preceding deltas. */
  message: AIMessage;
  /** Token consumption for this run, keyed by model ID. `null` when usage data is unavailable. */
  usage?: Record<string, unknown> | undefined;
}

/** Runtime validator for {@link AIChatStreamMessageComplete}. */
export const aIChatStreamMessageCompleteSchema = z.object({
  /** Why the model stopped generating this message, e.g. `"stop"`, `"length"`, or `"tool_calls"`. */
  finish_reason: z.string().optional().describe("Why the model stopped generating this message, e.g. `\"stop\"`, `\"length\"`, or `\"tool_calls\"`."),
  /** The complete assistant message for this run, assembled from the preceding deltas. */
  message: aIMessageSchema.describe("The complete assistant message for this run, assembled from the preceding deltas."),
  /** Token consumption for this run, keyed by model ID. `null` when usage data is unavailable. */
  usage: z.record(z.unknown()).optional().describe("Token consumption for this run, keyed by model ID. `null` when usage data is unavailable."),
}).describe("The fully assembled assistant message for one run of a streaming chat completion (SSE `message_complete` event).") satisfies z.ZodType<AIChatStreamMessageComplete>;

/** Incremental assistant text emitted during a streaming chat completion (SSE `message_delta` event). */
export interface AIChatStreamMessageDelta {
  /** The chunk of assistant text produced since the previous `message_delta` event. Concatenate deltas in order to reconstruct the message. */
  delta: string;
}

/** Runtime validator for {@link AIChatStreamMessageDelta}. */
export const aIChatStreamMessageDeltaSchema = z.object({
  /** The chunk of assistant text produced since the previous `message_delta` event. Concatenate deltas in order to reconstruct the message. */
  delta: z.string().describe("The chunk of assistant text produced since the previous `message_delta` event. Concatenate deltas in order to reconstruct the message."),
}).describe("Incremental assistant text emitted during a streaming chat completion (SSE `message_delta` event).") satisfies z.ZodType<AIChatStreamMessageDelta>;

/** Incremental tool-call data emitted as the model assembles a tool invocation (SSE `tool_call_delta` event). */
export interface AIChatStreamToolCallDelta {
  /** A chunk of the tool call's serialized arguments. Concatenate deltas to reconstruct the arguments JSON. */
  delta?: string | undefined;
  /** Identifier of the tool call this delta belongs to, once the model has assigned one. */
  id?: string | undefined;
  /** Name of the tool being called, once known. */
  name?: string | undefined;
}

/** Runtime validator for {@link AIChatStreamToolCallDelta}. */
export const aIChatStreamToolCallDeltaSchema = z.object({
  /** A chunk of the tool call's serialized arguments. Concatenate deltas to reconstruct the arguments JSON. */
  delta: z.string().optional().describe("A chunk of the tool call's serialized arguments. Concatenate deltas to reconstruct the arguments JSON."),
  /** Identifier of the tool call this delta belongs to, once the model has assigned one. */
  id: z.string().optional().describe("Identifier of the tool call this delta belongs to, once the model has assigned one."),
  /** Name of the tool being called, once known. */
  name: z.string().optional().describe("Name of the tool being called, once known."),
}).describe("Incremental tool-call data emitted as the model assembles a tool invocation (SSE `tool_call_delta` event).") satisfies z.ZodType<AIChatStreamToolCallDelta>;

/** The result of a server-executed tool, streamed back into the run (SSE `tool_result` event). */
export interface AIChatStreamToolResult {
  /** The tool's output, serialized as a string. */
  content?: string | undefined;
  /** ID of the tool call this result satisfies. */
  id?: string | undefined;
  /** Name of the tool that produced this result. */
  name?: string | undefined;
  /** How the tool call resolved, e.g. `"ok"` or `"error"`. */
  resolution?: string | undefined;
}

/** Runtime validator for {@link AIChatStreamToolResult}. */
export const aIChatStreamToolResultSchema = z.object({
  /** The tool's output, serialized as a string. */
  content: z.string().optional().describe("The tool's output, serialized as a string."),
  /** ID of the tool call this result satisfies. */
  id: z.string().optional().describe("ID of the tool call this result satisfies."),
  /** Name of the tool that produced this result. */
  name: z.string().optional().describe("Name of the tool that produced this result."),
  /** How the tool call resolved, e.g. `"ok"` or `"error"`. */
  resolution: z.string().optional().describe("How the tool call resolved, e.g. `\"ok\"` or `\"error\"`."),
}).describe("The result of a server-executed tool, streamed back into the run (SSE `tool_result` event).") satisfies z.ZodType<AIChatStreamToolResult>;

/** The result of an AI chat completion request. Returned by chat completion endpoints after the model finishes generating. */
export interface AICompletionResult {
  /** The reason the model stopped generating. Common values include `"stop"` (natural end), `"length"` (token limit reached), and `"tool_calls"` (the model invoked a tool). */
  finish_reason: string;
  /** The final assistant message produced by the completion. */
  message: AIMessage;
  /** The complete message history for the conversation, including all user, assistant, and tool messages in order. */
  messages: AIMessage[];
  /** Token consumption breakdown keyed by model ID. Each value is a map with `"input_tokens"` and `"output_tokens"` counts. `null` when usage data is unavailable. */
  token_usage?: Record<string, unknown> | undefined;
}

/** Runtime validator for {@link AICompletionResult}. */
export const aICompletionResultSchema = z.object({
  /** The reason the model stopped generating. Common values include `"stop"` (natural end), `"length"` (token limit reached), and `"tool_calls"` (the model invoked a tool). */
  finish_reason: z.string().describe("The reason the model stopped generating. Common values include `\"stop\"` (natural end), `\"length\"` (token limit reached), and `\"tool_calls\"` (the model invoked a tool)."),
  /** The final assistant message produced by the completion. */
  message: aIMessageSchema.describe("The final assistant message produced by the completion."),
  /** The complete message history for the conversation, including all user, assistant, and tool messages in order. */
  messages: z.array(aIMessageSchema).describe("The complete message history for the conversation, including all user, assistant, and tool messages in order."),
  /** Token consumption breakdown keyed by model ID. Each value is a map with `"input_tokens"` and `"output_tokens"` counts. `null` when usage data is unavailable. */
  token_usage: z.record(z.unknown()).optional().describe("Token consumption breakdown keyed by model ID. Each value is a map with `\"input_tokens\"` and `\"output_tokens\"` counts. `null` when usage data is unavailable."),
}).describe("The result of an AI chat completion request. Returned by chat completion endpoints after the model finishes generating.") satisfies z.ZodType<AICompletionResult>;

/** The result returned by an AI image generation or editing operation. Contains the generated image (as inline data or a URL) along with dimension, size, and usage metadata. */
export interface AIImageResult {
  /** Aspect ratio of the generated image, e.g. `"16:9"` or `"1:1"`. `null` when not reported by the provider. */
  aspect_ratio?: string | undefined;
  /** Height of the generated image in pixels. `null` when the provider does not report dimensions. */
  height?: number | undefined;
  /** The generated image encoded as a base64 string. Present when the provider returns inline image data. `null` when `image_url` is set instead. */
  image_data?: string | undefined;
  /** Resolution tier label for the image, e.g. `"1K"` or `"2K"`. `null` when the provider does not include a tier label. */
  image_size?: string | undefined;
  /** MIME type of the generated image, e.g. `"image/png"` or `"image/jpeg"`. `null` when the provider does not report a content type. */
  image_type?: string | undefined;
  /** Temporary URL pointing to the generated image hosted by the provider. Present when the provider returns a URL rather than inline data. `null` when `image_data` is set instead. */
  image_url?: string | undefined;
  /** Identifier of the model that produced the image, e.g. `"dall-e-3"` or `"imagen-3"`. */
  model: string;
  /** The prompt as rewritten by the provider before generation. Some providers (e.g. DALL-E 3) automatically expand or safety-check the original prompt. `null` when the provider does not revise prompts. */
  revised_prompt?: string | undefined;
  /** Canonical size string as returned by the provider, e.g. `"1024x1024"`. `null` when not reported. */
  size?: string | undefined;
  /** Provider-reported token and compute usage for the request. Structure varies by provider. `null` when usage data is unavailable. */
  usage?: Record<string, unknown> | undefined;
  /** Width of the generated image in pixels. `null` when the provider does not report dimensions. */
  width?: number | undefined;
}

/** Runtime validator for {@link AIImageResult}. */
export const aIImageResultSchema = z.object({
  /** Aspect ratio of the generated image, e.g. `"16:9"` or `"1:1"`. `null` when not reported by the provider. */
  aspect_ratio: z.string().optional().describe("Aspect ratio of the generated image, e.g. `\"16:9\"` or `\"1:1\"`. `null` when not reported by the provider."),
  /** Height of the generated image in pixels. `null` when the provider does not report dimensions. */
  height: z.number().int().optional().describe("Height of the generated image in pixels. `null` when the provider does not report dimensions."),
  /** The generated image encoded as a base64 string. Present when the provider returns inline image data. `null` when `image_url` is set instead. */
  image_data: z.string().optional().describe("The generated image encoded as a base64 string. Present when the provider returns inline image data. `null` when `image_url` is set instead."),
  /** Resolution tier label for the image, e.g. `"1K"` or `"2K"`. `null` when the provider does not include a tier label. */
  image_size: z.string().optional().describe("Resolution tier label for the image, e.g. `\"1K\"` or `\"2K\"`. `null` when the provider does not include a tier label."),
  /** MIME type of the generated image, e.g. `"image/png"` or `"image/jpeg"`. `null` when the provider does not report a content type. */
  image_type: z.string().optional().describe("MIME type of the generated image, e.g. `\"image/png\"` or `\"image/jpeg\"`. `null` when the provider does not report a content type."),
  /** Temporary URL pointing to the generated image hosted by the provider. Present when the provider returns a URL rather than inline data. `null` when `image_data` is set instead. */
  image_url: z.string().optional().describe("Temporary URL pointing to the generated image hosted by the provider. Present when the provider returns a URL rather than inline data. `null` when `image_data` is set instead."),
  /** Identifier of the model that produced the image, e.g. `"dall-e-3"` or `"imagen-3"`. */
  model: z.string().describe("Identifier of the model that produced the image, e.g. `\"dall-e-3\"` or `\"imagen-3\"`."),
  /** The prompt as rewritten by the provider before generation. Some providers (e.g. DALL-E 3) automatically expand or safety-check the original prompt. `null` when the provider does not revise prompts. */
  revised_prompt: z.string().optional().describe("The prompt as rewritten by the provider before generation. Some providers (e.g. DALL-E 3) automatically expand or safety-check the original prompt. `null` when the provider does not revise prompts."),
  /** Canonical size string as returned by the provider, e.g. `"1024x1024"`. `null` when not reported. */
  size: z.string().optional().describe("Canonical size string as returned by the provider, e.g. `\"1024x1024\"`. `null` when not reported."),
  /** Provider-reported token and compute usage for the request. Structure varies by provider. `null` when usage data is unavailable. */
  usage: z.record(z.unknown()).optional().describe("Provider-reported token and compute usage for the request. Structure varies by provider. `null` when usage data is unavailable."),
  /** Width of the generated image in pixels. `null` when the provider does not report dimensions. */
  width: z.number().int().optional().describe("Width of the generated image in pixels. `null` when the provider does not report dimensions."),
}).describe("The result returned by an AI image generation or editing operation. Contains the generated image (as inline data or a URL) along with dimension, size, and usage metadata.") satisfies z.ZodType<AIImageResult>;
