// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6f9b2344ac6b

import { z } from "zod";

/** A single execution of an automation triggered by a platform event or direct invocation. Captures the run's status, input payload, and final result. */
export interface AutomationRun {
  /** ID of the app that owns this automation run (`dap_...`). */
  app: string;
  /** ID of the automation that was executed (`aut_...`). */
  automation: string;
  /** When the automation run was created (ISO 8601). */
  created_at?: string | undefined;
  /** ID of the platform event that triggered this run. `null` for directly invoked automations. */
  event_id?: string | undefined;
  /** Automation run ID (`atr_...`). */
  id: string;
  /** The input event payload that triggered this run. Structure varies by automation type. Defaults to an empty object if no payload was provided. */
  payload?: Record<string, unknown> | undefined;
  /** The output produced after the automation finished executing. Contains workflow-defined keys alongside any returned output. `null` if the run has not yet completed. */
  result?: Record<string, unknown> | undefined;
  /** Current execution status of the run. One of `"pending"` (queued, not yet started), `"running"` (actively executing), `"completed"` (finished successfully), `"failed"` (finished with an error), or `"cancelled"` (stopped before completion). */
  status: string;
  /** ID of the team that owns this run (`tea_...`). `null` if the run is owned by a user rather than a team. */
  team?: string | undefined;
  /** When the automation run record was last updated (ISO 8601). */
  updated_at?: string | undefined;
  /** ID of the user that owns this run (`usr_...`). `null` if the run is owned by a team rather than a user. */
  user?: string | undefined;
}

/** Runtime validator for {@link AutomationRun}. */
export const automationRunSchema = z.object({
  /** ID of the app that owns this automation run (`dap_...`). */
  app: z.string().describe("ID of the app that owns this automation run (`dap_...`)."),
  /** ID of the automation that was executed (`aut_...`). */
  automation: z.string().describe("ID of the automation that was executed (`aut_...`)."),
  /** When the automation run was created (ISO 8601). */
  created_at: z.string().optional().describe("When the automation run was created (ISO 8601)."),
  /** ID of the platform event that triggered this run. `null` for directly invoked automations. */
  event_id: z.string().optional().describe("ID of the platform event that triggered this run. `null` for directly invoked automations."),
  /** Automation run ID (`atr_...`). */
  id: z.string().describe("Automation run ID (`atr_...`)."),
  /** The input event payload that triggered this run. Structure varies by automation type. Defaults to an empty object if no payload was provided. */
  payload: z.record(z.unknown()).optional().describe("The input event payload that triggered this run. Structure varies by automation type. Defaults to an empty object if no payload was provided."),
  /** The output produced after the automation finished executing. Contains workflow-defined keys alongside any returned output. `null` if the run has not yet completed. */
  result: z.record(z.unknown()).optional().describe("The output produced after the automation finished executing. Contains workflow-defined keys alongside any returned output. `null` if the run has not yet completed."),
  /** Current execution status of the run. One of `"pending"` (queued, not yet started), `"running"` (actively executing), `"completed"` (finished successfully), `"failed"` (finished with an error), or `"cancelled"` (stopped before completion). */
  status: z.string().describe("Current execution status of the run. One of `\"pending\"` (queued, not yet started), `\"running\"` (actively executing), `\"completed\"` (finished successfully), `\"failed\"` (finished with an error), or `\"cancelled\"` (stopped before completion)."),
  /** ID of the team that owns this run (`tea_...`). `null` if the run is owned by a user rather than a team. */
  team: z.string().optional().describe("ID of the team that owns this run (`tea_...`). `null` if the run is owned by a user rather than a team."),
  /** When the automation run record was last updated (ISO 8601). */
  updated_at: z.string().optional().describe("When the automation run record was last updated (ISO 8601)."),
  /** ID of the user that owns this run (`usr_...`). `null` if the run is owned by a team rather than a user. */
  user: z.string().optional().describe("ID of the user that owns this run (`usr_...`). `null` if the run is owned by a team rather than a user."),
}).describe("A single execution of an automation triggered by a platform event or direct invocation. Captures the run's status, input payload, and final result.") satisfies z.ZodType<AutomationRun>;
