// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 772cd6af62e3

import { z } from "zod";
import { agentSchema, messageSchema } from "./common.js";
import { teamSchema } from "./teams.js";
import { threadSchema } from "./threads.js";
import { userSchema } from "./users.js";
import type { Agent, Message } from "./common.js";
import type { Team } from "./teams.js";
import type { Thread } from "./threads.js";
import type { User } from "./users.js";

/** A participant in a chat thread, which may be either a human user or an AI agent. Exactly one of `user` or `agent` is populated depending on `type`. */
export interface ChatMember {
  /** Full agent object for this member. Populated when `type` is `"agent"`; `null` for user members. */
  agent?: Agent | undefined;
  /** Role of this member within the thread. Common values are `"owner"` and `"member"`. `null` when the membership type is not applicable. */
  membership_type?: string | undefined;
  /** Kind of participant. One of `"user"` (a human user) or `"agent"` (an AI agent). */
  type: string;
  /** Full user object for this member. Populated when `type` is `"user"`; `null` for agent members. */
  user?: User | undefined;
}

/** Runtime validator for {@link ChatMember}. */
export const chatMemberSchema = z.object({
  /** Full agent object for this member. Populated when `type` is `"agent"`; `null` for user members. */
  agent: agentSchema.optional().describe("Full agent object for this member. Populated when `type` is `\"agent\"`; `null` for user members."),
  /** Role of this member within the thread. Common values are `"owner"` and `"member"`. `null` when the membership type is not applicable. */
  membership_type: z.string().optional().describe("Role of this member within the thread. Common values are `\"owner\"` and `\"member\"`. `null` when the membership type is not applicable."),
  /** Kind of participant. One of `"user"` (a human user) or `"agent"` (an AI agent). */
  type: z.string().describe("Kind of participant. One of `\"user\"` (a human user) or `\"agent\"` (an AI agent)."),
  /** Full user object for this member. Populated when `type` is `"user"`; `null` for agent members. */
  user: userSchema.optional().describe("Full user object for this member. Populated when `type` is `\"user\"`; `null` for agent members."),
}).describe("A participant in a chat thread, which may be either a human user or an AI agent. Exactly one of `user` or `agent` is populated depending on `type`.") satisfies z.ZodType<ChatMember>;

/** A point-in-time snapshot of a chat room's state, including its loaded messages, member roster, and pagination cursors. Returned when loading or refreshing a thread's message list. */
export interface ChatRoomModel {
  /** Opaque cursor to pass when fetching messages newer than those in this snapshot. `null` when this snapshot already reflects the latest messages. */
  after_cursor?: string | undefined;
  /** The agent associated with this chat room. `null` when no agent is attached. */
  agent?: Agent | undefined;
  /** Opaque cursor to pass when fetching messages older than those in this snapshot. `null` when the beginning of the thread history has been reached. */
  before_cursor?: string | undefined;
  /** Whether this thread is ephemeral. Transient threads are not retained in long-term storage and may be deleted when the session ends. */
  is_transient: boolean;
  /** All active members of the chat room, including both human users and agents. */
  members: ChatMember[];
  /** The page of messages currently loaded for the thread, ordered chronologically. Use `before_cursor` or `after_cursor` to page through additional history. */
  messages: Message[];
  /** Number of messages that were added to the snapshot in the most recent incremental update. `null` on the initial load. */
  messages_loaded_on_last_update?: number | undefined;
  /** The team that owns this thread. `null` for threads scoped to an individual user rather than a team. */
  team?: Team | undefined;
  /** The parent thread whose message history and membership this snapshot represents. */
  thread: Thread;
}

/** Runtime validator for {@link ChatRoomModel}. */
export const chatRoomModelSchema = z.object({
  /** Opaque cursor to pass when fetching messages newer than those in this snapshot. `null` when this snapshot already reflects the latest messages. */
  after_cursor: z.string().optional().describe("Opaque cursor to pass when fetching messages newer than those in this snapshot. `null` when this snapshot already reflects the latest messages."),
  /** The agent associated with this chat room. `null` when no agent is attached. */
  agent: agentSchema.optional().describe("The agent associated with this chat room. `null` when no agent is attached."),
  /** Opaque cursor to pass when fetching messages older than those in this snapshot. `null` when the beginning of the thread history has been reached. */
  before_cursor: z.string().optional().describe("Opaque cursor to pass when fetching messages older than those in this snapshot. `null` when the beginning of the thread history has been reached."),
  /** Whether this thread is ephemeral. Transient threads are not retained in long-term storage and may be deleted when the session ends. */
  is_transient: z.boolean().describe("Whether this thread is ephemeral. Transient threads are not retained in long-term storage and may be deleted when the session ends."),
  /** All active members of the chat room, including both human users and agents. */
  members: z.array(chatMemberSchema).describe("All active members of the chat room, including both human users and agents."),
  /** The page of messages currently loaded for the thread, ordered chronologically. Use `before_cursor` or `after_cursor` to page through additional history. */
  messages: z.array(messageSchema).describe("The page of messages currently loaded for the thread, ordered chronologically. Use `before_cursor` or `after_cursor` to page through additional history."),
  /** Number of messages that were added to the snapshot in the most recent incremental update. `null` on the initial load. */
  messages_loaded_on_last_update: z.number().int().optional().describe("Number of messages that were added to the snapshot in the most recent incremental update. `null` on the initial load."),
  /** The team that owns this thread. `null` for threads scoped to an individual user rather than a team. */
  team: teamSchema.optional().describe("The team that owns this thread. `null` for threads scoped to an individual user rather than a team."),
  /** The parent thread whose message history and membership this snapshot represents. */
  thread: threadSchema.describe("The parent thread whose message history and membership this snapshot represents."),
}).describe("A point-in-time snapshot of a chat room's state, including its loaded messages, member roster, and pagination cursors. Returned when loading or refreshing a thread's message list.") satisfies z.ZodType<ChatRoomModel>;

/** Response returned after forking a chat thread. Contains the new thread, its initial chat-room snapshot, and the owning team when applicable. */
export interface ChatForkThreadResponse {
  /** Initial chat-room render snapshot for the forked thread, including members and loaded messages. `null` for transient threads whose room model is suppressed. */
  chat_model?: ChatRoomModel | undefined;
  /** Team that owns the forked thread. Present only when the original thread was team-scoped; `null` for personal threads. */
  team?: Team | undefined;
  /** The newly-created thread produced by the fork operation. */
  thread: Thread;
}

/** Runtime validator for {@link ChatForkThreadResponse}. */
export const chatForkThreadResponseSchema = z.object({
  /** Initial chat-room render snapshot for the forked thread, including members and loaded messages. `null` for transient threads whose room model is suppressed. */
  chat_model: chatRoomModelSchema.optional().describe("Initial chat-room render snapshot for the forked thread, including members and loaded messages. `null` for transient threads whose room model is suppressed."),
  /** Team that owns the forked thread. Present only when the original thread was team-scoped; `null` for personal threads. */
  team: teamSchema.optional().describe("Team that owns the forked thread. Present only when the original thread was team-scoped; `null` for personal threads."),
  /** The newly-created thread produced by the fork operation. */
  thread: threadSchema.describe("The newly-created thread produced by the fork operation."),
}).describe("Response returned after forking a chat thread. Contains the new thread, its initial chat-room snapshot, and the owning team when applicable.") satisfies z.ZodType<ChatForkThreadResponse>;

/** Response returned after loading an additional page of chat messages. Contains a refreshed chat-room snapshot with the newly-fetched messages merged in. */
export interface ChatLoadMoreMessagesResponse {
  /** Updated chat-room snapshot for the thread, incorporating the newly-loaded page of messages alongside any previously loaded messages. */
  data: ChatRoomModel;
}

/** Runtime validator for {@link ChatLoadMoreMessagesResponse}. */
export const chatLoadMoreMessagesResponseSchema = z.object({
  /** Updated chat-room snapshot for the thread, incorporating the newly-loaded page of messages alongside any previously loaded messages. */
  data: chatRoomModelSchema.describe("Updated chat-room snapshot for the thread, incorporating the newly-loaded page of messages alongside any previously loaded messages."),
}).describe("Response returned after loading an additional page of chat messages. Contains a refreshed chat-room snapshot with the newly-fetched messages merged in.") satisfies z.ZodType<ChatLoadMoreMessagesResponse>;

/** Response returned after marking a chat thread as read. Confirms that the read marker was successfully recorded for the authenticated user. */
export interface ChatMarkThreadReadResponse {
  /** Indicates whether the read marker was successfully applied. Always `true` on success; errors are returned as channel error replies rather than a `false` value here. */
  success: boolean;
}

/** Runtime validator for {@link ChatMarkThreadReadResponse}. */
export const chatMarkThreadReadResponseSchema = z.object({
  /** Indicates whether the read marker was successfully applied. Always `true` on success; errors are returned as channel error replies rather than a `false` value here. */
  success: z.boolean().describe("Indicates whether the read marker was successfully applied. Always `true` on success; errors are returned as channel error replies rather than a `false` value here."),
}).describe("Response returned after marking a chat thread as read. Confirms that the read marker was successfully recorded for the authenticated user.") satisfies z.ZodType<ChatMarkThreadReadResponse>;

/** Response returned when listing the messages of a joined chat thread. Contains the set of messages currently loaded for the thread. */
export interface ChatMessageListResponse {
  /** Ordered array of message objects currently loaded for the thread, from oldest to newest. Use the `load_more_messages` channel message to fetch earlier pages. */
  messages: Message[];
}

/** Runtime validator for {@link ChatMessageListResponse}. */
export const chatMessageListResponseSchema = z.object({
  /** Ordered array of message objects currently loaded for the thread, from oldest to newest. Use the `load_more_messages` channel message to fetch earlier pages. */
  messages: z.array(messageSchema).describe("Ordered array of message objects currently loaded for the thread, from oldest to newest. Use the `load_more_messages` channel message to fetch earlier pages."),
}).describe("Response returned when listing the messages of a joined chat thread. Contains the set of messages currently loaded for the thread.") satisfies z.ZodType<ChatMessageListResponse>;

/** Response returned after successfully posting a message to a chat thread. Contains the persisted message object echoed back to the sender. */
export interface ChatPostMessageResponse {
  /** The message that was created and stored. Contains the full message object including its assigned ID, author, content, and timestamps. */
  message: Message;
}

/** Runtime validator for {@link ChatPostMessageResponse}. */
export const chatPostMessageResponseSchema = z.object({
  /** The message that was created and stored. Contains the full message object including its assigned ID, author, content, and timestamps. */
  message: messageSchema.describe("The message that was created and stored. Contains the full message object including its assigned ID, author, content, and timestamps."),
}).describe("Response returned after successfully posting a message to a chat thread. Contains the persisted message object echoed back to the sender.") satisfies z.ZodType<ChatPostMessageResponse>;
