// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: cb65d3eacf8c

import { z } from "zod";
import { imageSourceSchema } from "./image.js";
import { userSchema } from "./users.js";

/** API schema for a single ACL grant entry. */
export const aclGrantSchema = z.object({
  actions: z.array(z.string()), // List of allowed actions (e.g. read, write)
  principal: z.string().optional(), // Principal identifier (UUID for user/team/org/agent_user, role name for org_role, omit for everyone)
  principal_type: z.string(), // Principal type: user, team, org, org_role, agent, or everyone
});
export type AclGrant = z.infer<typeof aclGrantSchema>;

/** API schema for identifying a principal to remove from an ACL. */
export const aclRemoveTargetSchema = z.object({
  principal: z.string().optional(), // Principal identifier to remove (omit for everyone)
  principal_type: z.string(), // Principal type to remove
});
export type AclRemoveTarget = z.infer<typeof aclRemoveTargetSchema>;

/** Reusable API schema for access control lists.

Supports two modes (mutually exclusive):

**Replace mode** — send `grants` to replace all entries:

    {"grants": [{"principal_type": "user", "principal": "...", "actions": ["read"]}]}

Use `{"grants": []}` to clear all entries.

**Patch mode** — send `add` and/or `remove`:

    {"add": [...grants...], "remove": [{"principal_type": "user", "principal": "..."}]}

Cannot mix `grants` with `add`/`remove`.
 */
export const aclSchema = z.object({
  add: z.array(aclGrantSchema).optional(), // Patch mode: grants to add or merge into existing
  grants: z.array(aclGrantSchema).optional(), // Replace mode: full list of grants (replaces all existing). Use [] to clear.
  remove: z.array(aclRemoveTargetSchema).optional(), // Patch mode: principals to remove from existing
});
export type Acl = z.infer<typeof aclSchema>;

/** Schema for a message actor (user or agent).

Actors represent the entity that sent a message.
Maps to the actor format from MessageActorHelper.build_actor/1.
 */
export const actorSchema = z.object({
  alias: z.string().optional(), // Actor alias/handle
  id: z.string().optional(), // Actor ID (format: user-xxx or agent-xxx)
  name: z.string().optional(), // Actor display name
  profile_picture: imageSourceSchema.optional(), // Profile picture
});
export type Actor = z.infer<typeof actorSchema>;

/** API schema for background worker status on a routine run. */
export const workerStatusSchema = z.object({
  attempt: z.number().int(), // Current attempt number (0 = not yet attempted)
  max_attempts: z.number().int(), // Maximum allowed attempts
  status: z.string(), // Worker state: queued, executing, retrying, completed, discarded, or cancelled
});
export type WorkerStatus = z.infer<typeof workerStatusSchema>;

/** API schema for a media variant. */
export const mediaVariantSchema = z.object({
  content_type: z.string().optional(), // File content type
  created_at: z.string().optional(), // Creation timestamp
  file: z.string().optional(), // Storage file
  filename: z.string().optional(), // Original filename
  height: z.number().int().optional(), // Height in pixels
  id: z.string(), // Variant ID
  image_source: imageSourceSchema.optional(), // Image source metadata
  updated_at: z.string().optional(), // Last update timestamp
  url: z.string().optional(), // Signed download URL
  variant_key: z.string().optional(), // Variant key (original, thumbnail, etc)
  width: z.number().int().optional(), // Width in pixels
});
export type MediaVariant = z.infer<typeof mediaVariantSchema>;

/** Schema for a message attachment.

Attachments can be of various types (file, scraped_link, artifact, task, media, action).
Fields present depend on the attachment type.
Maps to format_attachments_for_client/1 output.
 */
export const attachmentSchema = z.object({
  content_type: z.string().optional(), // MIME content type (file, artifact, media types)
  description: z.string().optional(), // Description (scraped_link, artifact, task types)
  filename: z.string().optional(), // File name (file, artifact, media types)
  height: z.number().int().optional(), // Media height (media type)
  id: z.string(), // Attachment ID
  image_height: z.number().int().optional(), // Preview image height (scraped_link type)
  image_source: imageSourceSchema.optional(), // Image metadata (file, scraped_link, artifact, media types)
  image_url: z.string().optional(), // Preview image URL (scraped_link type)
  image_width: z.number().int().optional(), // Preview image width (scraped_link type)
  media_type: z.string().optional(), // Media type (media type)
  name: z.string().optional(), // Media name (media type)
  object: z.record(z.unknown()).optional(), // Embedded object (task, action types)
  title: z.string().optional(), // Title (scraped_link, artifact, task types)
  type: z.string(), // Attachment type: file, scraped_link, artifact, task, media, action
  url: z.string().optional(), // URL to the resource (file, scraped_link, artifact, media types)
  variants: z.array(mediaVariantSchema).optional(), // Media variants (media type)
  version: z.number().int().optional(), // Artifact version number (artifact type)
  width: z.number().int().optional(), // Media width (media type)
});
export type Attachment = z.infer<typeof attachmentSchema>;

/** API schema for authentication token responses. */
export const authTokensSchema = z.object({
  expires_in: z.number().int(), // Token TTL in seconds
  metadata: z.record(z.unknown()).optional(), // Additional metadata (e.g., onboarding_job_id)
  refresh_token: z.string(), // Refresh token
  token: z.string(), // Access token (JWT)
  token_type: z.string(), // Token type (Bearer)
  user: userSchema, // Authenticated user
});
export type AuthTokens = z.infer<typeof authTokensSchema>;

/** An individual tool within a builtin tool catalog entry. */
export const builtinToolSchema = z.object({
  description: z.string().optional(), // Tool description
  name: z.string(), // Tool name
});
export type BuiltinTool = z.infer<typeof builtinToolSchema>;

/** A builtin tool catalog entry describing an available tool category. */
export const builtinToolCatalogEntrySchema = z.object({
  config_schema: z.record(z.unknown()).optional(), // JSON schema for tool configuration
  description: z.string().optional(), // Tool description
  instruction: z.string().optional(), // Tool instruction
  key: z.string(), // Unique tool key
  label: z.string().optional(), // Display label
  providers: z.array(z.string()).optional(), // Supported providers
  requires_integration: z.boolean().optional(), // Whether an integration is required
  server_tool_type: z.string().optional(), // Server tool type identifier
  tools: z.array(builtinToolSchema).optional(), // List of individual tools
});
export type BuiltinToolCatalogEntry = z.infer<typeof builtinToolCatalogEntrySchema>;

/** Result of executing a command on an agent computer. */
export const computerExecResultSchema = z.object({
  exit_code: z.number().int().optional(), // Process exit code
  output: z.string().optional(), // Command output
});
export type ComputerExecResult = z.infer<typeof computerExecResultSchema>;

/** API schema for a custom object. */
export const customObjectSchema = z.object({
  created_at: z.string().optional(), // Created timestamp
  fields: z.record(z.unknown()).optional(), // Object field values
  id: z.string(), // Public ID (cobj_...)
  org: z.string().optional(), // Organization
  row_key: z.string().optional(), // Row key
  sandbox: z.string().optional(), // Sandbox identifier
  schema_type: z.string().optional(), // Schema type (lookup_key)
  team: z.string().optional(), // Owning team
  updated_at: z.string().optional(), // Updated timestamp
  user: z.string().optional(), // Owning user
  version: z.number().int().optional(), // Aggregate version for OCC
});
export type CustomObject = z.infer<typeof customObjectSchema>;

/** API schema for OAuth device authorization responses. */
export const deviceAuthorizationResponseSchema = z.object({
  device_code: z.string(), // Device verification code
  expires_in: z.number().int(), // TTL in seconds
  interval: z.number().int(), // Polling interval in seconds
  user_code: z.string(), // User-facing verification code
  verification_uri: z.string(), // Base verification URI
  verification_uri_complete: z.string(), // Full verification URI with code
});
export type DeviceAuthorizationResponse = z.infer<typeof deviceAuthorizationResponseSchema>;

/** API schema for OAuth device authorization approval and denial responses. */
export const deviceAuthorizationStatusResponseSchema = z.object({
  status: z.string(), // Authorization status (approved or denied)
});
export type DeviceAuthorizationStatusResponse = z.infer<typeof deviceAuthorizationStatusResponseSchema>;

/** API schema for an installation. */
export const installationSchema = z.object({
  agent: z.string().optional(), // Owning agent
  config: z.record(z.unknown()).optional(), // Configuration
  created_at: z.string().optional(), // Creation timestamp
  id: z.string(), // Installation ID (cin_...)
  kind: z.string().optional(), // Installation kind
  shared_integration: z.string().optional(), // Bound shared integration
  state: z.string().optional(), // Installation state
  status_payload: z.record(z.unknown()).optional(), // Status payload
  updated_at: z.string().optional(), // Last update timestamp
});
export type Installation = z.infer<typeof installationSchema>;

/** API schema for an installation kind. */
export const installationKindSchema = z.object({
  accepts_sources: z.boolean().optional(), // Whether this kind accepts sources
  category: z.string().optional(), // Category
  config_schema: z.record(z.unknown()).optional(), // JSON schema for configuration
  description: z.string().optional(), // Description
  kind: z.string(), // Installation kind identifier
  label: z.string().optional(), // Display label
  provider: z.string().optional(), // Integration provider
  requires_integration: z.boolean().optional(), // Whether this kind requires an integration
});
export type InstallationKind = z.infer<typeof installationKindSchema>;

/** List response for installation kinds. */
export const installationKindListResponseSchema = z.object({
  data: z.array(installationKindSchema), // List of installation kinds
});
export type InstallationKindListResponse = z.infer<typeof installationKindListResponseSchema>;

/** List response for installations. */
export const installationListResponseSchema = z.object({
  data: z.array(installationSchema), // List of installations
});
export type InstallationListResponse = z.infer<typeof installationListResponseSchema>;

/** API schema for an installation source. */
export const installationSourceSchema = z.object({
  agent: z.string().optional(), // Owning agent
  context_installation: z.string().optional(), // Installation ID
  created_at: z.string().optional(), // Creation timestamp
  id: z.string(), // Source ID (cso_...)
  metadata: z.record(z.unknown()).optional(), // Arbitrary metadata
  parent_source: z.string().optional(), // Parent source ID
  payload: z.record(z.unknown()).optional(), // Source payload
  state: z.string().optional(), // Source state
  team: z.string().optional(), // Team ID
  thread: z.string().optional(), // Thread ID
  type: z.string().optional(), // Source type
  updated_at: z.string().optional(), // Last update timestamp
  user: z.string().optional(), // User ID
});
export type InstallationSource = z.infer<typeof installationSourceSchema>;

/** List response for installation sources. */
export const installationSourceListResponseSchema = z.object({
  data: z.array(installationSourceSchema), // List of installation sources
});
export type InstallationSourceListResponse = z.infer<typeof installationSourceListResponseSchema>;

/** Schema for a key-value storage entry.

Maps exactly to render_entry/1 output in ApiStorageController.
 */
export const keyValueStorageEntrySchema = z.object({
  created_at: z.string().optional(), // Creation timestamp
  key: z.string(), // Storage key
  updated_at: z.string().optional(), // Last update timestamp
  user: z.string(), // User
  value: z.string(), // Stored value
});
export type KeyValueStorageEntry = z.infer<typeof keyValueStorageEntrySchema>;

/** Schema for a key-value storage entry, optionally enriched with a summary of
the owning user.

Used by the dual-mode list endpoint: user-JWT callers omit the user_email /
user_name fields (they know who they are); developer / S2S callers populate
them so the portal can render an owner column without a per-row lookup.
 */
export const keyValueStorageEntryWithUserSchema = z.object({
  created_at: z.string(), // Creation timestamp
  key: z.string(), // Storage key
  updated_at: z.string(), // Last update timestamp
  user: z.string(), // User ID
  user_email: z.string().optional(), // User email (developer / S2S only)
  user_name: z.string().optional(), // User display name (developer / S2S only)
  value: z.string(), // Stored value
});
export type KeyValueStorageEntryWithUser = z.infer<typeof keyValueStorageEntryWithUserSchema>;

/** Response envelope for the dual-mode key-value list endpoint.

User-JWT callers receive `%{data: [...]}` (no pagination fields).
Developer / S2S callers receive `%{data: [...]}` plus pagination metadata.
 */
export const keyValueStorageEntryPageSchema = z.object({
  data: z.array(keyValueStorageEntryWithUserSchema), // Storage entries on this page
  has_next: z.boolean().optional(), // Whether a next page exists (developer / S2S only)
  has_prev: z.boolean().optional(), // Whether a previous page exists (developer / S2S only)
  page: z.number().int().optional(), // Current page number (developer / S2S only)
  page_size: z.number().int().optional(), // Results per page (developer / S2S only)
  total_entries: z.number().int().optional(), // Total entries matching the filters (developer / S2S only)
  total_pages: z.number().int().optional(), // Total number of pages (developer / S2S only)
});
export type KeyValueStorageEntryPage = z.infer<typeof keyValueStorageEntryPageSchema>;

/** Schema for inline message reactions.

This is the compact format used in Message.reactions[], which differs from
the full Reaction schema used in standalone reaction endpoints.
Maps to format_reactions_for_client/1 output.
 */
export const messageReactionSchema = z.object({
  payload: z.record(z.unknown()).optional(), // Reaction payload (e.g., {emoji: '👍'})
  type: z.string(), // Reaction type (e.g., emoji_reaction)
  user: z.string().optional(), // User who added the reaction
});
export type MessageReaction = z.infer<typeof messageReactionSchema>;

/** API schema for a chat message. */
export const messageSchema = z.object({
  actors: z.array(actorSchema).optional(), // Message actors
  agent: z.string().optional(), // Agent if sent by an agent user
  attachments: z.array(attachmentSchema).optional(), // Message attachments
  branched_thread: z.string().optional(), // Branched thread (if message spawned a thread)
  content: z.string().optional(), // Message content
  created_at: z.string().optional(), // Creation timestamp
  has_replies: z.boolean().optional(), // Whether message has replies
  id: z.string(), // Message ID (msg_...)
  idempotency_key: z.string().optional(), // Client-provided idempotency key
  legacy_agent: z.string().optional(), // Legacy agent if sent by legacy chat agent
  metadata: z.record(z.unknown()).optional(), // Message metadata
  org: z.string().optional(), // Organization
  reactions: z.array(messageReactionSchema).optional(), // Message reactions
  rendering_mode: z.string().optional(), // Rendering mode hint
  replies: z.array(z.record(z.unknown())).optional(), // Inline replies (if loaded)
  replies_after_cursor: z.string().optional(), // Cursor for replies pagination
  replies_before_cursor: z.string().optional(), // Cursor for replies pagination
  reply_count: z.number().int().optional(), // Number of replies
  reply_to: z.record(z.unknown()).optional(), // Parent message object (if loaded)
  sandbox: z.string().optional(), // Sandbox identifier
  team: z.string().optional(), // Team
  thread: z.string().optional(), // Parent thread
  user: z.string().optional(), // Author user (public ID or expanded object when loaded)
});
export type Message = z.infer<typeof messageSchema>;

/** API schema for OAuth token endpoint responses. */
export const oAuthTokenResponseSchema = z.object({
  access_token: z.string(), // OAuth access token
  expires_in: z.number().int(), // Token TTL in seconds
  refresh_token: z.string().optional(), // OAuth refresh token
  scope: z.string().optional(), // Granted scopes (space-separated)
  token_type: z.string(), // Token type (Bearer)
  user: userSchema.optional(), // Authenticated user
});
export type OAuthTokenResponse = z.infer<typeof oAuthTokenResponseSchema>;

/** Schema for paginated message replies response.

Used by message replies list endpoints.
Note: This response is NOT wrapped in a "data" field.
 */
export const paginatedRepliesSchema = z.object({
  after_cursor: z.string().optional(), // Cursor for fetching items after this point
  before_cursor: z.string().optional(), // Cursor for fetching items before this point
  has_more: z.boolean().optional(), // Whether more replies exist beyond the current page
  replies: z.array(messageSchema), // List of reply message objects
  total_count: z.number().int().optional(), // Total number of replies
});
export type PaginatedReplies = z.infer<typeof paginatedRepliesSchema>;

/** A routine preset with its metadata. */
export const routinePresetSchema = z.object({
  config: z.record(z.unknown()).optional(), // Default configuration
  description: z.string().optional(), // Preset description
  event_type: z.string().optional(), // Event type
  label: z.string().optional(), // Display label
  name: z.string(), // Preset name
});
export type RoutinePreset = z.infer<typeof routinePresetSchema>;

/** Schema for config validation result.
 */
export const validationResultSchema = z.object({
  errors: z.array(z.string()).optional(), // List of validation errors
  valid: z.boolean(), // Whether the config is valid
  warnings: z.array(z.string()).optional(), // Optional warnings emitted during validation
});
export type ValidationResult = z.infer<typeof validationResultSchema>;

/** API schema for a working memory entry. */
export const workingMemoryEntrySchema = z.object({
  agent: z.string().optional(), // Owning agent
  created_at: z.string().optional(), // Creation timestamp
  expires_at: z.string().optional(), // Expiration timestamp
  id: z.string(), // Memory entry ID (amm_...)
  key: z.string().optional(), // Memory key
  updated_at: z.string().optional(), // Last update timestamp
  value: z.string().optional(), // Memory value
});
export type WorkingMemoryEntry = z.infer<typeof workingMemoryEntrySchema>;

/** Paginated list response for working memory entries. */
export const workingMemoryEntryListResponseSchema = z.object({
  data: z.array(workingMemoryEntrySchema), // List of working memory entries
  has_next: z.boolean().optional(), // Whether a next page exists
  has_prev: z.boolean().optional(), // Whether a previous page exists
  page: z.number().int().optional(), // Current page number
  page_size: z.number().int().optional(), // Results per page
  total_entries: z.number().int().optional(), // Total number of entries
  total_pages: z.number().int().optional(), // Total number of pages
});
export type WorkingMemoryEntryListResponse = z.infer<typeof workingMemoryEntryListResponseSchema>;
