// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 5f72b9dfcbcb

import { z } from "zod";

/** A single immutable snapshot of a config's content, created each time the config is saved. */
export interface ConfigVersion {
  /** Human-readable summary of what changed in this version, as provided by the author. `null` if no description was supplied. */
  change_description?: string | undefined;
  /** SHA-256 digest of the raw config content encoded as `sha256:<hex>`. Uses the same algorithm as the CLI `computeContentHash` helper. `null` for versions created before this field was introduced. */
  content_hash?: string | undefined;
  /** When this config version was created (ISO 8601). */
  created_at?: string | undefined;
  /** Arbitrary structured metadata stored alongside this version. `null` when no extra data was provided. */
  data?: Record<string, unknown> | undefined;
  /** Config version ID (`cfv_...`). */
  id: string;
  /** Organization ID (`org_...`) that owns this config version. `null` for personal configs. */
  org?: string | undefined;
  /** Sandbox ID (`sbx_...`) this version was saved under. `null` for production configs. */
  sandbox?: string | undefined;
  /** Monotonically increasing integer identifying this version within the config. Starts at 1. */
  version_number: number;
}

/** Runtime validator for {@link ConfigVersion}. */
export const configVersionSchema = z.object({
  /** Human-readable summary of what changed in this version, as provided by the author. `null` if no description was supplied. */
  change_description: z.string().optional().describe("Human-readable summary of what changed in this version, as provided by the author. `null` if no description was supplied."),
  /** SHA-256 digest of the raw config content encoded as `sha256:<hex>`. Uses the same algorithm as the CLI `computeContentHash` helper. `null` for versions created before this field was introduced. */
  content_hash: z.string().optional().describe("SHA-256 digest of the raw config content encoded as `sha256:<hex>`. Uses the same algorithm as the CLI `computeContentHash` helper. `null` for versions created before this field was introduced."),
  /** When this config version was created (ISO 8601). */
  created_at: z.string().optional().describe("When this config version was created (ISO 8601)."),
  /** Arbitrary structured metadata stored alongside this version. `null` when no extra data was provided. */
  data: z.record(z.unknown()).optional().describe("Arbitrary structured metadata stored alongside this version. `null` when no extra data was provided."),
  /** Config version ID (`cfv_...`). */
  id: z.string().describe("Config version ID (`cfv_...`)."),
  /** Organization ID (`org_...`) that owns this config version. `null` for personal configs. */
  org: z.string().optional().describe("Organization ID (`org_...`) that owns this config version. `null` for personal configs."),
  /** Sandbox ID (`sbx_...`) this version was saved under. `null` for production configs. */
  sandbox: z.string().optional().describe("Sandbox ID (`sbx_...`) this version was saved under. `null` for production configs."),
  /** Monotonically increasing integer identifying this version within the config. Starts at 1. */
  version_number: z.number().int().describe("Monotonically increasing integer identifying this version within the config. Starts at 1."),
}).describe("A single immutable snapshot of a config's content, created each time the config is saved.") satisfies z.ZodType<ConfigVersion>;

/** A versioned config file owned by a team or user, representing a typed artifact such as an agent definition or API tool specification. */
export interface Config {
  /** Agent ID (`agt_...`) associated with this config. `null` if not linked to an agent. */
  agent?: string | undefined;
  /** When this config was first created (ISO 8601). */
  created_at?: string | undefined;
  /** The most recently saved version of this config. `null` if the config has never been saved with content. */
  current_version?: ConfigVersion | undefined;
  /** Config ID (`cfg_...`). */
  id: string;
  /** Whether this config has been archived. Archived configs are hidden from default listings but remain accessible by ID. */
  is_archived?: boolean | undefined;
  /** Type of config, e.g. `"Agent"` or `"APITool"`. Determines which fields and validation rules apply. */
  kind: string;
  /** Stable, user-defined key used to look up this config without knowing its ID. `null` if not set. */
  lookup_key?: string | undefined;
  /** MIME type of the config's content, e.g. `"text/yaml"`. `null` if not determined. */
  mime_type?: string | undefined;
  /** Organization ID (`org_...`) this config belongs to. `null` for configs not scoped to an org. */
  org?: string | undefined;
  /** Parent bundle config ID (`cfg_...`). Present only for configs that are children of a bundle; `null` otherwise. */
  parent?: string | undefined;
  /** ID (`cfg_...`) of the solution config this config was imported with. `null` if the config was not imported via a solution. */
  parent_solution?: string | undefined;
  /** Raw file content as a string. Populated only for system configs; `null` for user-owned configs. */
  raw_content?: string | undefined;
  /** Path of this config relative to its parent bundle root. Present only for bundle children; `null` otherwise. */
  relative_path?: string | undefined;
  /** Sandbox identifier this config belongs to. `null` for production configs. */
  sandbox?: string | undefined;
  /** Team ID (`tea_...`) that owns this config. `null` for personal (user-scoped) configs. */
  team?: string | undefined;
  /** When this config was last modified (ISO 8601). */
  updated_at?: string | undefined;
  /** User ID (`usr_...`) who owns this config. `null` for team-scoped configs. */
  user?: string | undefined;
  /** Logical path uniquely identifying this config within its team, e.g. `"agents/my-agent.yaml"`. `null` for configs without an explicit path. */
  virtual_path?: string | undefined;
}

/** Runtime validator for {@link Config}. */
export const configSchema = z.object({
  /** Agent ID (`agt_...`) associated with this config. `null` if not linked to an agent. */
  agent: z.string().optional().describe("Agent ID (`agt_...`) associated with this config. `null` if not linked to an agent."),
  /** When this config was first created (ISO 8601). */
  created_at: z.string().optional().describe("When this config was first created (ISO 8601)."),
  /** The most recently saved version of this config. `null` if the config has never been saved with content. */
  current_version: configVersionSchema.optional().describe("The most recently saved version of this config. `null` if the config has never been saved with content."),
  /** Config ID (`cfg_...`). */
  id: z.string().describe("Config ID (`cfg_...`)."),
  /** Whether this config has been archived. Archived configs are hidden from default listings but remain accessible by ID. */
  is_archived: z.boolean().optional().describe("Whether this config has been archived. Archived configs are hidden from default listings but remain accessible by ID."),
  /** Type of config, e.g. `"Agent"` or `"APITool"`. Determines which fields and validation rules apply. */
  kind: z.string().describe("Type of config, e.g. `\"Agent\"` or `\"APITool\"`. Determines which fields and validation rules apply."),
  /** Stable, user-defined key used to look up this config without knowing its ID. `null` if not set. */
  lookup_key: z.string().optional().describe("Stable, user-defined key used to look up this config without knowing its ID. `null` if not set."),
  /** MIME type of the config's content, e.g. `"text/yaml"`. `null` if not determined. */
  mime_type: z.string().optional().describe("MIME type of the config's content, e.g. `\"text/yaml\"`. `null` if not determined."),
  /** Organization ID (`org_...`) this config belongs to. `null` for configs not scoped to an org. */
  org: z.string().optional().describe("Organization ID (`org_...`) this config belongs to. `null` for configs not scoped to an org."),
  /** Parent bundle config ID (`cfg_...`). Present only for configs that are children of a bundle; `null` otherwise. */
  parent: z.string().optional().describe("Parent bundle config ID (`cfg_...`). Present only for configs that are children of a bundle; `null` otherwise."),
  /** ID (`cfg_...`) of the solution config this config was imported with. `null` if the config was not imported via a solution. */
  parent_solution: z.string().optional().describe("ID (`cfg_...`) of the solution config this config was imported with. `null` if the config was not imported via a solution."),
  /** Raw file content as a string. Populated only for system configs; `null` for user-owned configs. */
  raw_content: z.string().optional().describe("Raw file content as a string. Populated only for system configs; `null` for user-owned configs."),
  /** Path of this config relative to its parent bundle root. Present only for bundle children; `null` otherwise. */
  relative_path: z.string().optional().describe("Path of this config relative to its parent bundle root. Present only for bundle children; `null` otherwise."),
  /** Sandbox identifier this config belongs to. `null` for production configs. */
  sandbox: z.string().optional().describe("Sandbox identifier this config belongs to. `null` for production configs."),
  /** Team ID (`tea_...`) that owns this config. `null` for personal (user-scoped) configs. */
  team: z.string().optional().describe("Team ID (`tea_...`) that owns this config. `null` for personal (user-scoped) configs."),
  /** When this config was last modified (ISO 8601). */
  updated_at: z.string().optional().describe("When this config was last modified (ISO 8601)."),
  /** User ID (`usr_...`) who owns this config. `null` for team-scoped configs. */
  user: z.string().optional().describe("User ID (`usr_...`) who owns this config. `null` for team-scoped configs."),
  /** Logical path uniquely identifying this config within its team, e.g. `"agents/my-agent.yaml"`. `null` for configs without an explicit path. */
  virtual_path: z.string().optional().describe("Logical path uniquely identifying this config within its team, e.g. `\"agents/my-agent.yaml\"`. `null` for configs without an explicit path."),
}).describe("A versioned config file owned by a team or user, representing a typed artifact such as an agent definition or API tool specification.") satisfies z.ZodType<Config>;

/** A facet entry grouping configs by kind, returning the kind name and the number of matching configs visible to the authenticated viewer. */
export interface ConfigKindFacet {
  /** Number of configs of this kind that are visible to the authenticated viewer. Always `0` or greater. */
  count: number;
  /** The config kind identifier (e.g., `"Agent"`, `"WorkflowGraph"`). Matches the `kind` field on config objects. */
  kind: string;
}

/** Runtime validator for {@link ConfigKindFacet}. */
export const configKindFacetSchema = z.object({
  /** Number of configs of this kind that are visible to the authenticated viewer. Always `0` or greater. */
  count: z.number().int().describe("Number of configs of this kind that are visible to the authenticated viewer. Always `0` or greater."),
  /** The config kind identifier (e.g., `"Agent"`, `"WorkflowGraph"`). Matches the `kind` field on config objects. */
  kind: z.string().describe("The config kind identifier (e.g., `\"Agent\"`, `\"WorkflowGraph\"`). Matches the `kind` field on config objects."),
}).describe("A facet entry grouping configs by kind, returning the kind name and the number of matching configs visible to the authenticated viewer.") satisfies z.ZodType<ConfigKindFacet>;

/** A facet entry grouping configs by their leading path segment, returning the prefix and the number of matching configs visible to the authenticated viewer. */
export interface ConfigPathPrefixFacet {
  /** Number of configs whose `virtual_path` begins with this prefix that are visible to the authenticated viewer. Always `0` or greater. */
  count: number;
  /** The leading path segment of the config's `virtual_path`, always slash-terminated (e.g., `"agents/"`, `"__editor/"`). Pass this value as the `path_prefix` filter to narrow config listings. */
  prefix: string;
}

/** Runtime validator for {@link ConfigPathPrefixFacet}. */
export const configPathPrefixFacetSchema = z.object({
  /** Number of configs whose `virtual_path` begins with this prefix that are visible to the authenticated viewer. Always `0` or greater. */
  count: z.number().int().describe("Number of configs whose `virtual_path` begins with this prefix that are visible to the authenticated viewer. Always `0` or greater."),
  /** The leading path segment of the config's `virtual_path`, always slash-terminated (e.g., `"agents/"`, `"__editor/"`). Pass this value as the `path_prefix` filter to narrow config listings. */
  prefix: z.string().describe("The leading path segment of the config's `virtual_path`, always slash-terminated (e.g., `\"agents/\"`, `\"__editor/\"`). Pass this value as the `path_prefix` filter to narrow config listings."),
}).describe("A facet entry grouping configs by their leading path segment, returning the prefix and the number of matching configs visible to the authenticated viewer.") satisfies z.ZodType<ConfigPathPrefixFacet>;

/** Aggregated facet counts for the authenticated viewer's configs. Reports all distinct kinds and path prefixes across the full dataset, regardless of any active list filters. */
export interface ConfigFacets {
  /** All distinct config kinds present in the viewer's dataset, each with its total count. Use these values to populate kind filter options. */
  kinds: ConfigKindFacet[];
  /** All distinct slash-terminated path prefixes present in the viewer's dataset, each with its total count. Use these values to populate path prefix filter options. */
  path_prefixes: ConfigPathPrefixFacet[];
}

/** Runtime validator for {@link ConfigFacets}. */
export const configFacetsSchema = z.object({
  /** All distinct config kinds present in the viewer's dataset, each with its total count. Use these values to populate kind filter options. */
  kinds: z.array(configKindFacetSchema).describe("All distinct config kinds present in the viewer's dataset, each with its total count. Use these values to populate kind filter options."),
  /** All distinct slash-terminated path prefixes present in the viewer's dataset, each with its total count. Use these values to populate path prefix filter options. */
  path_prefixes: z.array(configPathPrefixFacetSchema).describe("All distinct slash-terminated path prefixes present in the viewer's dataset, each with its total count. Use these values to populate path prefix filter options."),
}).describe("Aggregated facet counts for the authenticated viewer's configs. Reports all distinct kinds and path prefixes across the full dataset, regardless of any active list filters.") satisfies z.ZodType<ConfigFacets>;

/** The JSON Schema definition and sample YAML for a specific config kind, used to validate and scaffold new configs of that kind. */
export interface ConfigKindSchema {
  /** JSON Schema object describing the valid structure of a config of this kind. `null` when no schema has been registered for this kind. */
  json_schema?: Record<string, unknown> | undefined;
  /** The config kind identifier (e.g., `"Agent"`, `"WorkflowGraph"`). Matches the `kind` field on config objects. */
  kind: string;
  /** A sample YAML document illustrating a minimal valid config of this kind. `null` when no sample has been registered for this kind. */
  sample_yaml?: string | undefined;
}

/** Runtime validator for {@link ConfigKindSchema}. */
export const configKindSchemaSchema = z.object({
  /** JSON Schema object describing the valid structure of a config of this kind. `null` when no schema has been registered for this kind. */
  json_schema: z.record(z.unknown()).optional().describe("JSON Schema object describing the valid structure of a config of this kind. `null` when no schema has been registered for this kind."),
  /** The config kind identifier (e.g., `"Agent"`, `"WorkflowGraph"`). Matches the `kind` field on config objects. */
  kind: z.string().describe("The config kind identifier (e.g., `\"Agent\"`, `\"WorkflowGraph\"`). Matches the `kind` field on config objects."),
  /** A sample YAML document illustrating a minimal valid config of this kind. `null` when no sample has been registered for this kind. */
  sample_yaml: z.string().optional().describe("A sample YAML document illustrating a minimal valid config of this kind. `null` when no sample has been registered for this kind."),
}).describe("The JSON Schema definition and sample YAML for a specific config kind, used to validate and scaffold new configs of that kind.") satisfies z.ZodType<ConfigKindSchema>;
