// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 2cc62988365d

import { z } from "zod";
import { imageSourceSchema } from "./image.js";

/** Minimal public-safe projection of the user who created an invite.

Invites are fetched by unauthenticated recipients on the `/auth/invites/:id`
route, so this schema deliberately exposes only the fields needed to render a
join screen — id, display name, and profile picture. Email, org, sandbox, and
other fields on the full `User` schema are omitted.
 */
export const inviteCreatorSchema = z.object({
  id: z.string(), // User ID
  name: z.string().optional(), // Display name
  profile_picture: imageSourceSchema.optional(), // Profile picture
});
export type InviteCreator = z.infer<typeof inviteCreatorSchema>;
