// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 1d1a764bd07a

import { z } from "zod";

/** Schema for ArchAstro script editor metadata */
export interface ScriptLanguageSpec {
  /** Builtin function docs */
  builtins: Record<string, unknown>[];
  /** Language keywords */
  keywords: string[];
  /** Monaco language identifier */
  languageId: string;
  /** Importable namespace docs */
  namespaces: Record<string, unknown>[];
  /** Language operators */
  operators: string[];
  /** Names that cannot be rebound */
  reservedNames?: string[] | undefined;
  /** Editor snippet templates */
  snippets?: Record<string, unknown>[] | undefined;
  /** Special symbols such as JSONPath root/current */
  specialIdentifiers?: Record<string, unknown>[] | undefined;
  /** Named type definitions (event interfaces, etc.) with fields */
  typeDefinitions?: Record<string, unknown>[] | undefined;
  /** Type-system primitives, generics, annotations, inference, and runtime-check guidance */
  typeSystem?: Record<string, unknown> | undefined;
  /** Schema version */
  version: number;
}

/** Runtime validator for {@link ScriptLanguageSpec}. */
export const scriptLanguageSpecSchema = z.object({
  /** Builtin function docs */
  builtins: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).describe("Builtin function docs"),
  /** Language keywords */
  keywords: z.array(z.string()).describe("Language keywords"),
  /** Monaco language identifier */
  languageId: z.string().describe("Monaco language identifier"),
  /** Importable namespace docs */
  namespaces: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).describe("Importable namespace docs"),
  /** Language operators */
  operators: z.array(z.string()).describe("Language operators"),
  /** Names that cannot be rebound */
  reservedNames: z.array(z.string()).optional().describe("Names that cannot be rebound"),
  /** Editor snippet templates */
  snippets: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).optional().describe("Editor snippet templates"),
  /** Special symbols such as JSONPath root/current */
  specialIdentifiers: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).optional().describe("Special symbols such as JSONPath root/current"),
  /** Named type definitions (event interfaces, etc.) with fields */
  typeDefinitions: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).optional().describe("Named type definitions (event interfaces, etc.) with fields"),
  /** Type-system primitives, generics, annotations, inference, and runtime-check guidance */
  typeSystem: z.record(z.custom<{} | null>((value) => value !== undefined)).optional().describe("Type-system primitives, generics, annotations, inference, and runtime-check guidance"),
  /** Schema version */
  version: z.number().int().describe("Schema version"),
}).describe("Schema for ArchAstro script editor metadata") satisfies z.ZodType<ScriptLanguageSpec>;

/** Schema for the result of executing a script in the editor */
export interface ScriptRunResult {
  /** Error message when script execution failed */
  error?: string | undefined;
  /** Structured diagnostics with position info for editor markers (severity, message, line, column, end_line, end_column) */
  findings?: Record<string, unknown>[] | undefined;
  /** Output lines from println calls, each with :line (source line number), :text, and optional :values */
  output?: Record<string, unknown>[] | undefined;
  /** The evaluated JSON-safe result (null when execution failed) */
  result?: unknown | undefined;
}

/** Runtime validator for {@link ScriptRunResult}. */
export const scriptRunResultSchema = z.object({
  /** Error message when script execution failed */
  error: z.string().optional().describe("Error message when script execution failed"),
  /** Structured diagnostics with position info for editor markers (severity, message, line, column, end_line, end_column) */
  findings: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).optional().describe("Structured diagnostics with position info for editor markers (severity, message, line, column, end_line, end_column)"),
  /** Output lines from println calls, each with :line (source line number), :text, and optional :values */
  output: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).optional().describe("Output lines from println calls, each with :line (source line number), :text, and optional :values"),
  /** The evaluated JSON-safe result (null when execution failed) */
  result: z.custom<{} | null>((value) => value !== undefined).optional().describe("The evaluated JSON-safe result (null when execution failed)"),
}).describe("Schema for the result of executing a script in the editor") satisfies z.ZodType<ScriptRunResult>;

/**
 * One `test.expect(...).<matcher>` call from a ScriptTest run.
 * Matchers never raise (the script language has no exceptions) — each call
 * emits a structured assertion entry that the test runner harvests into the
 * per-test report. Pass/fail is captured on `:pass`; `:expected` and
 * `:actual` carry the matcher's inputs for diff rendering.
 */
export interface ScriptTestAssertion {
  /** Actual value the matcher was called with — any JSON-safe value */
  actual?: unknown | undefined;
  /** Outer-to-inner describe path when the assertion fired */
  describe?: string[] | undefined;
  /** Expected value (or arguments to the matcher) — any JSON-safe value: scalar, map, or list */
  expected?: unknown | undefined;
  /** Name of the enclosing `test.it(...)` block */
  it?: string | undefined;
  /** Output entry kind, always `"assertion"` for this schema */
  kind?: string | undefined;
  /** Source line of the `expect(...)` call */
  line?: number | undefined;
  /** Matcher name (toEqual, toBe, toBeOk, toBeError, toContain, toMatch, toHaveLength) */
  matcher?: string | undefined;
  /** True when the matcher succeeded */
  pass: boolean;
}

/** Runtime validator for {@link ScriptTestAssertion}. */
export const scriptTestAssertionSchema = z.object({
  /** Actual value the matcher was called with — any JSON-safe value */
  actual: z.custom<{} | null>((value) => value !== undefined).optional().describe("Actual value the matcher was called with — any JSON-safe value"),
  /** Outer-to-inner describe path when the assertion fired */
  describe: z.array(z.string()).optional().describe("Outer-to-inner describe path when the assertion fired"),
  /** Expected value (or arguments to the matcher) — any JSON-safe value: scalar, map, or list */
  expected: z.custom<{} | null>((value) => value !== undefined).optional().describe("Expected value (or arguments to the matcher) — any JSON-safe value: scalar, map, or list"),
  /** Name of the enclosing `test.it(...)` block */
  it: z.string().optional().describe("Name of the enclosing `test.it(...)` block"),
  /** Output entry kind, always `"assertion"` for this schema */
  kind: z.string().optional().describe("Output entry kind, always `\"assertion\"` for this schema"),
  /** Source line of the `expect(...)` call */
  line: z.number().int().optional().describe("Source line of the `expect(...)` call"),
  /** Matcher name (toEqual, toBe, toBeOk, toBeError, toContain, toMatch, toHaveLength) */
  matcher: z.string().optional().describe("Matcher name (toEqual, toBe, toBeOk, toBeError, toContain, toMatch, toHaveLength)"),
  /** True when the matcher succeeded */
  pass: z.boolean().describe("True when the matcher succeeded"),
}).describe("One `test.expect(...).<matcher>` call from a ScriptTest run. Matchers never raise (the script language has no exceptions) — each call emits a structured assertion entry that the test runner harvests into the per-test report. Pass/fail is captured on `:pass`; `:expected` and `:actual` carry the matcher's inputs for diff rendering.") satisfies z.ZodType<ScriptTestAssertion>;

/**
 * One `test.it(...)` block from a ScriptTest run.
 * Built by the harvester from the raw output entries — pairs the case's
 * metadata with the assertions it produced and any runtime error that
 * aborted the body. An `it` block that emits zero assertions is treated
 * as a failure (`pass: false`) so silent mistakes don't pass quietly.
 */
export interface ScriptTestCase {
  /** Every `test.expect(...)` matcher that ran inside this case */
  assertions?: ScriptTestAssertion[] | undefined;
  /** Outer-to-inner describe path enclosing this case */
  describe?: string[] | undefined;
  /** Runtime error that aborted the body of this `it` block, when one occurred */
  error?: string | undefined;
  /** The name passed to `test.it(...)` */
  name: string;
  /** True when the case has at least one assertion and every assertion passed */
  pass: boolean;
}

/** Runtime validator for {@link ScriptTestCase}. */
export const scriptTestCaseSchema = z.object({
  /** Every `test.expect(...)` matcher that ran inside this case */
  assertions: z.array(scriptTestAssertionSchema).optional().describe("Every `test.expect(...)` matcher that ran inside this case"),
  /** Outer-to-inner describe path enclosing this case */
  describe: z.array(z.string()).optional().describe("Outer-to-inner describe path enclosing this case"),
  /** Runtime error that aborted the body of this `it` block, when one occurred */
  error: z.string().optional().describe("Runtime error that aborted the body of this `it` block, when one occurred"),
  /** The name passed to `test.it(...)` */
  name: z.string().describe("The name passed to `test.it(...)`"),
  /** True when the case has at least one assertion and every assertion passed */
  pass: z.boolean().describe("True when the case has at least one assertion and every assertion passed"),
}).describe("One `test.it(...)` block from a ScriptTest run. Built by the harvester from the raw output entries — pairs the case's metadata with the assertions it produced and any runtime error that aborted the body. An `it` block that emits zero assertions is treated as a failure (`pass: false`) so silent mistakes don't pass quietly.") satisfies z.ZodType<ScriptTestCase>;

/**
 * One println/log entry interleaved with a ScriptTest run.
 * After the test harvester filters out test-control entries (`it`,
 * `assertion`, `it_error`), only `println` and `log.<level>` calls remain
 * in the report's `output` field. Both shapes share `text`/`values`/`line`
 * (line is auto-annotated by the evaluator post-call); `level` and
 * `timestamp` are only present on `log.*` entries.
 */
export interface ScriptTestOutputEntry {
  /** Log level (`debug`, `info`, `warn`, `error`) — present on log.* entries only */
  level?: string | undefined;
  /** Source line of the println/log call */
  line?: number | undefined;
  /** Joined text representation of the args */
  text: string;
  /** UTC timestamp — present on log.* entries only */
  timestamp?: string | undefined;
  /** Original args coerced to JSON-safe values — mixed scalars, maps, and lists since the call sites accept arbitrary expressions */
  values?: unknown[] | undefined;
}

/** Runtime validator for {@link ScriptTestOutputEntry}. */
export const scriptTestOutputEntrySchema = z.object({
  /** Log level (`debug`, `info`, `warn`, `error`) — present on log.* entries only */
  level: z.string().optional().describe("Log level (`debug`, `info`, `warn`, `error`) — present on log.* entries only"),
  /** Source line of the println/log call */
  line: z.number().int().optional().describe("Source line of the println/log call"),
  /** Joined text representation of the args */
  text: z.string().describe("Joined text representation of the args"),
  /** UTC timestamp — present on log.* entries only */
  timestamp: z.string().optional().describe("UTC timestamp — present on log.* entries only"),
  /** Original args coerced to JSON-safe values — mixed scalars, maps, and lists since the call sites accept arbitrary expressions */
  values: z.array(z.custom<{} | null>((value) => value !== undefined)).optional().describe("Original args coerced to JSON-safe values — mixed scalars, maps, and lists since the call sites accept arbitrary expressions"),
}).describe("One println/log entry interleaved with a ScriptTest run. After the test harvester filters out test-control entries (`it`, `assertion`, `it_error`), only `println` and `log.<level>` calls remain in the report's `output` field. Both shapes share `text`/`values`/`line` (line is auto-annotated by the evaluator post-call); `level` and `timestamp` are only present on `log.*` entries.") satisfies z.ZodType<ScriptTestOutputEntry>;

/**
 * One `test.describe(...)` group from a ScriptTest run.
 * Suites are derived from the unique describe paths the harvester sees, so
 * there's no synthetic "ungrouped" suite — `it` blocks emitted outside any
 * `describe` show up in the top-level `tests` array on the parent report
 * instead.
 */
export interface ScriptTestSuite {
  /** Outer-to-inner describe path identifying this suite */
  describe: string[];
  /** Human-readable suite name (`describe` path joined by ` > `) */
  name: string;
  /** Every `test.it(...)` case run inside this describe */
  tests?: ScriptTestCase[] | undefined;
}

/** Runtime validator for {@link ScriptTestSuite}. */
export const scriptTestSuiteSchema = z.object({
  /** Outer-to-inner describe path identifying this suite */
  describe: z.array(z.string()).describe("Outer-to-inner describe path identifying this suite"),
  /** Human-readable suite name (`describe` path joined by ` > `) */
  name: z.string().describe("Human-readable suite name (`describe` path joined by ` > `)"),
  /** Every `test.it(...)` case run inside this describe */
  tests: z.array(scriptTestCaseSchema).optional().describe("Every `test.it(...)` case run inside this describe"),
}).describe("One `test.describe(...)` group from a ScriptTest run. Suites are derived from the unique describe paths the harvester sees, so there's no synthetic \"ungrouped\" suite — `it` blocks emitted outside any `describe` show up in the top-level `tests` array on the parent report instead.") satisfies z.ZodType<ScriptTestSuite>;

/** Schema for the result of running a ScriptTest */
export interface ScriptTestRunResult {
  /** Total number of `test.expect(...)` matcher calls that ran */
  assertion_count?: number | undefined;
  /** Top-level error message when a runtime error fired outside any `it` block (parse/tokenize errors return 422 instead) */
  error?: string | undefined;
  /** Structured diagnostics with position info for editor markers when the run errored before any tests could run */
  findings?: Record<string, unknown>[] | undefined;
  /** Non-test output entries (println, log.*) interleaved during the run */
  output?: ScriptTestOutputEntry[] | undefined;
  /** True when every test in every suite passed */
  passed: boolean;
  /** One entry per describe path */
  suites?: ScriptTestSuite[] | undefined;
  /** Flat list of every `it` that ran, each with assertions and pass flag */
  tests?: ScriptTestCase[] | undefined;
}

/** Runtime validator for {@link ScriptTestRunResult}. */
export const scriptTestRunResultSchema = z.object({
  /** Total number of `test.expect(...)` matcher calls that ran */
  assertion_count: z.number().int().optional().describe("Total number of `test.expect(...)` matcher calls that ran"),
  /** Top-level error message when a runtime error fired outside any `it` block (parse/tokenize errors return 422 instead) */
  error: z.string().optional().describe("Top-level error message when a runtime error fired outside any `it` block (parse/tokenize errors return 422 instead)"),
  /** Structured diagnostics with position info for editor markers when the run errored before any tests could run */
  findings: z.array(z.record(z.custom<{} | null>((value) => value !== undefined))).optional().describe("Structured diagnostics with position info for editor markers when the run errored before any tests could run"),
  /** Non-test output entries (println, log.*) interleaved during the run */
  output: z.array(scriptTestOutputEntrySchema).optional().describe("Non-test output entries (println, log.*) interleaved during the run"),
  /** True when every test in every suite passed */
  passed: z.boolean().describe("True when every test in every suite passed"),
  /** One entry per describe path */
  suites: z.array(scriptTestSuiteSchema).optional().describe("One entry per describe path"),
  /** Flat list of every `it` that ran, each with assertions and pass flag */
  tests: z.array(scriptTestCaseSchema).optional().describe("Flat list of every `it` that ran, each with assertions and pass flag"),
}).describe("Schema for the result of running a ScriptTest") satisfies z.ZodType<ScriptTestRunResult>;
