// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 12dcacbd0afe

import { z } from "zod";

/** A long-lived API credential associated with a system account, used to authenticate server-to-server requests. */
export interface SystemAccessToken {
  /** When this token was created (ISO 8601). */
  created_at?: string | undefined;
  /** When the token expires. `null` on legacy rows that predate stored expiry. */
  expires_at?: string | undefined;
  /** Token ID (`sat_...`). */
  id: string;
  /** When this token was last used to authenticate a request. `null` if the token has never been used. */
  last_used_at?: string | undefined;
  /** Human-readable label assigned to this token at creation time. */
  name?: string | undefined;
  /** When this token was revoked. `null` if the token is still active. */
  revoked_at?: string | undefined;
  /** Space-separated OAuth scopes stamped on the token. `null` on legacy rows; treat as `full_access`. */
  scopes?: string | undefined;
  /** Raw bearer token string. Present only in the response to the create request; never returned again after that. */
  token?: string | undefined;
}

/** Runtime validator for {@link SystemAccessToken}. */
export const systemAccessTokenSchema = z.object({
  /** When this token was created (ISO 8601). */
  created_at: z.string().optional().describe("When this token was created (ISO 8601)."),
  /** When the token expires. `null` on legacy rows that predate stored expiry. */
  expires_at: z.string().optional().describe("When the token expires. `null` on legacy rows that predate stored expiry."),
  /** Token ID (`sat_...`). */
  id: z.string().describe("Token ID (`sat_...`)."),
  /** When this token was last used to authenticate a request. `null` if the token has never been used. */
  last_used_at: z.string().optional().describe("When this token was last used to authenticate a request. `null` if the token has never been used."),
  /** Human-readable label assigned to this token at creation time. */
  name: z.string().optional().describe("Human-readable label assigned to this token at creation time."),
  /** When this token was revoked. `null` if the token is still active. */
  revoked_at: z.string().optional().describe("When this token was revoked. `null` if the token is still active."),
  /** Space-separated OAuth scopes stamped on the token. `null` on legacy rows; treat as `full_access`. */
  scopes: z.string().optional().describe("Space-separated OAuth scopes stamped on the token. `null` on legacy rows; treat as `full_access`."),
  /** Raw bearer token string. Present only in the response to the create request; never returned again after that. */
  token: z.string().optional().describe("Raw bearer token string. Present only in the response to the create request; never returned again after that."),
}).describe("A long-lived API credential associated with a system account, used to authenticate server-to-server requests.") satisfies z.ZodType<SystemAccessToken>;
