// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d5c97d7c6aef

import { z } from "zod";

/** A long-lived API credential associated with a system account, used to authenticate server-to-server requests. */
export interface SystemAccessToken {
  /** When this token was created (ISO 8601). */
  created_at?: string | undefined;
  /** Agent user that minted this token (`usr_...`). `null` unless an agent minted it. */
  created_by_agent_user?: string | null | undefined;
  /** Developer account that minted this token (`dva_...`). `null` unless minted with a developer token. */
  created_by_developer?: string | null | undefined;
  /** Org of the principal that minted this token (`org_...`). `null` on legacy rows. */
  created_by_org?: string | null | undefined;
  /** Team that minted this token (`tem_...`). `null` unless minted as a team. */
  created_by_team?: string | null | undefined;
  /** User who minted this token (`usr_...`). Distinct from the token subject. `null` on legacy rows. */
  created_by_user?: string | null | undefined;
  /** When the token expires. `null` on legacy rows that predate stored expiry. */
  expires_at?: string | null | undefined;
  /** Token ID (`sat_...`). */
  id: string;
  /** When this token was last used to authenticate a request. `null` if the token has never been used. */
  last_used_at?: string | null | undefined;
  /** Human-readable label assigned to this token at creation time. `null` when no label was supplied. */
  name?: string | null | undefined;
  /** When this token was revoked. `null` if the token is still active. */
  revoked_at?: string | null | undefined;
  /** Space-separated OAuth scopes stamped on the token. `null` on legacy rows; treat as `full_access`. */
  scopes?: string | null | undefined;
  /** Raw bearer token string. Present only in the response to the create request; never returned again after that. */
  token?: string | undefined;
}

/** Runtime validator for {@link SystemAccessToken}. */
export const systemAccessTokenSchema = z.object({
  /** When this token was created (ISO 8601). */
  created_at: z.string().optional().describe("When this token was created (ISO 8601)."),
  /** Agent user that minted this token (`usr_...`). `null` unless an agent minted it. */
  created_by_agent_user: z.string().nullable().optional().describe("Agent user that minted this token (`usr_...`). `null` unless an agent minted it."),
  /** Developer account that minted this token (`dva_...`). `null` unless minted with a developer token. */
  created_by_developer: z.string().nullable().optional().describe("Developer account that minted this token (`dva_...`). `null` unless minted with a developer token."),
  /** Org of the principal that minted this token (`org_...`). `null` on legacy rows. */
  created_by_org: z.string().nullable().optional().describe("Org of the principal that minted this token (`org_...`). `null` on legacy rows."),
  /** Team that minted this token (`tem_...`). `null` unless minted as a team. */
  created_by_team: z.string().nullable().optional().describe("Team that minted this token (`tem_...`). `null` unless minted as a team."),
  /** User who minted this token (`usr_...`). Distinct from the token subject. `null` on legacy rows. */
  created_by_user: z.string().nullable().optional().describe("User who minted this token (`usr_...`). Distinct from the token subject. `null` on legacy rows."),
  /** When the token expires. `null` on legacy rows that predate stored expiry. */
  expires_at: z.string().nullable().optional().describe("When the token expires. `null` on legacy rows that predate stored expiry."),
  /** Token ID (`sat_...`). */
  id: z.string().describe("Token ID (`sat_...`)."),
  /** When this token was last used to authenticate a request. `null` if the token has never been used. */
  last_used_at: z.string().nullable().optional().describe("When this token was last used to authenticate a request. `null` if the token has never been used."),
  /** Human-readable label assigned to this token at creation time. `null` when no label was supplied. */
  name: z.string().nullable().optional().describe("Human-readable label assigned to this token at creation time. `null` when no label was supplied."),
  /** When this token was revoked. `null` if the token is still active. */
  revoked_at: z.string().nullable().optional().describe("When this token was revoked. `null` if the token is still active."),
  /** Space-separated OAuth scopes stamped on the token. `null` on legacy rows; treat as `full_access`. */
  scopes: z.string().nullable().optional().describe("Space-separated OAuth scopes stamped on the token. `null` on legacy rows; treat as `full_access`."),
  /** Raw bearer token string. Present only in the response to the create request; never returned again after that. */
  token: z.string().optional().describe("Raw bearer token string. Present only in the response to the create request; never returned again after that."),
}).describe("A long-lived API credential associated with a system account, used to authenticate server-to-server requests.") satisfies z.ZodType<SystemAccessToken>;
