// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: b6be950c01cd

import { z } from "zod";
import { agentSchema } from "./agents.js";
import { attachmentSchema, messageSchema } from "./common.js";
import { userSchema } from "./users.js";

/** Schema for thread settings response.

Used by thread settings show/update endpoints.
 */
export const threadSettingsSchema = z.object({
  agent_enabled: z.boolean().optional(), // Whether the agent is enabled for this thread
});
export type ThreadSettings = z.infer<typeof threadSettingsSchema>;

/** API schema for a chat thread. */
export const threadSchema = z.object({
  agent_user: z.string().optional(), // Owning agent user
  created_at: z.string().optional(), // Creation timestamp
  creator: userSchema.optional(), // Creator user object
  description: z.string().optional(), // Thread description
  id: z.string(), // Thread ID (thr_...)
  is_channel: z.boolean().optional(), // Whether this is a channel
  is_default: z.boolean().optional(), // Whether this is the default thread
  is_transient: z.boolean().optional(), // Whether this thread is transient
  is_unlisted: z.boolean().optional(), // Whether this thread is unlisted
  key: z.string().optional(), // Thread key
  last_activity: z.string().optional(), // Last activity timestamp
  metadata: z.record(z.unknown()).optional(), // Thread metadata
  org: z.string().optional(), // Organization
  parent_message: messageSchema.optional(), // Parent message object
  participant: z.array(z.string()).optional(), // Participant users
  participants: z.array(userSchema).optional(), // Participant user objects
  participating_actor: z.array(z.string()).optional(), // Actors participating in thread
  participating_agents: z.array(agentSchema).optional(), // Agents participating in thread
  role: z.string().optional(), // User's role in the thread
  sandbox: z.string().optional(), // Sandbox identifier
  settings: threadSettingsSchema.optional(), // Thread settings
  slug: z.string().optional(), // Thread slug
  sub_threads: z.array(z.record(z.unknown())).optional(), // Sub-threads
  team: z.string().optional(), // Owning team
  title: z.string().optional(), // Thread title
  ttl: z.number().int().optional(), // Time-to-live in seconds
  unread_count: z.number().int().optional(), // Unread message count
  updated_at: z.string().optional(), // Last update timestamp
  user: z.string().optional(), // Owning user
});
export type Thread = z.infer<typeof threadSchema>;

/** API schema for a thread action. */
export const threadActionSchema = z.object({
  call_to_action: z.string().optional(), // Call to action text
  completion_result: z.record(z.unknown()).optional(), // Result after action completion
  id: z.string(), // Thread action ID (tha_...)
  metadata: z.record(z.unknown()).optional(), // Action metadata
  native_template: z.record(z.unknown()).optional(), // Native template for mobile clients
  org: z.string().optional(), // Organization
  path: z.string().optional(), // URL path for action
  sandbox: z.string().optional(), // Sandbox
  status: z.string(), // Action status (active, canceled, done)
  type: z.string(), // Action type (connect_google, add_credential, send_email)
});
export type ThreadAction = z.infer<typeof threadActionSchema>;

/** Base64 encoded profile picture */
export const threadCreateParamsProfilePictureSchema = z.object({
  data: z.string().optional(), // Base64 encoded image data
  filename: z.string().optional(), // Original filename
  mime_type: z.string().optional(), // MIME type of the image
});
export type ThreadCreateParamsProfilePicture = z.infer<typeof threadCreateParamsProfilePictureSchema>;

/** Schema for thread creation parameters.

Used by both Users.Threads.Create and Teams.Threads.Create actions.
 */
export const threadCreateParamsSchema = z.object({
  create_legacy_agent: z.boolean().optional(), // Create a legacy chat agent for this thread
  description: z.string().optional(), // Thread description
  is_unlisted: z.boolean().optional(), // Whether the thread is unlisted
  key: z.string().optional(), // Unique key for the thread
  metadata: z.record(z.unknown()).optional(), // Additional metadata
  org_id: z.string().optional(), // Organization ID
  profile_picture: threadCreateParamsProfilePictureSchema.optional(), // Base64 encoded profile picture
  settings: threadSettingsSchema.optional(), // Thread settings
  title: z.string().optional(), // Thread title
});
export type ThreadCreateParams = z.infer<typeof threadCreateParamsSchema>;

/** Schema for thread detail response in the developer portal.

Extended thread data including members and associated entities.
 */
export const threadDetailSchema = z.object({
  agent: z.record(z.unknown()).optional(), // Associated agent info (id, name)
  app_name: z.string().optional(), // Associated app name
  created_at: z.string().optional(), // Created timestamp
  creator: z.record(z.unknown()).optional(), // Thread creator info (id, email, full_name)
  id: z.string(), // Public ID (thr_...)
  is_channel: z.boolean().optional(), // Whether this is a channel thread
  is_default: z.boolean().optional(), // Whether this is the default thread
  is_unlisted: z.boolean().optional(), // Whether thread is hidden from listings
  key: z.string().optional(), // Unique key within owner scope
  members: z.array(z.record(z.unknown())).optional(), // Thread member list
  metadata: z.record(z.unknown()).optional(), // Thread metadata
  org: z.string().optional(), // Organization (nullable)
  owner: z.string().optional(), // Owner public
  owner_name: z.string().optional(), // Owner display name
  owner_type: z.string().optional(), // Owner type: team, user, agent, or nil
  sandbox: z.string().optional(), // Sandbox identifier (nullable)
  slug: z.string().optional(), // URL-friendly slug
  title: z.string(), // Thread title
  updated_at: z.string().optional(), // Updated timestamp
});
export type ThreadDetail = z.infer<typeof threadDetailSchema>;

/** API schema for a thread member. */
export const threadMemberSchema = z.object({
  membership_type: z.string().optional(), // Membership type (owner or member)
  thread: z.string().optional(), // Thread
  user: userSchema.optional(), // User details (when loaded)
});
export type ThreadMember = z.infer<typeof threadMemberSchema>;

/** Schema for a thread message in the developer portal.

Maps to serialized message output from developer portal API.
 */
export const threadMessageSchema = z.object({
  admin: z.record(z.unknown()).optional(), // Admin-only metadata and trajectory
  agent: z.string().optional(), // Agent identifier (nullable)
  app: z.string().optional(), // App identifier
  attachments: z.array(attachmentSchema).optional(), // Message attachments
  content: z.string().optional(), // Message content
  created_at: z.string().optional(), // Created timestamp
  id: z.string(), // Public ID (msg_...)
  org: z.string().optional(), // Organization (nullable)
  sandbox: z.string().optional(), // Sandbox identifier (nullable)
  sender: z.string().optional(), // Sender public
  sender_name: z.string().optional(), // Display name of sender
  sender_type: z.string().optional(), // Type: user, agent, or system
  team: z.string().optional(), // Team identifier (nullable)
  user: z.string().optional(), // User identifier (nullable)
});
export type ThreadMessage = z.infer<typeof threadMessageSchema>;

/** API schema for a thread message trajectory. */
export const threadMessageTrajectorySchema = z.object({
  agent_message: z.string().optional(), // Agent message
  created_at: z.string().optional(), // Creation timestamp
  id: z.string(), // Thread message trajectory ID (tmt_...)
  org: z.string().optional(), // Organization
  sandbox: z.string().optional(), // Sandbox
  thread: z.string().optional(), // Thread
  trajectory: z.string().optional(), // Trajectory
  updated_at: z.string().optional(), // Last update timestamp
  user_message: z.string().optional(), // User message
});
export type ThreadMessageTrajectory = z.infer<typeof threadMessageTrajectorySchema>;

/** Schema for thread read status response.
 */
export const threadReadStatusSchema = z.object({
  last_read_message: z.string().optional(), // Last read message
  thread: z.string(), // Thread
  unread_count: z.number().int(), // Number of unread messages
});
export type ThreadReadStatus = z.infer<typeof threadReadStatusSchema>;

/** Base64 encoded profile picture */
export const threadUpdateParamsProfilePictureSchema = z.object({
  data: z.string().optional(), // Base64 encoded image data
  filename: z.string().optional(), // Original filename
  mime_type: z.string().optional(), // MIME type of the image
});
export type ThreadUpdateParamsProfilePicture = z.infer<typeof threadUpdateParamsProfilePictureSchema>;

/** Schema for thread update parameters.

Used by both Users.Threads.Update and Teams.Threads.Update actions.
 */
export const threadUpdateParamsSchema = z.object({
  description: z.string().optional(), // Thread description
  metadata: z.record(z.unknown()).optional(), // Additional metadata
  profile_picture: threadUpdateParamsProfilePictureSchema.optional(), // Base64 encoded profile picture
  title: z.string().optional(), // Thread title
});
export type ThreadUpdateParams = z.infer<typeof threadUpdateParamsSchema>;
