// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: b4d3aee0a9fd

import { z } from "zod";
import { agentSchema, messageSchema } from "./common.js";
import { userSchema } from "./users.js";
import type { Agent, Message } from "./common.js";
import type { User } from "./users.js";

/** Configuration settings for a thread that control AI agent behavior and other thread-level preferences. */
export interface ThreadSettings {
  /** Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured. */
  agent_enabled?: boolean | undefined;
}

/** Runtime validator for {@link ThreadSettings}. */
export const threadSettingsSchema = z.object({
  /** Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured. */
  agent_enabled: z.boolean().optional().describe("Whether the AI agent is active for this thread. `true` enables AI responses; `false` disables them. Defaults to `true` when settings have not been explicitly configured."),
}).describe("Configuration settings for a thread that control AI agent behavior and other thread-level preferences.") satisfies z.ZodType<ThreadSettings>;

/** A chat thread, representing a conversation channel that can be owned by a user, team, or agent and may contain messages, participants, and AI agent activity. */
export interface Thread {
  /** ID of the agent that owns this thread (`agt_...`). `null` for user-owned or team-owned threads. */
  agent_user?: string | undefined;
  /** When the thread was created (ISO 8601). */
  created_at?: string | undefined;
  /** Expanded user object for the user who created this thread. Populated only when the association is loaded. */
  creator?: User | undefined;
  /** Optional description or purpose statement for the thread. `null` if not set. */
  description?: string | undefined;
  /** Thread ID (`thr_...`). */
  id: string;
  /** Whether this thread operates as a channel — a multi-member broadcast-style conversation. */
  is_channel?: boolean | undefined;
  /** Whether this is the default thread for its owner. Each user or team has at most one default thread. */
  is_default?: boolean | undefined;
  /** Whether this thread is ephemeral and may be deleted automatically after a period of inactivity or when its TTL expires. */
  is_transient?: boolean | undefined;
  /** Whether this thread is hidden from public discovery. Unlisted threads are accessible only to direct participants. */
  is_unlisted?: boolean | undefined;
  /** Application-defined stable key that uniquely identifies the thread within its scope. Useful for idempotent creation. `null` if not set. */
  key?: string | undefined;
  /** When the last message or activity occurred in this thread. Present only when activity enrichment is requested. */
  last_activity?: string | undefined;
  /** Arbitrary key-value metadata attached to the thread. Shape is application-defined; `null` if no metadata has been set. */
  metadata?: Record<string, unknown> | undefined;
  /** Whether the authenticated user has muted notifications for this thread. `true` suppresses all notification delivery. */
  muted?: boolean | undefined;
  /** ID of the organization this thread belongs to (`org_...`). `null` for threads outside an org context. */
  org?: string | undefined;
  /** The message that spawned this thread as a sub-thread. `null` for top-level threads. */
  parent_message?: Message | undefined;
  /** Array of participant user IDs (`usr_...`) who are members of this thread. */
  participant?: string[] | undefined;
  /** Expanded participant user objects for each member of this thread. Populated only when the association is loaded. */
  participants?: User[] | undefined;
  /** Composite actor identifiers for all participants currently active in this thread. Present only when actor enrichment is requested. */
  participating_actor?: string[] | undefined;
  /** Expanded agent objects for all agents participating in this thread. Present only when agent enrichment is requested. */
  participating_agents?: Agent[] | undefined;
  /** The authenticated user's membership role in this thread, e.g. `"owner"`, `"member"`, or `"viewer"`. `null` if the user is not a member. */
  role?: string | undefined;
  /** ID of the developer sandbox this thread is scoped to (`sbx_...`). `null` for production threads. */
  sandbox?: string | undefined;
  /** Per-thread configuration settings controlling AI agent behavior for this thread. */
  settings?: ThreadSettings | undefined;
  /** URL-safe slug for the thread, used in human-readable permalinks. `null` if not assigned. */
  slug?: string | undefined;
  /** Threads that are nested under this thread as replies to a parent message. Present only when sub-thread enrichment is requested. */
  sub_threads?: Record<string, unknown>[] | undefined;
  /** ID of the team that owns this thread (`team_...`). `null` for user-owned or agent-owned threads. */
  team?: string | undefined;
  /** Human-readable name of the thread. `null` if no title has been set. */
  title?: string | undefined;
  /** Time-to-live in seconds after which the thread may be automatically cleaned up. `null` if the thread does not expire. */
  ttl?: number | undefined;
  /** Number of messages in this thread that the authenticated user has not yet read. Present only when read-state enrichment is requested. */
  unread_count?: number | undefined;
  /** When the thread was last modified (ISO 8601). */
  updated_at?: string | undefined;
  /** ID of the user who owns this thread (`usr_...`). `null` for team-owned or agent-owned threads. */
  user?: string | undefined;
}

/** Runtime validator for {@link Thread}. */
export const threadSchema = z.object({
  /** ID of the agent that owns this thread (`agt_...`). `null` for user-owned or team-owned threads. */
  agent_user: z.string().optional().describe("ID of the agent that owns this thread (`agt_...`). `null` for user-owned or team-owned threads."),
  /** When the thread was created (ISO 8601). */
  created_at: z.string().optional().describe("When the thread was created (ISO 8601)."),
  /** Expanded user object for the user who created this thread. Populated only when the association is loaded. */
  creator: userSchema.optional().describe("Expanded user object for the user who created this thread. Populated only when the association is loaded."),
  /** Optional description or purpose statement for the thread. `null` if not set. */
  description: z.string().optional().describe("Optional description or purpose statement for the thread. `null` if not set."),
  /** Thread ID (`thr_...`). */
  id: z.string().describe("Thread ID (`thr_...`)."),
  /** Whether this thread operates as a channel — a multi-member broadcast-style conversation. */
  is_channel: z.boolean().optional().describe("Whether this thread operates as a channel — a multi-member broadcast-style conversation."),
  /** Whether this is the default thread for its owner. Each user or team has at most one default thread. */
  is_default: z.boolean().optional().describe("Whether this is the default thread for its owner. Each user or team has at most one default thread."),
  /** Whether this thread is ephemeral and may be deleted automatically after a period of inactivity or when its TTL expires. */
  is_transient: z.boolean().optional().describe("Whether this thread is ephemeral and may be deleted automatically after a period of inactivity or when its TTL expires."),
  /** Whether this thread is hidden from public discovery. Unlisted threads are accessible only to direct participants. */
  is_unlisted: z.boolean().optional().describe("Whether this thread is hidden from public discovery. Unlisted threads are accessible only to direct participants."),
  /** Application-defined stable key that uniquely identifies the thread within its scope. Useful for idempotent creation. `null` if not set. */
  key: z.string().optional().describe("Application-defined stable key that uniquely identifies the thread within its scope. Useful for idempotent creation. `null` if not set."),
  /** When the last message or activity occurred in this thread. Present only when activity enrichment is requested. */
  last_activity: z.string().optional().describe("When the last message or activity occurred in this thread. Present only when activity enrichment is requested."),
  /** Arbitrary key-value metadata attached to the thread. Shape is application-defined; `null` if no metadata has been set. */
  metadata: z.record(z.unknown()).optional().describe("Arbitrary key-value metadata attached to the thread. Shape is application-defined; `null` if no metadata has been set."),
  /** Whether the authenticated user has muted notifications for this thread. `true` suppresses all notification delivery. */
  muted: z.boolean().optional().describe("Whether the authenticated user has muted notifications for this thread. `true` suppresses all notification delivery."),
  /** ID of the organization this thread belongs to (`org_...`). `null` for threads outside an org context. */
  org: z.string().optional().describe("ID of the organization this thread belongs to (`org_...`). `null` for threads outside an org context."),
  /** The message that spawned this thread as a sub-thread. `null` for top-level threads. */
  parent_message: messageSchema.optional().describe("The message that spawned this thread as a sub-thread. `null` for top-level threads."),
  /** Array of participant user IDs (`usr_...`) who are members of this thread. */
  participant: z.array(z.string()).optional().describe("Array of participant user IDs (`usr_...`) who are members of this thread."),
  /** Expanded participant user objects for each member of this thread. Populated only when the association is loaded. */
  participants: z.array(userSchema).optional().describe("Expanded participant user objects for each member of this thread. Populated only when the association is loaded."),
  /** Composite actor identifiers for all participants currently active in this thread. Present only when actor enrichment is requested. */
  participating_actor: z.array(z.string()).optional().describe("Composite actor identifiers for all participants currently active in this thread. Present only when actor enrichment is requested."),
  /** Expanded agent objects for all agents participating in this thread. Present only when agent enrichment is requested. */
  participating_agents: z.array(agentSchema).optional().describe("Expanded agent objects for all agents participating in this thread. Present only when agent enrichment is requested."),
  /** The authenticated user's membership role in this thread, e.g. `"owner"`, `"member"`, or `"viewer"`. `null` if the user is not a member. */
  role: z.string().optional().describe("The authenticated user's membership role in this thread, e.g. `\"owner\"`, `\"member\"`, or `\"viewer\"`. `null` if the user is not a member."),
  /** ID of the developer sandbox this thread is scoped to (`sbx_...`). `null` for production threads. */
  sandbox: z.string().optional().describe("ID of the developer sandbox this thread is scoped to (`sbx_...`). `null` for production threads."),
  /** Per-thread configuration settings controlling AI agent behavior for this thread. */
  settings: threadSettingsSchema.optional().describe("Per-thread configuration settings controlling AI agent behavior for this thread."),
  /** URL-safe slug for the thread, used in human-readable permalinks. `null` if not assigned. */
  slug: z.string().optional().describe("URL-safe slug for the thread, used in human-readable permalinks. `null` if not assigned."),
  /** Threads that are nested under this thread as replies to a parent message. Present only when sub-thread enrichment is requested. */
  sub_threads: z.array(z.record(z.unknown())).optional().describe("Threads that are nested under this thread as replies to a parent message. Present only when sub-thread enrichment is requested."),
  /** ID of the team that owns this thread (`team_...`). `null` for user-owned or agent-owned threads. */
  team: z.string().optional().describe("ID of the team that owns this thread (`team_...`). `null` for user-owned or agent-owned threads."),
  /** Human-readable name of the thread. `null` if no title has been set. */
  title: z.string().optional().describe("Human-readable name of the thread. `null` if no title has been set."),
  /** Time-to-live in seconds after which the thread may be automatically cleaned up. `null` if the thread does not expire. */
  ttl: z.number().int().optional().describe("Time-to-live in seconds after which the thread may be automatically cleaned up. `null` if the thread does not expire."),
  /** Number of messages in this thread that the authenticated user has not yet read. Present only when read-state enrichment is requested. */
  unread_count: z.number().int().optional().describe("Number of messages in this thread that the authenticated user has not yet read. Present only when read-state enrichment is requested."),
  /** When the thread was last modified (ISO 8601). */
  updated_at: z.string().optional().describe("When the thread was last modified (ISO 8601)."),
  /** ID of the user who owns this thread (`usr_...`). `null` for team-owned or agent-owned threads. */
  user: z.string().optional().describe("ID of the user who owns this thread (`usr_...`). `null` for team-owned or agent-owned threads."),
}).describe("A chat thread, representing a conversation channel that can be owned by a user, team, or agent and may contain messages, participants, and AI agent activity.") satisfies z.ZodType<Thread>;

/** A user's membership record in a thread, capturing their role and full user profile. */
export interface ThreadMember {
  /** Role of the member within the thread. One of `"owner"` (the user who created or was granted ownership) or `"member"` (a regular participant). */
  membership_type?: string | undefined;
  /** ID of the thread this membership belongs to (`thr_...`). */
  thread?: string | undefined;
  /** Full user object for the member (`usr_...`). Present when the association is preloaded; `null` otherwise. */
  user?: User | undefined;
}

/** Runtime validator for {@link ThreadMember}. */
export const threadMemberSchema = z.object({
  /** Role of the member within the thread. One of `"owner"` (the user who created or was granted ownership) or `"member"` (a regular participant). */
  membership_type: z.string().optional().describe("Role of the member within the thread. One of `\"owner\"` (the user who created or was granted ownership) or `\"member\"` (a regular participant)."),
  /** ID of the thread this membership belongs to (`thr_...`). */
  thread: z.string().optional().describe("ID of the thread this membership belongs to (`thr_...`)."),
  /** Full user object for the member (`usr_...`). Present when the association is preloaded; `null` otherwise. */
  user: userSchema.optional().describe("Full user object for the member (`usr_...`). Present when the association is preloaded; `null` otherwise."),
}).describe("A user's membership record in a thread, capturing their role and full user profile.") satisfies z.ZodType<ThreadMember>;

/** The read status of a thread for a specific user, indicating how far they have read and how many messages remain unread. */
export interface ThreadReadStatus {
  /** Message ID (`msg_...`) of the last message the user has read in this thread. `null` if the user has never read any message in the thread. */
  last_read_message?: string | undefined;
  /** Thread ID (`thr_...`) that this read status belongs to. */
  thread: string;
  /** Number of messages in the thread that the user has not yet read. */
  unread_count: number;
}

/** Runtime validator for {@link ThreadReadStatus}. */
export const threadReadStatusSchema = z.object({
  /** Message ID (`msg_...`) of the last message the user has read in this thread. `null` if the user has never read any message in the thread. */
  last_read_message: z.string().optional().describe("Message ID (`msg_...`) of the last message the user has read in this thread. `null` if the user has never read any message in the thread."),
  /** Thread ID (`thr_...`) that this read status belongs to. */
  thread: z.string().describe("Thread ID (`thr_...`) that this read status belongs to."),
  /** Number of messages in the thread that the user has not yet read. */
  unread_count: z.number().int().describe("Number of messages in the thread that the user has not yet read."),
}).describe("The read status of a thread for a specific user, indicating how far they have read and how many messages remain unread.") satisfies z.ZodType<ThreadReadStatus>;
