// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 49ab1024bdac

import { z } from "zod";

/** API schema for a user. */
export const userSchema = z.object({
  alias: z.string().optional(), // User alias/handle
  email: z.string().optional(), // User email address
  id: z.string(), // User ID
  metadata: z.record(z.unknown()).optional(), // User metadata
  name: z.string().optional(), // User display name
  org: z.string().optional(), // Organization
  sandbox: z.string().optional(), // Sandbox
});
export type User = z.infer<typeof userSchema>;

/** API schema for a user invite. */
export const userInviteSchema = z.object({
  created_at: z.string().optional(), // Creation timestamp
  id: z.string(), // Invite ID (uin_...)
  key: z.string().optional(), // Invite key
  metadata: z.record(z.unknown()).optional(), // Invite metadata
  thread: z.string().optional(), // Thread
  user: userSchema.optional(), // Invite creator
});
export type UserInvite = z.infer<typeof userInviteSchema>;

/** API schema for user feedback on messages. */
export const userFeedbackSchema = z.object({
  comment: z.string().optional(), // Optional comment
  created_at: z.string().optional(), // Creation timestamp
  id: z.string(), // Feedback ID
  message: z.string(), // Message
  org: z.string().optional(), // Organization
  rating: z.string(), // Rating (positive/negative)
  sandbox: z.string().optional(), // Sandbox
  source: z.string(), // Feedback source
  thread: z.string(), // Thread
  updated_at: z.string().optional(), // Update timestamp
});
export type UserFeedback = z.infer<typeof userFeedbackSchema>;
