// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 2cf2247d02d7

import { z } from "zod";

/** One ordered, replayable record from a durable workflow journal. */
export interface WorkflowJournalEntry {
  /** Durable command identifier associated with the record, when present. */
  command_id?: string | undefined;
  /** When this entry was durably committed. */
  created_at?: string | undefined;
  /** Journal entry ID (`wdr_...`). */
  id: string;
  /** Workflow node associated with the record. `null` for execution-level records. */
  node_id?: string | undefined;
  /** Replayable workflow record body, including payload, context, environment, metadata, and timestamp. */
  record: Record<string, unknown>;
  /** Monotonically increasing sequence within the journal. */
  sequence: number;
  /** Durable timer identifier associated with the record, when present. */
  timer_id?: string | undefined;
  /** Workflow record type, such as `node_started`, `node_completed`, or `node_failed`. */
  type: string;
}

/** Runtime validator for {@link WorkflowJournalEntry}. */
export const workflowJournalEntrySchema = z.object({
  /** Durable command identifier associated with the record, when present. */
  command_id: z.string().optional().describe("Durable command identifier associated with the record, when present."),
  /** When this entry was durably committed. */
  created_at: z.string().optional().describe("When this entry was durably committed."),
  /** Journal entry ID (`wdr_...`). */
  id: z.string().describe("Journal entry ID (`wdr_...`)."),
  /** Workflow node associated with the record. `null` for execution-level records. */
  node_id: z.string().optional().describe("Workflow node associated with the record. `null` for execution-level records."),
  /** Replayable workflow record body, including payload, context, environment, metadata, and timestamp. */
  record: z.record(z.custom<{} | null>((value) => value !== undefined)).describe("Replayable workflow record body, including payload, context, environment, metadata, and timestamp."),
  /** Monotonically increasing sequence within the journal. */
  sequence: z.number().int().describe("Monotonically increasing sequence within the journal."),
  /** Durable timer identifier associated with the record, when present. */
  timer_id: z.string().optional().describe("Durable timer identifier associated with the record, when present."),
  /** Workflow record type, such as `node_started`, `node_completed`, or `node_failed`. */
  type: z.string().describe("Workflow record type, such as `node_started`, `node_completed`, or `node_failed`."),
}).describe("One ordered, replayable record from a durable workflow journal.") satisfies z.ZodType<WorkflowJournalEntry>;

/** Summary of the durable workflow execution journal associated with a run. */
export interface WorkflowJournal {
  /** When durable workflow execution reached a terminal state. `null` while it is active. */
  completed_at?: string | undefined;
  /** When the journal was created. */
  created_at?: string | undefined;
  /** Highest workflow record sequence durably committed to this journal. */
  current_sequence: number;
  /** Journal execution ID (`wde_...`). */
  id: string;
  /** When durable workflow execution started. */
  started_at?: string | undefined;
  /** Current durable execution status: `pending`, `running`, `waiting`, `completed`, `failed`, or `cancelled`. */
  status: string;
  /** When the journal was last updated. */
  updated_at?: string | undefined;
}

/** Runtime validator for {@link WorkflowJournal}. */
export const workflowJournalSchema = z.object({
  /** When durable workflow execution reached a terminal state. `null` while it is active. */
  completed_at: z.string().optional().describe("When durable workflow execution reached a terminal state. `null` while it is active."),
  /** When the journal was created. */
  created_at: z.string().optional().describe("When the journal was created."),
  /** Highest workflow record sequence durably committed to this journal. */
  current_sequence: z.number().int().describe("Highest workflow record sequence durably committed to this journal."),
  /** Journal execution ID (`wde_...`). */
  id: z.string().describe("Journal execution ID (`wde_...`)."),
  /** When durable workflow execution started. */
  started_at: z.string().optional().describe("When durable workflow execution started."),
  /** Current durable execution status: `pending`, `running`, `waiting`, `completed`, `failed`, or `cancelled`. */
  status: z.string().describe("Current durable execution status: `pending`, `running`, `waiting`, `completed`, `failed`, or `cancelled`."),
  /** When the journal was last updated. */
  updated_at: z.string().optional().describe("When the journal was last updated."),
}).describe("Summary of the durable workflow execution journal associated with a run.") satisfies z.ZodType<WorkflowJournal>;

/** Externally executable work yielded by a durable workflow. */
export interface WorkflowWorkItem {
  /** Agent assigned to execute this work. */
  agent: string;
  /** Number of times this work has been freshly claimed or reclaimed. */
  attempt_count: number;
  /** Opaque journal command identity used to resume the workflow exactly once. */
  command_id: string;
  created_at: string;
  /** Durable workflow execution that owns this work. */
  execution: string;
  /** Work item ID (`wdi_...`). */
  id: string;
  /** When the current claim expires. Null for queued or terminal work. */
  lease_expires_at?: string | undefined;
  /** Workflow graph node that yielded the work. */
  node_id: string;
  /** Instructions and participant bindings needed to execute the work. */
  payload: Record<string, unknown>;
  /** Routine run that owns the execution, when this work came from a routine. */
  routine_run?: string | undefined;
  /** Current queue lifecycle status. */
  status: string;
  /** Stable resource discriminator. Always `workflow_work_item`. */
  type: string;
  updated_at: string;
}

/** Runtime validator for {@link WorkflowWorkItem}. */
export const workflowWorkItemSchema = z.object({
  /** Agent assigned to execute this work. */
  agent: z.string().describe("Agent assigned to execute this work."),
  /** Number of times this work has been freshly claimed or reclaimed. */
  attempt_count: z.number().int().describe("Number of times this work has been freshly claimed or reclaimed."),
  /** Opaque journal command identity used to resume the workflow exactly once. */
  command_id: z.string().describe("Opaque journal command identity used to resume the workflow exactly once."),
  created_at: z.string(),
  /** Durable workflow execution that owns this work. */
  execution: z.string().describe("Durable workflow execution that owns this work."),
  /** Work item ID (`wdi_...`). */
  id: z.string().describe("Work item ID (`wdi_...`)."),
  /** When the current claim expires. Null for queued or terminal work. */
  lease_expires_at: z.string().optional().describe("When the current claim expires. Null for queued or terminal work."),
  /** Workflow graph node that yielded the work. */
  node_id: z.string().describe("Workflow graph node that yielded the work."),
  /** Instructions and participant bindings needed to execute the work. */
  payload: z.record(z.custom<{} | null>((value) => value !== undefined)).describe("Instructions and participant bindings needed to execute the work."),
  /** Routine run that owns the execution, when this work came from a routine. */
  routine_run: z.string().optional().describe("Routine run that owns the execution, when this work came from a routine."),
  /** Current queue lifecycle status. */
  status: z.string().describe("Current queue lifecycle status."),
  /** Stable resource discriminator. Always `workflow_work_item`. */
  type: z.string().describe("Stable resource discriminator. Always `workflow_work_item`."),
  updated_at: z.string(),
}).describe("Externally executable work yielded by a durable workflow.") satisfies z.ZodType<WorkflowWorkItem>;

/** A claimed workflow work item and its caller-held lease token. */
export interface WorkflowWorkItemLease {
  /** Opaque lease token that must be persisted and presented for later transitions. */
  lease_owner: string;
  /** The claimed, resumed, started, or heartbeated work item. */
  work_item: WorkflowWorkItem;
}

/** Runtime validator for {@link WorkflowWorkItemLease}. */
export const workflowWorkItemLeaseSchema = z.object({
  /** Opaque lease token that must be persisted and presented for later transitions. */
  lease_owner: z.string().describe("Opaque lease token that must be persisted and presented for later transitions."),
  /** The claimed, resumed, started, or heartbeated work item. */
  work_item: workflowWorkItemSchema.describe("The claimed, resumed, started, or heartbeated work item."),
}).describe("A claimed workflow work item and its caller-held lease token.") satisfies z.ZodType<WorkflowWorkItemLease>;

/** Result of polling an agent's durable workflow work queue. */
export interface WorkflowWorkItemClaim {
  /** Claimed or resumed work and its lease; null when no eligible item exists. */
  data?: WorkflowWorkItemLease | undefined;
}

/** Runtime validator for {@link WorkflowWorkItemClaim}. */
export const workflowWorkItemClaimSchema = z.object({
  /** Claimed or resumed work and its lease; null when no eligible item exists. */
  data: workflowWorkItemLeaseSchema.optional().describe("Claimed or resumed work and its lease; null when no eligible item exists."),
}).describe("Result of polling an agent's durable workflow work queue.") satisfies z.ZodType<WorkflowWorkItemClaim>;

/** Active durable workflow work available to the viewer. */
export interface WorkflowWorkItemList {
  /** Opaque cursor for the next page, or null at the end. */
  after_cursor?: string | undefined;
  /** Always null because queue pagination is forward-only. */
  before_cursor?: string | undefined;
  /** Active work items. Lease tokens are intentionally never included in list responses. */
  data: WorkflowWorkItem[];
  /** Whether another page of work exists. */
  has_more: boolean;
}

/** Runtime validator for {@link WorkflowWorkItemList}. */
export const workflowWorkItemListSchema = z.object({
  /** Opaque cursor for the next page, or null at the end. */
  after_cursor: z.string().optional().describe("Opaque cursor for the next page, or null at the end."),
  /** Always null because queue pagination is forward-only. */
  before_cursor: z.string().optional().describe("Always null because queue pagination is forward-only."),
  /** Active work items. Lease tokens are intentionally never included in list responses. */
  data: z.array(workflowWorkItemSchema).describe("Active work items. Lease tokens are intentionally never included in list responses."),
  /** Whether another page of work exists. */
  has_more: z.boolean().describe("Whether another page of work exists."),
}).describe("Active durable workflow work available to the viewer.") satisfies z.ZodType<WorkflowWorkItemList>;
